Feature/custom app lock
wireapp/wire-ios pull request #4495
Opened 2020-07-29 17:09 UTC by billypchan

## What's new in this PR?

2020-09-04 16:06 UTC, typfel requested changes

2020-09-04 16:06 UTC, typfel commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        callback?(false) ///TODO: need call back?
I guess it's not necessary? If so then you could move the dismiss logic inside the `PasscodeSetupViewController`.

2020-09-04 16:06 UTC, typfel commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +extension SelfProfileViewController: UIAdaptivePresentationControllerDelegate {
Perhaps we shouldn't allow the Passcode setup screen to swiped away? Then we wouldn't need this code...

2020-09-07 08:50 UTC, billypchan commented
@typfel I will create a new PR to the fixes to prevent this PR grows bigger.

2020-09-08 07:10 UTC, billypchan commented on azure-pipelines.yml
> +    fastlane prepare config_branch:feature/customAppLock
```suggestion
    fastlane prepare
```

2020-09-08 07:10 UTC, billypchan commented on fastlane/Fastfile
> +                config_branch = "feature/customAppLock"
```suggestion
                config_branch = "master"
```

2020-09-08 07:21 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +                userInterface?.presentCreatePasscodeScreen(callback: { _ in
done.

2020-09-08 07:22 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +extension SelfProfileViewController: UIAdaptivePresentationControllerDelegate {
I would keep the card style presentation to align iOS 13 UI guideline.

2020-09-08 07:27 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AppLock.rules.useCustomCodeInsteadOfAccountPassword else { return }
Yes, since in this method the create new passcode/delete existing passcode only relevant to custom passcode. The user can not change or delete his/her account password.

2020-09-08 07:38 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +                                callback: @escaping ResultHandler) {
I would keep the callback here for now since `SelfProfileViewController` extends `SettingsPropertyFactoryDelegate` and owns `SettingsPropertyFactory` which changes `AppLock.isActive`.

2020-09-11 12:34 UTC, typfel commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AppLock.rules.useCustomCodeInsteadOfAccountPassword else { return }
But it isn't this also the method which sets `AppLock.isActive = true/false/`?

Don't we need:

```
guard AppLock.rules.useCustomCodeInsteadOfAccountPassword else { 
     AppLock.isActive = newValue
     return 
}

2020-09-11 13:28 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AppLock.rules.useCustomCodeInsteadOfAccountPassword else { return }
The delegate method `appLockOptionDidChange` is only relevant to custom passcode. When `AppLock.rules.useCustomCodeInsteadOfAccountPassword` feature flag is false it does not do anything.

2020-09-14 07:59 UTC, typfel commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AppLock.rules.useCustomCodeInsteadOfAccountPassword else { return }
Exactly the problem is that you don't call the `callback` in the guard return block, which means that we will never update `AppLock.isActive` when `useCustomCodeInsteadOfAccountPassword` is `false`.

see:

```
                self.delegate?.appLockOptionDidChange(self,
                                                              newValue: lockApp.boolValue,
                                                              callback: { result in
                            AppLock.isActive = result
                        }) 
```

2020-09-14 09:12 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AppLock.rules.useCustomCodeInsteadOfAccountPassword else { return }
Cleaned up the code and add the callback in the guard block

2020-09-14 09:44 UTC, typfel commented on Cartfile.resolved
> +github "wireapp/wire-ios-data-model" "refactor/notification-extension"
`Cartfile.resolved` is referring to development branches

2020-09-14 09:49 UTC, billypchan commented on Cartfile.resolved
> +github "wireapp/wire-ios-data-model" "refactor/notification-extension"
cartfile updated.

2020-09-14 10:07 UTC, typfel approved these changes

2020-09-14 10:18 UTC, merged

2020-10-01 08:05 UTC, watcher699 reviewed
Ok