Set user when switching accounts
wireapp/wire-ios pull request #4599
Opened 2020-09-22 15:12 UTC by billypchan

## What's new in this PR?

Update Countly user properties when the user switches between different accounts.

2020-09-23 16:27 UTC, typfel requested changes
So we can only track events for the active account? I guess that's fine we only generate events when the application is in the foreground.

2020-09-23 16:27 UTC, typfel commented on Wire-iOS/Sources/Analytics/Analytics.swift
> +        selfUser = ZMUser.selfUser()
Can't we use `SelfUser.current`? Same question applies for other places where you get the self user.

2020-09-23 16:27 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +            let _ = selfUser.team else {
What are we checking here, if the self user belongs to a team? If so you could use `isTeamMember` instead and avoid the cast to `ZMUser`.

2020-09-23 16:27 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +            let team = selfUser.team else {
Is the only thing we query from the `Team` objects the number of members? Then we could consider exposing that on the `UserType` or expose a `TeamType` on the `UserType`.

2020-09-24 10:41 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +            let team = selfUser.team else {
fixed

2020-09-24 10:43 UTC, billypchan commented on Wire-iOS/Sources/Analytics/Analytics.swift
> +        selfUser = ZMUser.selfUser()
fixed

2020-09-24 10:44 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +            let _ = selfUser.team else {
fixed.

2020-09-25 07:27 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +                Countly.user().set("user_id", value: (self.selfUser as? ZMUser )?.userId.uuid.zmSHA256Digest().zmHexEncodedString() ?? "")
What is this `user_id` property we are setting here? Seems strange that we are sending the `user_id` of the self user when are going through the trouble of generating a random analytics identifier.

2020-09-25 08:11 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +                Countly.user().set("user_id", value: (self.selfUser as? ZMUser )?.userId.uuid.zmSHA256Digest().zmHexEncodedString() ?? "")
the hashed user id is required in the spec, I will discuss again to see if the user id need to be unset also for non team users.

2020-09-25 09:29 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +                Countly.user().set("user_id", value: (self.selfUser as? ZMUser )?.userId.uuid.zmSHA256Digest().zmHexEncodedString() ?? "")
after discussion, this case is not likely to happen and since we do not track for non-team users, I will clean the user id.

2020-09-25 10:23 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +                Countly.user().set("user_id", value: (self.selfUser as? ZMUser )?.userId.uuid.zmSHA256Digest().zmHexEncodedString() ?? "")
Do we send the `analyticsIdentifier` in a different way?

2020-09-25 12:15 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    var userIdHash: String? {
This was outdated and needs to be replaced by the `analyticsIdentifier`

2020-09-28 08:36 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +                Countly.user().set("user_id", value: (self.selfUser as? ZMUser )?.userId.uuid.zmSHA256Digest().zmHexEncodedString() ?? "")
add a TODO for now and usr_id will be filled in next PR.

2020-09-28 08:40 UTC, typfel approved these changes

2020-09-28 08:52 UTC, merged