Feature: restore analytics calling tracker
wireapp/wire-ios pull request #4602
Opened 2020-09-23 14:54 UTC by billypchan

## What's new in this PR?

Restore AnalyticsCallingTracker and add new screen share tracking.

2020-09-25 10:14 UTC, typfel requested changes

2020-09-25 10:14 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +    func callParticipantsDidChange(conversation: ZMConversation, participants: [CallParticipant]) {
This will get called for many reason not only when screen sharing is turned on or off, for example when a participant mutes himself/herself.

- You would need guard against only updating `screenSharingStartTime` the first time you discover `videoState == .screenSharing` is on.
- What about if someone turn screen sharing on or off many times during a call?
- What about if the call ends while screen sharing is on? Then you wouldn't have any `screenSharingEndTime` set?
- What if multiple people screen shared during a call? Should we maybe send multiple events during a call?

2020-09-25 10:14 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Log.calling.error("UserSession not available when .established call")
I would never except this to happen. If you still want to log something I think we should do it under a separate Analytics tag.

2020-09-25 10:14 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                    analytics.tag(callEvent: .screenSharing(duration: (screenSharingEndTime ?? Date()).timeIntervalSince(start)),
As mentioned above maybe this is not right place to send this event?

2020-09-25 10:14 UTC, typfel commented on Wire-iOS Tests/Analytics/AnalyticsCountlyProviderTests.swift
> +        XCTAssertEqual(convertedDictionary, ["conversation_guests_wireless": "0", "is_allow_guests": "False", "conversation_type": "one_to_one", "conversation_guests_pro": "0", "user_type": "user", "
Formatting?

2020-09-25 11:31 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +    func callParticipantsDidChange(conversation: ZMConversation, participants: [CallParticipant]) {
the current logic design just records the last screen share timing from any other remote user. I would discuss this with the PM.

2020-09-25 12:02 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +    func callParticipantsDidChange(conversation: ZMConversation, participants: [CallParticipant]) {
Still would need to account for the fact the `callParticipantsDidChange` is also called when the user mutes himself.

2020-09-25 12:05 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Log.calling.error("UserSession not available when .established call")
fixed

2020-09-25 12:18 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Log.calling.error("UserSession not available when .established call")
How is this fixed? I see no change.

2020-09-28 07:54 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +    func callParticipantsDidChange(conversation: ZMConversation, participants: [CallParticipant]) {
rewrite the screen duration recording and it tags event when screen sharing is ended.

2020-09-28 08:38 UTC, typfel requested changes

2020-09-28 08:38 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +        }
This approach is much better! It has some bugs though:

- Multiple `ScreenSharingInfo` will get inserted for the same user when `callParticipantsDidChange()` called repeatedly.
- Having a `screenSharingInfos` set makes me think we want to support tracking multiple users screen sharing at the same time but that doesn't work due to the `first(where:)` usage. Either make it work for multiple users or replace the set with a single value.
- Code is hard to read, maybe break it up separate statements instead of one big nested if statement.

2020-09-28 08:38 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Log.calling.error("UserSession not available when .established call")
I would also log this an analytics error.

2020-09-28 08:38 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +                                             "user_id": selfUser.userId.uuid.zmSHA256Digest().zmHexEncodedString(),
This is still wrong but I guess will be fixed in https://github.com/wireapp/wire-ios/pull/4599/files ?

2020-09-28 10:06 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Log.calling.error("UserSession not available when .established call")
fixed

2020-09-28 10:08 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +                                             "user_id": selfUser.userId.uuid.zmSHA256Digest().zmHexEncodedString(),
fixed after merging

2020-09-28 14:00 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +        }
- the `ScreenSharingInfo` object is inserted only when the participant has a video state == `.screenSharing` and it will be removed from `screenSharingInfos` set when screen sharing ends. I would add a test to show that.
- when multiple screen share starts, it will insert several `ScreenSharingInfo` objects with different `clientId` and tracking them is possible. (I will add a test)
- I will refactor the code.

2020-09-30 21:03 UTC, typfel approved these changes

2020-10-01 06:58 UTC, merged