[Feature]: AppStateController Refactoring
wireapp/wire-ios pull request #4632
Opened 2020-10-06 12:53 UTC by marcomaddy1982

## What's new in this PR?

The context of this PR is the App Launching Routing Refactoring. The idea is separate it in smaller chunks that are easier to review. I thought that a reasonable starting point could be refactor the AppState and the way we calculate it in the AppStateController.
Previously in the AppStateController you could have found a lot of variables used to calculate the current AppState. These variables were set in the SessionManagerDelagate methods and used in the calculateAppState() method to find the current appState. This approach is really verbose and it have been produced a lot of not necessary code.
The idea behind this PR is set directly the appState in the SessionManagerDelagate call backs and get rid of all the variables used in the calculateAppState() and of the method itself.
Moreover to decouple the AppStateController from the SessionManagerDelagate callbacks (and make it lighter) I decided to create the AppStateSessionManagerObserver. The scope of this class is to inform the AppStateController of the new AppState, in this manner the only dirty of the AppStateController will be transit (when necessary) from a state to another.

It seems to works fine but It would be nice if some of you at some point could do other manual test.

P.S: Any other idea is super well accepted

2020-10-06 13:24 UTC, johnxnguyen reviewed
So now all the app state calculation is done in separate class, what is the role of the `AppStateController`?

2020-10-06 13:38 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +    private(set) var appStateCalculator = AppStateCalculator()
Can be `private let`.

2020-10-06 13:48 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateController.swift
> +    private(set) var appStateCalculator = AppStateCalculator()
I could not use `private let` cause it is passed through dependency injection in the `SessionManager.create`. Moreover in swift it is not possible (for obvious reasons) define a property as `private(set) let`.

2020-10-07 06:57 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +    private(set) var appStateCalculator = AppStateCalculator()
Ah sorry, I mean it can be `let` since it's never mutated.

2020-10-07 07:03 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateController.swift
> +    private(set) var appStateCalculator = AppStateCalculator()
Ok we can make it public and and as a `let`. The idea was encapsulate it and protect from external set, that's why I used `private(set) let` but using `let` it is super fine as well :-D

2020-10-07 07:22 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> -        guard !isRunningTests || isRunningSelfUnitTest else { return .headless }
Do we not need these flags anymore?

2020-10-07 07:26 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateController.swift
> -        guard !isRunningTests || isRunningSelfUnitTest else { return .headless }
It seems no, cause when the tests are running at the start the appStae is always `headless`, moreover all the test are passing as before.

2020-10-07 14:16 UTC, typfel requested changes
Good changes, I agree that the logic the is easier to follow now without all the boolean flags and don't quite see benefit of extracting the AppState calculation into a separate class. Why not keep `SessionManagerDelegate` implementation inside the `AppStateController`?

2020-10-07 14:16 UTC, typfel commented on Wire-iOS/Sources/AppStateController.swift
> +// TO DO: Ask why AuthenticationCoordinatorDelegate implements AuthenticationStatusProvider. For the scope of knowing the appState it is not necessary. We could get rid off all the AuthenticationStat
True, it's not necessary for calculating the AppState. The `AuthenticationStatusProvider` is was creating as way to abstract the registration / login code from accessing the SessionManager directly for easier testing. 

`AppStateController` doesn't necessarily need to implement `AuthenticationStatusProvider` but then something else need to take over that responsibility.

2020-10-07 14:16 UTC, typfel commented on Wire-iOS/Sources/AppStateController.swift
>      func userAuthenticationDidComplete(addedAccount: Bool) {
It kind of breaks the abstraction that this not inside the `AppStateCalculator`.

2020-10-07 14:21 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateController.swift
>      func userAuthenticationDidComplete(addedAccount: Bool) {
The other PR  (https://github.com/wireapp/wire-ios/pull/4635) will cover this part.

2020-10-07 14:22 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateController.swift
> +// TO DO: Ask why AuthenticationCoordinatorDelegate implements AuthenticationStatusProvider. For the scope of knowing the appState it is not necessary. We could get rid off all the AuthenticationStat
The other PR (#4635) will cover this part.

2020-10-07 14:32 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    func sessionManagerDidBlacklistCurrentVersion() {
Ok, I will take a note

> Good changes, I agree that the logic the is easier to follow now without all the boolean flags and don't quite see benefit of extracting the AppState calculation into a separate class. Why not keep `SessionManagerDelegate` implementation inside the `AppStateController`?

Actually after this other PR (#4635) I think that there is no need to extracting the `AppState` calculation into a separate class. Anyway I would rename the `AppStateController` in `AppStateCalculator`. To do this I should merge the (#4635) into this.

2020-10-07 14:34 UTC, marcomaddy1982 commented
> Good changes, I agree that the logic the is easier to follow now without all the boolean flags and don't quite see benefit of extracting the AppState calculation into a separate class. Why not keep `SessionManagerDelegate` implementation inside the `AppStateController`?

Actually after this other PR (#4635) I think that there is no need to extracting the `AppState` calculation into a separate class. Anyway I would rename the `AppStateController` in `AppStateCalculator`. To do this I should merge the (#4635) into this.

2020-10-07 14:36 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    func sessionManagerDidBlacklistCurrentVersion() {
We should take a note to this. But for now I guess we should keep the stuffs in the UI as they are. What do you think about?

2020-10-07 14:47 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    func sessionManagerDidBlacklistCurrentVersion() {
Yes, we can keep things are as they are in the UI but only if we make the change I suggested in sync engine.

2020-10-07 14:54 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    func sessionManagerDidBlacklistCurrentVersion() {
Ok should we change the sync engine before merging this PR?

2020-10-07 15:04 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateController.swift
> -    @objc func applicationDidBecomeActive() {
Done

2020-10-07 15:22 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                     didCalculate: .headless,
This not correct, we should move away from .headless when the app becomes active.

2020-10-07 15:24 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                     didCalculate: .headless,
I guess is hard to do without keeping the current appState in a variable or something.

2020-10-07 15:26 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    func sessionManagerDidBlacklistCurrentVersion() {
Why not do it now so that you don't forget about it, I think it will be a fairly small change.

2020-10-07 15:28 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                     didCalculate: .headless,
so if I understood correctly we should keep the lastAppState and in the `applicationDidBecomeActive()` propagate it. Am I right?

2020-10-07 15:46 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    func sessionManagerDidBlacklistCurrentVersion() {
Of course.

2020-10-07 15:49 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                     didCalculate: .headless,
Yes

2020-10-07 16:11 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                     didCalculate: .headless,
But you also need make sure that we we don't propagate any app state changes before the application has become active.

2020-10-07 16:13 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    static let appStateDidTransit = Notification.Name(rawValue: "AppStateDidTransit")
Was this intentionally renamed from `appStateDidTransition`?

2020-10-07 16:15 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                     didCalculate: .headless,
I'm a bit lost now. So which is your suggestion?

2020-10-07 16:16 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    static let appStateDidTransit = Notification.Name(rawValue: "AppStateDidTransit")
Yes, I guess now reading again it sound pretty bad. Any suggestion?

2020-10-07 16:19 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    static let appStateDidTransit = Notification.Name(rawValue: "AppStateDidTransit")
Change is back to `appStateDidTransition`? That what would be inline with how the methods are named.

2020-10-08 07:26 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                     didCalculate: .headless,
Done

2020-10-08 08:43 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    }
A couple things: 

1. It would be cleaner to remove the replace the stored property `forceTransition` with an argument to `transition`. It's one less mutable state to maintain. 
2. It's possible for `propagate` to be called twice, if the `appState` is different and the transition is force. This might have unintended consequences.
3. `forceTransition` seems to really mean "force transition propagation", because we update the appState regardless. I think we can express intent more clearly by propagating the appState every time we update it's value, and only update if it changes or is forced. This also allows you to remove some code duplication.

```swift
private func transition(to appState: AppState, force: Bool = false, completion: ...) {
  guard self.appState != appState || force else {
    completion?()
    return
  }
  
  self.appState = appState
  delegate?.appStateCalculator(self, didCalculate: appState, completion: ...)
}

```

2020-10-08 09:04 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    }
I really like it. Thanks. Much better in this manner.

2020-10-08 09:08 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    }
Btw in your suggestion it is not taking in consideration the `previousAppState.

2020-10-08 09:21 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +    }
Done

2020-10-09 14:52 UTC, typfel approved these changes

2020-10-12 08:37 UTC, merged