[Fix] Accept 2 file extensions
wireapp/wire-ios pull request #4634
Opened 2020-10-06 15:27 UTC by KaterinaWire

## What's new in this PR?

### Issues
When you sent a backup file through the email, the Gmail app changes the file extension.(xxx.**ios_wbu** to xxx.**ios-wbu**).

### Causes
There is the Gmail app issue.
https://support.google.com/mail/thread/15716995?hl=en

### Solutions
To be able to accept both file extensions.

### Dependencies

https://github.com/wireapp/wire-ios/issues/4609

2020-10-06 16:02 UTC, marcomaddy1982 approved these changes

2020-10-06 16:12 UTC, billypchan commented on Wire-iOS/Sources/Authentication/Backup/BackupRestoreController.swift
> +    static let WireBackupAdditionalUTI = "com.wire.backup-ios-additional"
We can create a static array like 
```suggestion
    static let WireBackupUTIs = ["com.wire.backup-ios", "com.wire.backup-ios-additional"]
```

2020-10-07 07:18 UTC, johnxnguyen requested changes
I think we can improve the naming here to avoid confusion in the future. Are we able to modify the existing UTI (not the extension, just the naming)? Something like `com.wire.backup-ios-underscore` and `com.wire.backup-ios-hyphen`. I think it would also need a comment to explain why we have these two types.

2020-10-07 09:11 UTC, KaterinaWire commented
> I think we can improve the naming here to avoid confusion in the future. Are we able to modify the existing UTI (not the extension, just the naming)? Something like `com.wire.backup-ios-underscore` and `com.wire.backup-ios-hyphen`. I think it would also need a comment to explain why we have these two types.

@johnxnguyen Yes, it's possible to modify the  existing UTI name. I've made it and added a comment.

2020-10-07 09:14 UTC, johnxnguyen approved these changes

2020-10-07 11:37 UTC, billypchan requested changes

2020-10-07 11:37 UTC, billypchan commented on Cartfile.resolved
> +github "wireapp/wire-ios-sync-engine" "fix/accept-a-second-file-extension-for-backup"
This needs to be restored before merging.

2020-10-08 09:54 UTC, KaterinaWire commented on Cartfile.resolved
> +github "wireapp/wire-ios-sync-engine" "fix/accept-a-second-file-extension-for-backup"
Done

2020-10-08 11:43 UTC, billypchan approved these changes

2020-10-08 12:18 UTC, merged