[Fix] Add new app state
wireapp/wire-ios pull request #4649
Opened 2020-10-13 08:16 UTC by KaterinaWire

## What's new in this PR?

### Issues
When the applock is enable and client accepts a call through CallKit, the client has no visual elements about the current call.

### Solutions
Add a new app state ʻappLocked` and not handle the call when the app is in this state.

### Dependencies
wireapp/wire-ios-sync-engine/pull/1323

2020-10-13 09:17 UTC, johnxnguyen commented on Wire-iOS/Sources/AppRootViewController.swift
> +                }
Do we need to switch to the account for that pending call? Or is this logic already present in session manager?

2020-10-13 09:17 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +        NotificationCenter.default.post(name: .appLocked, object: self, userInfo: nil)
So this is triggering the change of app state to `.appLocked`. I would expect it to be the other way around, that when we transition to `.appLocked` then we display the app lock ui.

2020-10-13 13:20 UTC, billypchan commented on Wire-iOS/Sources/AppStateController.swift
> +    @objc func applicationDidBecomeLocked() {
```suggestion
    @objc 
    private func applicationDidBecomeLocked() {
```

2020-10-13 14:33 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +        NotificationCenter.default.post(name: .appLocked, object: self, userInfo: nil)
This was changed as we discussed during the call.

2020-10-14 08:10 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +    }
I suggest to move this to a senate object and extract a protocol from it. This will improve your tests.

2020-10-14 09:03 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +        object: .none)
Fixed

2020-10-14 09:03 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
>      }
No.
Removed

2020-10-14 09:03 UTC, KaterinaWire commented on Wire-iOS/Sources/AppState.swift
> +    case appLocked
Done

2020-10-14 09:04 UTC, KaterinaWire commented on Wire-iOS/Sources/AppRootViewController.swift
> +                }
Ok, I will move it to the next PR

2020-10-14 09:48 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +    }
I'm not 100% sure what you meant, but I moved this logic into a separate protocol. You can check it in my last commit.

2020-10-14 12:47 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +final class AppStateController : NSObject, ScreenLockHelperProtocol {
I meant to move this code into some concrete type, abstract it with a protocol and refer to the protocol in `AppStateController`. So it would look something like:

```swift
protocol AppLockTimerProtocol {
  var shouldLockApp: Bool { get }
}

class AppStateController {

  // This should be injectable, so when testing we can provide a different implementation.
  let appLockTimer: AppLockTimerProtocol
  
  func calculateAppState() {
    ...
    switch authenticationState {
    case .loggedIn where isDatabaseLocked || appLockTimer.shouldLockApp:
     appState = .locked
      ...
    }
  }
}
```

You could then provide a test implementation that can return true of false as you wish (no time calculation at all) and inject that when testing.

2020-10-14 15:20 UTC, typfel requested changes

2020-10-14 15:20 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
>              AppLock.lastUnlockedDate = Date()
Don't we need to move this somewhere else since the `AppLockPresenter` will not be instantiated when the app is unlocked and the app enters the background.

2020-10-14 15:20 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +    static let appLocked = Notification.Name("AppLocked")
NOTE: Can't comment on correct line so I'm commenting here.

isn't the `AuthenticationState.authenticated` state unnecessary now since we won't show the AppLock at all when authenticated?

2020-10-14 15:20 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.swift
>  final class NotificationWindowRootViewController: UIViewController {
This class does nothing now?

2020-10-15 09:07 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.swift
>  final class NotificationWindowRootViewController: UIViewController {
Seems like yes, but removing this class requires removing instances from other parts of the code. I would prefer to do it in another PR.

2020-10-15 15:27 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
>              AppLock.lastUnlockedDate = Date()
Yes.
I moved this observer to the `AppStateController`

2020-10-15 15:28 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +    static let appLocked = Notification.Name("AppLocked")
Yes, we don't need it now

2020-10-16 05:28 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
> -    var isAuthenticationNeeded: Bool {
Yes, we don't need it anymore.

2020-10-16 07:22 UTC, johnxnguyen commented on Wire-iOS Tests/AppLock/AppLockViewControllerSnapshotTests.swift
>      }
Is this test needed anymore?

2020-10-16 07:22 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +
Better to move this to a separate file so as not to clutter up this one.

2020-10-16 07:22 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +    }
It's better to create another type to implement this protocol, since the point is to able to inject a mock implementation to make testing easier.

2020-10-16 07:22 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +        appLock = self
There's not much sense for `self.appLock` to hold a reference to itself. This value should be injectable (for tests), but it we can of course initialize a default value.

2020-10-16 07:22 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +
The name could be improved by describing the behavior of the abstraction. If this is an abstraction over a timer object that tells us whether we should lock the screen, then `AppLockTimerProtocol` would be more suitable.

2020-10-16 07:22 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
> +    private var lockView: AppLockView?
Why did this become optional?

2020-10-16 15:15 UTC, typfel requested changes

2020-10-16 15:15 UTC, typfel commented on Wire-iOS/Sources/AppStateController.swift
> +    internal var isDatabaseLocked = false
Why did this become internal? Are you modifying it in a test?

2020-10-16 15:15 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
> -            return .databaseLock
Why was the .databaseLock scenario removed? When the database is locked we can only unlock with biometric or passcode **not** the account password.

2020-10-16 15:15 UTC, typfel commented on Wire-iOS/Sources/AppState.swift
>      case authenticated(completedRegistration: Bool, databaseIsLocked: Bool)
I think we should remove the `databaseIsLocked` associated value or move it to the `.locked` case.

2020-10-16 15:15 UTC, typfel commented on Wire-iOS/Sources/AppStateController.swift
> +    @objc func applicationDidEnterBackground() {
I think when AppLock is active we always dim the screen when app will enter the background regardless if the lock timer as expired. That way you can't read any message from screenshot in the iOS task manager.

2020-10-16 15:32 UTC, typfel commented
Have you tested this on a real device? With and without EAR enabled?

2020-10-19 11:58 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockViewControllerSnapshotTests.swift
>      }
No. I deleted it.

2020-10-19 11:59 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +
Changed the name and moved it to a separate file.

2020-10-19 12:01 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +    }
Removed this extension. I created a helper class `AppLockTimer` that implements `AppLockTimerProtocol`.

2020-10-19 12:29 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +        appLock = self
In init() of the AppStateController class I added a  default value:
appLockTimer = AppLockTimer()
(`AppLockTimer` is a class that  implements `AppLockTimerProtocol`)

2020-10-19 13:04 UTC, johnxnguyen commented on Wire-iOS Tests/AppStateControllerTests.swift
> +        AppLock.lastUnlockedDate = Date(timeIntervalSinceNow: timeInterval)
Now that you have a protocol abstraction of the app lock timer, you can define a mock timer and use that during testing. This means you don't' need any of this logic in your tests anymore.

For example:

```swift
struct MockAppLockTimer: AppLockTimerProtocol {
    var shouldLock: Bool

    var shouldLockApp: Bool {
        return shouldLock
    }
}

2020-10-19 13:04 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +    var appLockTimer: AppLockTimerProtocol?
This doesn't need to be optional since you always provide a value.

2020-10-19 13:31 UTC, KaterinaWire commented on Wire-iOS Tests/AppStateControllerTests.swift
> +        AppLock.lastUnlockedDate = Date(timeIntervalSinceNow: timeInterval)
Done.
Also I added tests for `AppLockTimer` class.

2020-10-19 13:42 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +    var appLockTimer: AppLockTimerProtocol?
I've made `appLockTimer` as non optional and set a default value in the definition otherwise it requires to initialize it in `super.init `.

(`var appLockTimer: AppLockTimerProtocol = AppLockTimer()`)

2020-10-19 13:44 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +    var appLockTimer: AppLockTimerProtocol?
Done

2020-10-19 15:09 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
> +    private var lockView: AppLockView?
Previously we created an instance of `AppLockPresenter` an instance of `AppLockView`. After refactoring the `AppLockPresenter`, we decided to hide or show the `lockView` in the `AppLockPresenter` initializer.
I rolled back `lockView` changes. Now it's again non-optional. But there are also changes in `AppLockViewController`:
```
1. lockView = AppLockView()
2. self.appLockPresenter = AppLockPresenter(userInterface: self)
```

2020-10-19 16:02 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +    internal var isDatabaseLocked = false
No, I am not modifying it. These were unnecessary changes.

2020-10-19 16:13 UTC, KaterinaWire commented on Wire-iOS/Sources/AppState.swift
>      case authenticated(completedRegistration: Bool, databaseIsLocked: Bool)
Removed

2020-10-21 10:04 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +    @objc func applicationDidEnterBackground() {
@johnxnguyen @typfel To roll back this logic I added an observer to `NotificationWindowRootViewController` for `UIApplication.willResignActiveNotification` event. In this moment I create `AppLockViewController` screen.
Also in `AppRootViewController` for `ApplicationDidBecomeActive` event I hide dimmed screen by `AppDelegate.shared.notificationsWindow?.isHidden = true`

2020-10-21 10:17 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
> -            return .databaseLock
@johnxnguyen @typfel It has been removed together with an `appState` property from the `AppLockInteractor`.
Since we do not currently have an `appState` property, I added the `isDatabaseLocked`  parameter in the `AppLockInteractor` initializer. This parameter will be passed from the `AppStateViewController` so that ʻAppLockInteractor` knows whether the database is locked or not.

2020-10-21 10:55 UTC, johnxnguyen requested changes
In my opinion, reusing the `AppLockViewController` to block the screen for task switching is introducing unnecessary complexity. A better approach would be to just display a simple view in the notification window. 

The notification window seems to have no other responsibility so you could repurpose it for the sole task of hiding the app when entering the background.

2020-10-21 10:55 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> -    case authenticated
I'm a bit confused what this represents and why it's no longer needed.

2020-10-21 10:55 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +    case noNeeded
What is the purpose of this new case? To force the app lock view controller to never display the reauthorization ui?

2020-10-21 11:09 UTC, johnxnguyen commented on Wire-iOS/Sources/AppRootViewController.swift
> +            viewController = AppLockViewController(isDatabaseLocked: appStateController.isDatabaseLocked)
I suggest to pass `isDatabaseLocked` as an associated value on the `locked` case so you avoid reaching back to the `appStateController`.

2020-10-21 12:50 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +    case noNeeded
Yes

2020-10-21 13:01 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> -    case authenticated
This state is unnecessary now. We used it previously in the `applicationDidEnterBackground` event. In this event we changed the `lastUnlockedDate` if user is authenticated. It has now been moved to `AppStateController`.

2020-10-21 13:17 UTC, KaterinaWire commented on Wire-iOS/Sources/AppRootViewController.swift
> +            viewController = AppLockViewController(isDatabaseLocked: appStateController.isDatabaseLocked)
Done

2020-10-21 14:36 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +    case noNeeded
According to your suggestion, I added a separate view to block the screen for task switching, and this state is no longer needed.

2020-10-21 14:37 UTC, KaterinaWire commented
> In my opinion, reusing the `AppLockViewController` to block the screen for task switching is introducing unnecessary complexity. A better approach would be to just display a simple view in the notification window.
> 
> The notification window seems to have no other responsibility so you could repurpose it for the sole task of hiding the app when entering the background.

Added a `DimmedViewController` for this purpose.

2020-10-23 09:35 UTC, johnxnguyen reviewed
Are there any tests for the `AppLockTimer`?

2020-10-23 09:35 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +    }
Setting the `lastUnlockedDate` should be the responsibility of the `AppLockTimer`. The problem with having `AppLock.lastUnlockedDate` publicly accessible and mutable is that it can be modified from anywhere and indeed it is from more than one place (here and in the `AppLockPresenter`. This can lead to programming errors that are difficult to catch before they are released.

I suggest to encapsulate all app lock date logic inside the `AppLockTimer`. This means to remove `AppLock.lastUnlockDate` and implementing the `AppLockTimer` in a way similar to:

```swift
class AppLockTimer {

  private var isLocked = true
  private var startDate = Date.distantPast

  var shouldLockApp: Bool {
    return isAppLockFeatureEnabled && isLocked
  }

  func appDidBecomeUnlocked() {
    isLocked = false
  }

  func appDidEnterForeground() {
    let elpasedTime = startDate.timeIntervalSinceNow
    isLocked = elpasedTime > 10 // <- some threshold
  }

  func appDidEnterBackground() {
    guard !isLocked else { return }
    startDate = Date()
  }

}
```

2020-10-23 09:35 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
> +    private var isDatabaseLocked: Bool = false
Is there a need to store this? If you simply need it to instantiated the `AppLockPresenter`, then you should create the presenter in `init`.

2020-10-23 09:35 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.swift
> +    private(set) var dimmedViewController: DimmedViewController = DimmedViewController()
Does the notification window do anything beside holding the `dimmedViewController`? If not, then I suggest to repurpose the notification window and it's root view controller to be the dimmed view controller / window. As a side note, I think a more intent-revealing name is `ScreenObfuscation`.

For instance:

```swift
final class ScreenObfuscationWindow: UIWindow {

  override init(frame: CGRect) {
    super.init(frame: frame)
    rootViewController = RootViewController(frame: frame)
  }

  func applicationWillResignActive() {
    isHidden = true
  }

  func applicationDidEnterForeground() {
    isHidden = !AppLock.isActive
  }

}

private extension ScreenObfuscationWindow {

  class RootViewController: UIViewController {

    override func loadView() {
      view = // some opaque view
    }

  }

}
```

This way you only need to hide the window and not care about adding / removing a separate view controller.

2020-10-23 09:44 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
> +    private var lockView: AppLockView?
The method that ends up hiding / showing the lock view is `requireAuthenticationIfNeeded()` and is called at the end of the initializer for the `AppLockPresenter`. You could remove this invocation from the initializer and call it from the `viewDidLoad` method:

```swift
override func viewDidLoad() {
  super.viewDidLoad()
  lockView = AppLockView()
  presenter.requireAuthenticationIfNeeded()
}
```

Or, you could also just initialize the lock view when declaring it: `private let lockView = AppLockView()`

2020-10-28 11:37 UTC, KaterinaWire commented
> AppLockTimer

Yes, there's a `AppLockTimerTests` class

2020-10-28 11:38 UTC, KaterinaWire commented
> Are there any tests for the `AppLockTimer`?

Yes, there's a `AppLockTimerTests` class

2020-10-28 15:35 UTC, KaterinaWire commented on Wire-iOS/Sources/AppRootViewController.swift
> +        AppDelegate.shared.notificationsWindow?.isHidden = true
Replaced

2020-10-28 15:35 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +    }
Modified

2020-10-28 15:36 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
> +    private var isDatabaseLocked: Bool = false
Yes. 
I moved into `init`

2020-10-28 23:23 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindowRootViewController.swift
> +    private(set) var dimmedViewController: DimmedViewController = DimmedViewController()
Changed the NotificationWindow

2020-10-29 07:53 UTC, johnxnguyen commented on Wire-iOS/Sources/Helpers/AppLock/AppLockTimerProtocol.swift
> +    func appDidEnterBackground()
I was thinking more that these methods were not part of the protocol but rather callbacks to notifications (defined only in `AppLockTimer`).

2020-10-29 07:53 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateController.swift
> +            appLockTimer.appDidEnterBackground()
If the `AppLockTimer` does its own observation "application did enter background", then this is unnecessary, including the check of the authentication state.

2020-10-29 07:53 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
> +final class ScreenObfuscationWindow: UIWindow {
Don't forget to rename the file.

2020-10-29 07:53 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
>          isOpaque = false
You may want to update these properties:

I would say that background color is irrelevant now, the accessibility identifier should change (check with QA though because they're probably using it), and the window is now opaque.

2020-10-29 07:53 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
> +import Cartography
We're trying to get rid of Cartography, but it looks like it's not used in this file anyway. I think you can safely remove this import.

2020-10-29 08:48 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
> +import Cartography
Yes, you are right, we don't need it now.

2020-10-29 08:48 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
> +final class ScreenObfuscationWindow: UIWindow {
Done

2020-10-29 08:49 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateController.swift
> +            appLockTimer.appDidEnterBackground()
Added an observer to the `AppLockTimer` and removed from the `AppStateController`.

2020-10-29 08:51 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
>          isOpaque = false
I will ask about `accessibilityIdentifier`.
The rest of the irrelevant  setting I removed.

2020-10-29 09:02 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/NotificationWindow.swift
>          isOpaque = false
Victor confirmed that they don't use this identifier for their tests.

2020-10-29 10:57 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/AppLock/AppLockTimerProtocol.swift
> +    func appDidEnterBackground()
As we discussed during the call, I can't use observers `appDidBecomeUnlocked` and `appDidEnterForeground` in `AppLockTimer` because there are the same observers in `AppStateController`.
Since `AppLockTimer` is a helper class that conform `AppLockTimerProtocol` and in `AppStateController` we use an instance by this protocol. That's why I need to have these methods as a part of the `AppLockTimerProtocol`

2020-10-29 13:17 UTC, johnxnguyen commented on Wire-iOS Tests/AppLock/AppLockTimerTests.swift
> +    func testThatShouldLockScreenReturnsTrueIfNeeded() {
```suggestion
    func testThatScreenShouldBeLockedIfAppLockIsActiveAndTimeoutIsReached() {
```

2020-10-29 13:17 UTC, johnxnguyen commented on Wire-iOS Tests/AppLock/AppLockTimerTests.swift
> +        timeoutReached ? nil : sut.appDidBecomeUnlocked()
It would be more readable to use an `if` statement.

2020-10-29 13:17 UTC, johnxnguyen commented on Wire-iOS Tests/AppStateControllerTests.swift
> +    var lastUnlockedDate = Date.distantPast
Is this last unlock date property necessary?

2020-10-29 13:17 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/ScreenObfuscationWindow.swift
> +        isHidden = !(AppLock.isActive || (ZMUserSession.shared()?.isDatabaseLocked ?? false))
This seems like duplicated code (see comment in the other PR about CallKit).

2020-10-29 13:17 UTC, johnxnguyen commented on Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
> +         //when
There seem to be quite a few tests here that referred to dimmed contents. You may want to update the test names to be more accurate.

2020-10-29 13:18 UTC, typfel requested changes

2020-10-29 13:18 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Overlay/ScreenObfuscationWindow.swift
> +        isHidden = !(AppLock.isActive || (ZMUserSession.shared()?.isDatabaseLocked ?? false))
We need check if EAR is enabled not if the database is locked since that's never the case when main UI is shown.

```suggestion
        isHidden = !(AppLock.isActive || (ZMUserSession.shared()?.encryptMessagesAtRest ?? false))
```

2020-10-29 15:05 UTC, typfel approved these changes

2020-10-29 15:22 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/ScreenObfuscationWindow.swift
> +        isHidden = !(AppLock.isActive || (ZMUserSession.shared()?.isDatabaseLocked ?? false))
Yes, I created
```
var isLockScreenEnabled: Bool {
         return AppLock.isActive || (ZMUserSession.shared()?.encryptMessagesAtRest ?? false)
     }
```
in the `SessionManager` extension in my another PR which is (currently) based on this PR because they are related.
But it makes sense to have it here.
What @typfel @johnxnguyen do you think about having `isLockScreenEnabled` in the `SessionManager` extension?
(I will remove it from another PR)

2020-10-29 15:23 UTC, KaterinaWire commented on Wire-iOS Tests/AppStateControllerTests.swift
> +    var lastUnlockedDate = Date.distantPast
Don't need it anymore

2020-10-29 15:24 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockTimerTests.swift
> +        timeoutReached ? nil : sut.appDidBecomeUnlocked()
Fixed

2020-10-29 15:32 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockViewController.swift
> +    private var lockView: AppLockView?
I initialized `lockView` when declaring it.

2020-10-29 15:42 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
> +         //when
Renamed

2020-10-30 07:25 UTC, johnxnguyen approved these changes
Looks good, still need to fix a failing test though.

2020-12-10 12:12 UTC, billypchan approved these changes

2020-12-10 12:13 UTC, billypchan commented
@KaterinaNikolaenko I read through the code and seems no issue, but you need to update this PR.

2021-02-17 09:42 UTC, closed without merging