[Refactor]: URLAction and SwitchAccount Router
wireapp/wire-ios pull request #4653
Opened 2020-10-14 07:37 UTC by marcomaddy1982

## What's new in this PR?

In order to decouple and make the `AppRootRouter` lighter I created two new different routers: the `URLActionRouter` and the `SwitchAccountRouter`. The first one implements the `URLActionDelegate` and it takes care of presenting on the `rootViewController` the necessary alert depending on the `URLActionDelegate` call back. The second one implements the `SessionManagerSwitchingDelegate` and it takes care to present on the `rootViewController` the alert for switching the user account.

2020-10-14 08:23 UTC, johnxnguyen commented on Wire-iOS/Sources/URLActionRouter.swift
> +    private func performSwitchBakend(with configurationURL: URL) {
Suggestion `switchBackend(with:)`

2020-10-14 08:24 UTC, johnxnguyen reviewed
Is this code covered by unit tests?

2020-10-14 08:45 UTC, marcomaddy1982 commented
> Is this code covered by unit tests?

No, also before were no covered.

2020-10-14 08:51 UTC, johnxnguyen commented
> > Is this code covered by unit tests?
> 
> No, also before were no covered.

I think we should add coverage not only for this change but for the rest of the refactoring because refactoring gives us the opportunity to make it testable. Is this something you're planning to do / have ideas about how to do it?

2020-10-14 08:57 UTC, marcomaddy1982 commented
> > > Is this code covered by unit tests?
> > 
> > 
> > No, also before were no covered.
> 
> I think we should add coverage not only for this change but for the rest of the refactoring because refactoring gives us the opportunity to make it testable. Is this something you're planning to do / have ideas about how to do it?

Yes, right.

2020-10-14 13:12 UTC, typfel requested changes

2020-10-14 13:12 UTC, typfel commented on Wire-iOS/Sources/URLActionRouter.swift
> +final class URLActionRouter {
This currently doesn't  follow the VIPER architecture. Shouldn't the `URLActionDelegate` be implemented in a `Interactor` and the alert in a `Presenter`

2020-10-15 06:23 UTC, marcomaddy1982 commented on Wire-iOS/Sources/URLActionRouter.swift
> +    private let rootViewController: RootViewController
I thinks that alert should be always presented from the `RootViewController`, do you have in mind some issues with it?

2020-10-15 06:25 UTC, marcomaddy1982 commented on Wire-iOS/Sources/URLActionRouter.swift
> -            guard SecurityFlags.customBackend.isEnabled else {
we can move it back or rename `presentCustomBackendAlert` in `presentCustomBackendAlertIfNecesssary`.

2020-10-15 06:28 UTC, marcomaddy1982 commented on Wire-iOS/Sources/URLActionRouter.swift
> +final class URLActionRouter {
The idea of this class was decouple a bit the `AppRootRouter`, we could also add the `Interactor` and the `Presenter` but IMHO in this case the code would be just more verbose.

2020-10-15 06:28 UTC, marcomaddy1982 commented on Wire-iOS/Sources/URLActionRouter.swift
> -            self.isLoadingViewVisible = true
Nice catch, Thanks

2020-10-15 06:50 UTC, marcomaddy1982 commented on Wire-iOS/Sources/URLActionRouter.swift
> +    private let rootViewController: RootViewController
moved back to the old position

2020-10-15 06:51 UTC, marcomaddy1982 commented on Wire-iOS/Sources/URLActionRouter.swift
> -            guard SecurityFlags.customBackend.isEnabled else {
moved back to the old position

2020-10-15 06:51 UTC, marcomaddy1982 commented on Wire-iOS/Sources/URLActionRouter.swift
> -            self.isLoadingViewVisible = true
Done.

2020-10-16 12:48 UTC, typfel commented on Wire-iOS/Sources/URLActionRouter.swift
> +final class URLActionRouter {
Ok, we can review it that later. This refactoring is already big enough :)

2020-10-16 12:51 UTC, typfel approved these changes

2020-10-19 07:50 UTC, merged