[Feature]: AppCenterOperation
wireapp/wire-ios pull request #4656
Opened 2020-10-15 14:27 UTC by marcomaddy1982

## What's new in this PR?

Same topic of this PR https://github.com/wireapp/wire-ios/pull/4655 but applied to the AppCenter launch configuration. 

### NOTA BENE ###
- Let's review in detail ti.

2020-10-15 14:38 UTC, billypchan approved these changes

2020-10-16 12:36 UTC, typfel requested changes

2020-10-16 12:36 UTC, typfel commented on Wire-iOS/Sources/LaunchSequenceOperation.swift
> +extension AppCenterOperation: MSDistributeDelegate {
It's bit counter intuitive that the `AppCenterOperation` implements in the `MSDistributeDelegate`. If something is called `operation ` I expect it to perform an operation and then be done.

Maybe the delegates could implemented somewhere else and then be injected into the `AppCenterOperation`?

2020-10-19 08:07 UTC, marcomaddy1982 commented on Wire-iOS/Sources/LaunchSequenceOperation.swift
> +extension AppCenterOperation: MSDistributeDelegate {
I would find a bit verbose something like that honestly. :-D

2020-10-19 08:16 UTC, merged