analytics: remove user_id and set analytics id as device id
wireapp/wire-ios pull request #4665
Opened 2020-10-26 19:29 UTC by billypchan

## What's new in this PR?

For the requirement update. Set the analytics id as device id.
Since self user's analytics id is not defined til the session is created, the Countly start session is trigged after `AnalyticsCountlyProvider.selfUser` is assigned

2020-10-27 11:06 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        beginSession() //else { return nil }
Is this necessary?

2020-10-27 11:17 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        beginSession() //else { return nil }
cleared

2020-10-29 12:46 UTC, typfel requested changes

2020-10-29 12:46 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        beginSession()
This will never do anything since `selfUser` can't be set at this point.

2020-10-29 12:46 UTC, typfel commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        //TODO: begin session only if self user is set
What's with the `TODO.  This logic is already implemented, no?

2020-10-29 12:54 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        beginSession()
I will remove this.

2020-10-29 12:56 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        //TODO: begin session only if self user is set
the comment is updated.

2020-10-29 13:00 UTC, typfel approved these changes

2020-10-29 13:19 UTC, merged