tag app.open when app became active
wireapp/wire-ios pull request #4668
Opened 2020-10-27 13:48 UTC by billypchan

## What's new in this PR?

For every time the app became active, tag `app.open` event.
If selfuser is not set, i.e. before the user session is created, store the event and send it after selfuser is set.

2020-10-27 15:38 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        }
I suggest to use a guard statement to make the intent a bit clearer:

```swift
guard selfUser != nil else {
  storedEvents.append(...)
  return
}
```

2020-10-27 15:38 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    private var storedEvents: [StoredEvent]?
Is there a particular reason to make this optional?

2020-10-27 15:50 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +        }
fixed.

2020-10-27 19:22 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    private var storedEvents: [StoredEvent]?
removed the optional and simplied the code, thx!

2020-10-28 07:09 UTC, johnxnguyen requested changes
It would be great to have a test for this new behavior.

2020-10-28 12:06 UTC, billypchan commented on Wire-iOS Tests/Analytics/AnalyticsCountlyProviderTests.swift
> +    }
@johnxnguyen test added for stored events

2020-10-28 13:01 UTC, johnxnguyen commented on Wire-iOS Tests/Analytics/AnalyticsCountlyProviderTests.swift
> +    }
If you abstract out `Countly.sharedInstance()` from `AnalyticsCountlyProvider`, you would be able to test that events "recorded" only once the self user is set. Also, that would open up the possibility of more focused testing.

For instance, suppose you had a protocol:

```swift
protocol CountlyInstance {
  func recordEvent(_ key: String, segmentation: [String : String]?)
}
```

Which can be conformed to by `Countly`, then you could inject a test instance and verify invocations to this method rather than exposing the concept of stored events and counting them.

2020-10-28 14:46 UTC, billypchan commented on Wire-iOS Tests/Analytics/AnalyticsCountlyProviderTests.swift
> +    }
adding `MockCountly` class for tests

2020-10-29 14:12 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    init?(countlyInstanceType: CountlyInstance.Type = Countly.self) {
I think it makes more sense to pass in the instance itself, not the type.

2020-10-29 14:12 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
>          Countly.sharedInstance().start(with: config)
Ideally we remove all concrete instances of `Countly`, and just have the protocol type.

2020-10-29 14:39 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    init?(countlyInstanceType: CountlyInstance.Type = Countly.self) {
passing the type is better since there are some other places calling another static methods, e.g. `Countly.user().set()`

2020-10-29 14:41 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    init?(countlyInstanceType: CountlyInstance.Type = Countly.self) {
can we abstract those too?

2020-10-29 14:46 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    init?(countlyInstanceType: CountlyInstance.Type = Countly.self) {
I will create another PR to test the switching account requirement. It would be better to write tests when abstracting the methods.

2020-10-29 14:47 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
>          Countly.sharedInstance().start(with: config)
I will open another PR for testing switching account and non-team member behavior

2020-10-29 16:54 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCountlyProvider.swift
> +    init?(countlyInstanceType: CountlyInstance.Type = Countly.self) {
Added test and mocked `start()` method. I will add more mocks if necessary.
https://github.com/wireapp/wire-ios/pull/4680

2020-10-30 07:19 UTC, johnxnguyen approved these changes

2020-10-30 08:32 UTC, merged