remove legacy tag events
wireapp/wire-ios pull request #4669
Opened 2020-10-27 14:09 UTC by billypchan

## What's new in this PR?

Remove the tag events no longer needs.

2020-10-27 15:19 UTC, typfel commented on Wire-iOS Share Extension/ShareExtensionAnalytics.swift
>  final class ExtensionActivity {
Do we not track anything from the share extension anymore? Can we remove this whole class?

2020-10-27 15:48 UTC, billypchan commented on Wire-iOS Share Extension/ShareExtensionAnalytics.swift
>  final class ExtensionActivity {
checked that this class also stores the attachments info for `appendFileTextToEditor` method and it should stay.

2020-10-28 10:29 UTC, typfel requested changes

2020-10-28 10:29 UTC, typfel commented on Wire-iOS Share Extension/ShareExtensionAnalytics.swift
>  final class ExtensionActivity {
Seems like this class had multiple responsibilities. We remove all tracking related properties and give the file better name which reflects its responsibility.

The stored attachments are used to calculate `numberOfImages`, `hasVideo`, `hasFile` which are private no longer in use so they can be deleted.

2020-10-28 10:29 UTC, typfel commented on Wire-iOS Share Extension/ShareExtensionAnalytics.swift
>      func markConversationDidDegrade() {
Can be deleted if `conversationDidDegrade` is deleted.

2020-10-28 10:29 UTC, typfel commented on Wire-iOS Share Extension/ShareExtensionAnalytics.swift
>      private var conversationDidDegrade = false
Private and no longer in use so they can be deleted.

2020-10-28 10:29 UTC, typfel commented on Wire-iOS Share Extension/ShareExtensionViewController.swift
>          extensionActivity?.hasText = !contentText.isEmpty
Can be deleted, `hasText` was only read by `sentEvent(completion: @escaping (StorableTrackingEvent)`. So I guess this whole function can be deleted.

2020-10-28 10:29 UTC, typfel commented on Wire-iOS Share Extension/ShareExtensionViewController.swift
> -        sharingSession?.analyticsEventPersistence.add(activity.openedEvent())
What about the `analyticsEventPersistence` should we remove this property? Will we add new events to the share extension later?

2020-10-28 13:18 UTC, billypchan commented on Wire-iOS Share Extension/ShareExtensionViewController.swift
> -        sharingSession?.analyticsEventPersistence.add(activity.openedEvent())
no plannings for tagging share extension events for now.

2020-10-28 13:42 UTC, billypchan commented
@typfel I replaced `ExtensionActivity` with a member property `attachments: [AttachmentType: [NSItemProvider]]`

2020-10-28 13:51 UTC, typfel commented on Wire-iOS Share Extension/ShareExtensionAnalytics.swift
> +//final class ExtensionActivity {
Commented out code

2020-10-28 13:59 UTC, billypchan commented on Wire-iOS Share Extension/ShareExtensionAnalytics.swift
> +//final class ExtensionActivity {
removed.

2020-10-28 14:00 UTC, typfel approved these changes

2020-10-28 14:15 UTC, merged