[Refactoring]:[WIP]: AppStateCalculator Tests
wireapp/wire-ios pull request #4671
Opened 2020-10-27 15:29 UTC by marcomaddy1982

## What's new in this PR?

This PR is still in WIP, I will write more detail once it will be completed.

2020-10-28 09:34 UTC, johnxnguyen reviewed
If `appState` didn't have a private setter, you could simplify your unit tests a great deal by being able to set the app state directly and not rely on other logic.

2020-10-28 09:34 UTC, johnxnguyen commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +        sut.delegate = appRootRouter
The app root router isn't really relevant so I'd suggest to rename it to

```swift
private extension AppStateCalculatorTests {
  
  class MockDelegate: AppStateCalculatorDelegate {

    var wasNotified: Bool
    
    ...
  }
  
}

```

2020-10-28 09:34 UTC, johnxnguyen commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +    }
This looks like two tests in one. Is the first given-when-then all setup code?

2020-10-28 09:34 UTC, johnxnguyen commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +        appRootRouter.isAppStateCalculatorCalled = false
This is all setup code and should be under a single "given".

2020-10-28 09:34 UTC, johnxnguyen commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +        appRootRouter.isAppStateCalculatorCalled = false
Again, this is all setup code. It should be under a single "given". 

Also, I don't really understand the test name, could you elaborate?

2020-10-28 09:34 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                                isDatabaseLocked: isDatabaseLocked)
You should also add a test code to cover this path too.

2020-10-28 09:58 UTC, marcomaddy1982 commented
> If `appState` didn't have a private setter, you could simplify your unit tests a great deal by being able to set the app state directly and not rely on other logic.

I thought about that, but I preferred to don't expose the `appState` for this reason: As you know the scope of the `AppStateCalculator` is calculate the `AppState` itself without being injected from any other part of the code. So to maintain the `appState` incapsulated I preferred to have it `private`. I know that In the test exposing the `appState`  it would be much easier to set the `appState` directly, but if I will expose it the idea of having a unique calculator will be lost.

2020-10-28 10:01 UTC, marcomaddy1982 commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +        appRootRouter.isAppStateCalculatorCalled = false
Actually no, cause when I do this `sut.sessionManagerDidBlacklistCurrentVersion()` then `isAppStateCalculatorCalled = true` so if I wanna check if another transition is done I must reset the `isAppStateCalculatorCalled` to `false`.

2020-10-28 10:02 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                                isDatabaseLocked: isDatabaseLocked)
Ohhhh probably I forgot it, thanks for pointing it out.

2020-10-28 10:04 UTC, marcomaddy1982 commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +    }
This basically tests that when we migrate to a new account we have a transition form `loading` to the `migrating`.

2020-10-28 10:16 UTC, johnxnguyen commented
> I know that In the test exposing the appState it would be much easier to set the appState directly, but if I will expose it the idea of having a unique calculator will be lost.

@marcomaddy1982 what about having a setter for tests only (marked in a way that makes it clear that it should only be used for testing purposes)? I agree with you that it's more important to have stricter access control but if it's absolutely clear to the developer to not abuse the test helper then I don't see any problem with it. What do you think?

2020-10-28 10:32 UTC, marcomaddy1982 commented
> > I know that In the test exposing the appState it would be much easier to set the appState directly, but if I will expose it the idea of having a unique calculator will be lost.
> 
> @marcomaddy1982 what about having a setter for tests only (marked in a way that makes it clear that it should only be used for testing purposes)? I agree with you that it's more important to have stricter access control but if it's absolutely clear to the developer to not abuse the test helper then I don't see any problem with it. What do you think?

But wait, I don't know if I am missing something: if I set every time the appState how we test AppStateCalculator if call or not the delegates? I mean this is the flow:

1) call a delegate (`SessionManagerDelegate` and `AuthenticationCoordinatorDelegate`) methods in a way that we set the new appState 
2) and then check if the `AppStateCalculatorDelegate` method is called, which means that we transit to the new state. 

if we set every time the `appState` how we test the part 2)?

2020-10-28 10:37 UTC, marcomaddy1982 commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +        appRootRouter.isAppStateCalculatorCalled = false
The name is wrong, there is a "Dont" in the naming that should not be there. I wanna tot the contrary actually: is there is a new `appState` the app transit to the new one.

2020-10-28 10:47 UTC, johnxnguyen commented
> But wait, I don't know if I am missing something: if I set every time the appState, how we test AppStateCalculator if call or not the delegates?

@marcomaddy1982 what about something like this:

```swift
// Given
sut.testHelper_setAppState(.blacklisted)
mockDelegate.isNotifiedOfChange = false 

// When
sut.sessionManagedDidBlacklist()

// Then
XCTAssertEqual(sut.appState, .blacklisted)
XCTAssertFalse(mockDelegate.isNotifiedOfChange)
```

The thing we are testing is that given we're in a particular app state, when something happens that doesn't change the app state, then the app state hasn't changed and the delegate wasn't notified of a change.

2020-10-28 10:48 UTC, marcomaddy1982 commented
> > > I know that In the test exposing the appState it would be much easier to set the appState directly, but if I will expose it the idea of having a unique calculator will be lost.
> > 
> > 
> > @marcomaddy1982 what about having a setter for tests only (marked in a way that makes it clear that it should only be used for testing purposes)? I agree with you that it's more important to have stricter access control but if it's absolutely clear to the developer to not abuse the test helper then I don't see any problem with it. What do you think?
> 
> But wait, I don't know if I am missing something: if I set every time the appState, how we test AppStateCalculator if call or not the delegates? I mean, this is the flow of the current tests :
> 
> 1. call a delegate (`SessionManagerDelegate` and `AuthenticationCoordinatorDelegate`) methods in a way that we set the new appState
> 2. and then check if the `AppStateCalculatorDelegate` method is called, which means that the application has transition to the new appState.
> 
> if we set every time the `appState` how we test the part 2)?



> > > I know that In the test exposing the appState it would be much easier to set the appState directly, but if I will expose it the idea of having a unique calculator will be lost.
> > 
> > 
> > @marcomaddy1982 what about having a setter for tests only (marked in a way that makes it clear that it should only be used for testing purposes)? I agree with you that it's more important to have stricter access control but if it's absolutely clear to the developer to not abuse the test helper then I don't see any problem with it. What do you think?
> 
> But wait, I don't know if I am missing something: if I set every time the appState, how we test AppStateCalculator if call or not the delegates? I mean, this is the flow of the current tests :
> 
> 1. call a delegate (`SessionManagerDelegate` and `AuthenticationCoordinatorDelegate`) methods in a way that we set the new appState
> 2. and then check if the `AppStateCalculatorDelegate` method is called, which means that the application has transition to the new appState.
> 
> if we set every time the `appState` how we test the part 2)?

Now I understood what you mean. It is a good idea but there is something in me that think that we will use it also for other purpose than tests. :-).

2020-10-28 10:51 UTC, marcomaddy1982 commented
> > But wait, I don't know if I am missing something: if I set every time the appState, how we test AppStateCalculator if call or not the delegates?
> 
> @marcomaddy1982 what about something like this:
> 
> ```swift
> // Given
> sut.testHelper_setAppState(.blacklisted)
> mockDelegate.isNotifiedOfChange = false 
> 
> // When
> sut.sessionManagedDidBlacklist()
> 
> // Then
> XCTAssertEqual(sut.appState, .blacklisted)
> XCTAssertFalse(mockDelegate.isNotifiedOfChange)
> ```
> 
> The thing we are testing is that given we're in a particular app state, when something happens that doesn't change the app state, then the app state hasn't changed and the delegate wasn't notified of a change.

Ahhhh ok, in this manner it makes sense. ok. deal.

2020-10-28 11:13 UTC, johnxnguyen commented
> Now I understand what you mean. It is a good idea but there is something in me that think that we will use it also for other purpose than tests. :-). But yes, in the way you commented the tests will be much less verbose.

@marcomaddy1982 sure but if someone intentionally abuses a test helper (key word here is "intentionally", it must be obvious that it is only for testing), then there's nothing to stop them from changing the access of the property itself. But this is also why we have code reviews, to prevent such things from happening 😄 

I'm just trying to convince you, but I'm open to other solutions as well. Simplifying the tests is not just to make them smaller, but rather to make them more focused on what is actually being tested.

2020-10-28 11:21 UTC, marcomaddy1982 commented
> > Now I understand what you mean. It is a good idea but there is something in me that think that we will use it also for other purpose than tests. :-). But yes, in the way you commented the tests will be much less verbose.
> 
> @marcomaddy1982 sure but if someone intentionally abuses a test helper (key word here is "intentionally", it must be obvious that it is only for testing), then there's nothing to stop them from changing the access of the property itself. But this is also why we have code reviews, to prevent such things from happening 😄
> 
> I'm just trying to convince you, but I'm open to other solutions as well. Simplifying the tests is not just to make them smaller, but rather to make them more focused on what is actually being tested.

Actually I liked the idea, I'm going to push it. I created an extension at the bottom of the class, hopefully it would not be so visible :-D.

2020-10-28 11:31 UTC, typfel requested changes

2020-10-28 11:31 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                      error : Error) {
Adding `selectedAccount` seems like kind of workaround in order to keep the current logic and this logic is pretty much unreadable atm so I think we should try to fix the semantics of this method inside SE instead.

IMO much of this logic comes from the fact that `sessionManagerDidFailToLogin()` is called in many different scenario, many are actually irrelevant to the `AppStateCalculator` because they are trigged during the login flow.  Here we are only interested in the case when we transition from being `authenticated` to `unauthenticated`.

Let's have a call and discuss this?

2020-10-28 15:40 UTC, typfel requested changes
I would like to see some more descriptive test names. We often try to follow this format:

testThat**WhatWillHappen**_**GivenSomeCondition**

and if there's multiple variants of a test:

testThat**WhatWillHappen**_**GivenSomeCondition**_**AdditionalCondition1**
testThat**WhatWillHappen**_**GivenSomeCondition**_**AdditionalCondition2**

the goal is that it should be possible to understand what a test is checking without having to read function body.

2020-10-28 15:40 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +        delegate = MockAppStateCalculatorDelegate()
You should nil this out in `tearDown` otherwise they will live for the duration of the whole test suite.

2020-10-28 15:40 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +    func testThatSessionManagerDidBlacklistCurrentVersion() {
```suggestion
    func testThatAppStateChanges_OnSessionManagerDidBlacklistCurrentVersion() {
```

2020-10-28 15:40 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +    func testThatSessionManagerWillMigrateAccount() {
```suggestion
    func testThatAppStateChanges_OnSessionManagerWillMigrateAccount() {
```

2020-10-28 15:40 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +    func testThatSessionManagerWillNotMigrateAccount() {
```suggestion
    func testThatAppStateIsNotChanged_OnSessionManagerWillMigrateAccount_ForNonActiveAccount() {
```

2020-10-28 15:40 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +    func testThatWillLogout() {
```suggestion
    func testThatAppStateChanges_OnSessionManagerWillLogout() {
```

2020-10-28 15:41 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
> +                                      error : Error) {
We decided to tackle this change for another PR.

2020-10-29 12:07 UTC, typfel requested changes

2020-10-29 12:07 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +    // MARK: - Tests AppState Changes
I think these tests are wrong and the `AppStateCalculator` has the wrong logic implemented.

The behaviour we want is that we don't change the `AppState` until the app as become active at least once.

I would expect tests like this:

testThatAppStateDoesntChange_OnDidReportDatabaseLockChange_BeforeAppBecomeActive
testThatAppStateChanges_OnDidReportDatabaseLockChange_AfterAppHasBecomeActive

2020-10-29 13:38 UTC, typfel requested changes

2020-10-29 13:38 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
>          }
Isn't easier to read if these are to different guards:

```
guard (self.appState != appState else {
             completion?()
             return
}
guard hasEnteredForeground  else {
             pendingAppState = appState
             completion?()
             return
}

```

2020-10-29 13:38 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
>                              force: Bool = false,
The `force` argument is is never used so I guess it can be removed.

2020-10-29 13:38 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
>          sut.applicationDidEnterBackground()
this is the setup so it belongs to `GIVEN`

2020-10-29 13:38 UTC, typfel commented on Wire-iOS Tests/AppStateCalculatorTests.swift
> +        sut.sessionManagerDidReportDatabaseLockChange(isLocked: isDatabaseLocked)
this is the setup so it belongs to `GIVEN`

2020-10-29 13:50 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
>          }
in this manner almost all the tests are failing

2020-10-29 13:57 UTC, typfel commented on Wire-iOS/Sources/AppStateCalculator.swift
>          }
Huh, aren't they logically equivalent? Why are the tests failing?

2020-10-29 14:12 UTC, typfel approved these changes

2020-10-30 07:06 UTC, merged