[Refactor]: SwitchingAccountRouter Tests
wireapp/wire-ios pull request #4673
Opened 2020-10-28 14:56 UTC by marcomaddy1982

## What's new in this PR?

SwitchingAccountRouter coverage tests written using the changes made in the [PR](https://github.com/wireapp/wire-ios-sync-engine/pull/1332)

### Dependencies

sync-engine: https://github.com/wireapp/wire-ios-sync-engine/pull/1332

2020-10-28 17:52 UTC, David-Henner commented on Wire-iOS Tests/SwitchingAccountRouterTests.swift
> +        sut.confirmSwitchingAccount { isConfirmed in }
```suggestion
        sut.confirmSwitchingAccount { _ in }
```

2020-10-29 07:37 UTC, typfel requested changes

2020-10-29 07:37 UTC, typfel commented on Wire-iOS Tests/SwitchingAccountRouterTests.swift
> +    func testThatSwitchAccountAlertIfPresented() {
```suggestion
    func testThatAlertIsPresented_WhenConfirmSwitchingAccountIsInvoked() {
```

2020-10-29 07:37 UTC, typfel commented on Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorController.swift
> +        guard
These changes doesn't related to the main refactoring

2020-10-29 07:37 UTC, typfel commented on Wire-iOS/Sources/SwitchingAccountRouter.swift
> +    @objc
@objc is unnecessary?

2020-10-29 07:37 UTC, typfel commented on Wire-iOS/Sources/SwitchingAccountRouter.swift
> -extension SwitchingAccountRouter: SessionManagerSwitchingDelegate {
A nice thing about this is that Xcode will suggest that to add any missing delegate methods directly into this extension.

2020-10-29 07:49 UTC, marcomaddy1982 commented on Wire-iOS/Sources/SwitchingAccountRouter.swift
> +    @objc
yes it is unfortunately.

2020-10-29 07:54 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/SelfProfile/AccountSelectorController.swift
> +        guard
they are somehow, cause I moved the checks about the ongoing call in the sync engine so they are not necessary anymore there there and moreover I wanted to remove the super ugly exposed method of the `AppRootRouter`

```swift
AppDelegate.shared.appRootRouter?.confirmSwitchingAccount 
```

P.s. tested many time and seems to work fine.

2020-10-29 08:03 UTC, johnxnguyen commented on Wire-iOS Tests/SwitchingAccountRouterTests.swift
> +    var sut: MockSwitchingAccountRouter!
The combination of terminologies "system under test" and "mock" is an oxymoron, I suggest to rename `MockSwitchingAccountRouter` to something like `TestableSwitichingAccountRouter`. We want to express that it is indeed a `SwitchingAccountRouter` and not some fake version of it.

2020-10-29 08:37 UTC, marcomaddy1982 commented on Wire-iOS Tests/SwitchingAccountRouterTests.swift
> +    var sut: MockSwitchingAccountRouter!
Done

2020-10-29 15:52 UTC, typfel approved these changes

2020-10-29 16:10 UTC, merged