fix: appcenter is not started
wireapp/wire-ios pull request #4695
Opened 2020-11-06 13:54 UTC by billypchan

## What's new in this PR?

### Issues

App center is not started.

### Causes

After https://github.com/wireapp/wire-ios/pull/4651, we fixed the appcenter is always started case but it stops app center starting on normal case.

### Solutions

Fix the check for `UserDefaults` KVP. When "UseAppCenter" key is not exist, default value is true and app center can start.

2020-11-09 12:46 UTC, typfel requested changes

2020-11-09 12:46 UTC, typfel commented on WireCommonComponents/AutomationHelper.swift
> +        return useAppCenterLaunchOption && useAppCenter
To me this logic would only make sense if `useAppCenterLaunchOption` is optional and only set if `--user-app-center` is present.

Then we could write something like this:

```
if let useAppCenterLaunchOption {
    return useAppCenterLaunchOption
} else {
    return UserDefaults.standard.bool(forKey: "UseAppCenter") ?? true
}
```

2020-11-09 16:02 UTC, billypchan commented on WireCommonComponents/AutomationHelper.swift
> +        return useAppCenterLaunchOption && useAppCenter
The use case of `useAppCenterLaunchOption` is set it to false to disable app center.

If the code is refactored as suggestion, it would have difference result:

when `useAppCenterLaunchOption` is false, it will check `UserDefaults.standard.bool(forKey: "UseAppCenter")`

The original code would let `useAppCenterLaunchOption` has higher priority, when `useAppCenterLaunchOption` is false, app center would not start no matter `UserDefaults.standard.bool(forKey: "UseAppCenter")`'s value is true or false.

2020-11-10 07:18 UTC, johnxnguyen commented on WireCommonComponents/AutomationHelper.swift
> +        return useAppCenterLaunchOption && useAppCenter
How would it have a different result? Jacob's suggestion is much more readable.

2020-11-10 07:48 UTC, marcomaddy1982 commented
@billypchan I would suggest to merge dev on this branch in order to have all the changes regarding the App Launch Refactoring and have a look to the `AppCenterOperation` class.  I know your change is made in the `AutomationHelper.swift` but IMHO for testing it is better being alined with develop.

2020-11-10 07:49 UTC, marcomaddy1982 commented
> @billypchan I would suggest to merge dev on this branch in order to have all the changes regarding the App Launch Refactoring and have a look to the `AppCenterOperation` class. I know your change is made in the `AutomationHelper.swift` but IMHO for testing it is better being alined with develop.

2020-11-10 15:10 UTC, billypchan commented on WireCommonComponents/AutomationHelper.swift
> +        return useAppCenterLaunchOption && useAppCenter
refactor the code for readibility

2020-11-10 15:11 UTC, billypchan commented
@marcomaddy1982 retested after merging

2020-11-11 12:47 UTC, marcomaddy1982 approved these changes

2020-11-11 13:34 UTC, typfel commented on WireCommonComponents/AutomationHelper.swift
> +        return useAppCenterLaunchOption && useAppCenter
> If the code is refactored as suggestion, it would have difference result:

You're correct, I had a typo in my example (I updated it).

If `useAppCenterLaunchOption` is optional and we do:

```
if let useAppCenterLaunchOption = self.useAppCenterLaunchOption {
    return useAppCenterLaunchOption
} else {
    return UserDefaults.standard.bool(forKey: "UseAppCenter") ?? true
}
```

the `--user-app-center` will have priority if present and otherwise we rely on the value from user defaults.

2020-11-11 13:36 UTC, typfel requested changes
See my new comment.

2020-11-11 14:02 UTC, typfel approved these changes

2020-11-11 15:41 UTC, merged