[Refactoring]: Introduca CallRouter
wireapp/wire-ios pull request #4696
Opened 2020-11-06 15:38 UTC by marcomaddy1982

## What's new in this PR?

This PR will cover what mentioned here in the [RFC](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/124125940/Call+Routing+Refactoring).

Main `CallRouter` actions:
- Present/Dismiss/Minimize `ActiveCallController`
- Show and hidde `CallTopOverlayController`
- Present/Dismiss `CallQualityViewController`
- Present `Call Alerts`

P.s: cause this PR is already huge I will add the tests in a separate PR.

2020-11-09 16:17 UTC, David-Henner reviewed
Thanks for all the heavy work! 👍

2020-11-09 16:17 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Overlay/ActiveCallViewController.swift
> +    func callControllerDidDisappear(_ callController: CallViewController)
isn't it redundant to define two different protocols with the same exact method?

2020-11-09 16:17 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +    func dismissActiveCall(animated: Bool, completion: (()-> Void)?)
Do we have a type alias for `()-> Void` we could use ?

2020-11-09 16:17 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
> +            delegate?.callControllerDidDisappear(self)
I don't understand.
`CallViewControllerDelegate` seems to report the disappearance of `self`
`ViewControllerDismisser` seems to ask for dismissal of `self`

how can one replace the other?

2020-11-09 16:20 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Overlay/ActiveCallViewController.swift
> +    func callControllerDidDisappear(_ callController: CallViewController)
the first one was defined in `CallViewController.swift`

2020-11-09 16:38 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
> +        topOverlayCall = priorityCallConversation
that's a good point!! Thanks. Yes, probably it is not the scope of this PR but I guess we could try to improve it now that we working with this part of the code. Thanks for pointing it out

2020-11-09 16:44 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +        rootViewController.dismiss(animated: animated, completion: { [weak self] in
When I developed this part at the beginning it was done as your comment, then I opted for this approach (that works btw) cause I didn't want to have an instance to the ActiveCallController around in a way that the CallRouter was not too huge. Anyway not that you commented I'm rethinking again. So if I understood you would prefer the first approach, maybe using a lazy property?

```swift
struct Animal {
    private lazy var activeCallViewController: ActiveCallViewControllerDelegate
}
```

2020-11-09 16:45 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +        DebugAlert.showSendLogsMessage(message: "Sending the debug logs can help us improve the quality of calls and the overall app experience.")
I could be that I miss it. Also if not it would not hurt adding `executeOrSchedulePostCallAction`. Thanks for pointing it out!!!

2020-11-09 16:47 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +}
I could create a `CallQualityTransitioningDelegate` class that implements `UIViewControllerTransitioningDelegate`, what do you think about?

2020-11-09 16:47 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
> +    func callControllerDidDisappear(_ callController: CallViewController)
nice catch!!! Thanks

2020-11-09 16:48 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +    func dismissActiveCall(animated: Bool, completion: (()-> Void)?)
I can have a look, if yes I will use it.

2020-11-09 17:02 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
> +            delegate?.callControllerDidDisappear(self)
You are right `ViewControllerDismisser` ask for dismissal of `self` but in the old implementation the dismisser was not doing any action of dismissing (moreover the `CallController` is not a `ViewController`). There were just reset some properties (see old implementation). The dismiss was basically called at the end of the swipe down of the active call.

```swift
func dismiss(viewController: UIViewController, completion: Completion? = nil) {
        guard let callViewController = viewController as? CallViewController,
            let conversation = callViewController.conversation else { return }

        minimizedCall = conversation
        activeCallViewController = nil
}
```

My idea is to have a delegate the once the active call is out of the screen reset the property and dismiss the controller.

```swift
func callControllerDidDisappear(_ callController: CallViewController) {
        router?.dismissActiveCall(animated: true, completion: nil)
        minimizedCall = callController.conversation
    }
```

But if you thing that this is confusing or the naming is confusing we can try to improve this part.

2020-11-10 07:56 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
> +    // MARK: - Public Impletation
Typo "Implementation"

2020-11-10 07:56 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallController.swift
> +    private func shouldAnimate(call: ZMConversation) -> Bool {
Suggestion: `shouldAnimateTransitionForCall(in conversation: ZMConversation) -> Bool`

2020-11-10 07:56 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +protocol CallRouterProtocol: class {
Suggestion `ActiveCallRouterProtocol`

2020-11-10 07:56 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +class CallRouter: NSObject {
Suggestion: `ActiveCallRouter`

2020-11-10 07:56 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +    }
I think a more intent-revealing name is needed here.

2020-11-10 07:59 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +protocol CallRouterProtocol: class {
Yes I know, thanks for remembering. We discussed it in the RFC. My idea was apply this change in the next push :-)

2020-11-10 08:11 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +    }
`updateActiveCallPresentetionState` maybe?

2020-11-10 08:57 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +    }
Yup, I like that (without the typo of course 😄 )

2020-11-10 08:59 UTC, johnxnguyen requested changes

2020-11-10 08:59 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
> +    }
You should rename `updateCallState` to `updateActiveCallPresentationState` too.

2020-11-10 09:11 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +    }
right!!! :-D

2020-11-10 10:48 UTC, johnxnguyen approved these changes

2020-11-10 10:51 UTC, marcomaddy1982 commented
@David-Henner @johnxnguyen: I have addressed all your comments. It would be nice if you will spend 5 minutes when you have time to try out if no bugs are introduced in the routing.  It is a pretty important part of the app and I could have missed something. Thanks :-)

2020-11-10 10:53 UTC, johnxnguyen commented
> It would be nice if you will spend 5 minutes when you have time to try out if no bugs are introduced in the routing.

@marcomaddy1982 sure, but it might need to wait until tomorrow unfortunately.

2020-11-10 11:03 UTC, marcomaddy1982 commented
> > It would be nice if you will spend 5 minutes when you have time to try out if no bugs are introduced in the routing.
> 
> @marcomaddy1982 sure, but it might need to wait until tomorrow unfortunately.

@johnxnguyen it is not a problem. Thanks 👍

2020-11-10 14:33 UTC, David-Henner commented
> @David-Henner @johnxnguyen: I have addressed all your comments. It would be nice if you will spend 5 minutes when you have time to try out if no bugs are introduced in the routing. It is a pretty important part of the app and I could have missed something. Thanks :-)

I'll try to review again today, but if not, I'll make sure it's done tomorrow

2020-11-10 15:08 UTC, marcomaddy1982 commented
> > @David-Henner @johnxnguyen: I have addressed all your comments. It would be nice if you will spend 5 minutes when you have time to try out if no bugs are introduced in the routing. It is a pretty important part of the app and I could have missed something. Thanks :-)
> 
> I'll try to review again today, but if not, I'll make sure it's done tomorrow

No rush. We just started the new sprint and this ticket is part of that Sprint.

2020-11-11 09:20 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +        rootViewController.dismiss(animated: animated, completion: { [weak self] in
I thought at first that it was a mistake. Maybe the naming is a bit confusing, because I'm not sure if `rootViewController` is the root VC of the app or only the starting point for calling related UI.

2020-11-11 09:23 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +}
Yeah I think it'd be great to have in a separate class 👍 
But shouldn't the `delegate` keyword be reserved for protocols only?

2020-11-11 09:24 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallViewController/CallViewController.swift
> +            delegate?.callControllerDidDisappear(self)
Thanks for clarifying! The naming is good 👍

2020-11-11 09:27 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallController/ActiveCallRouter.swift
> +    func minimizeCall(animated: Bool, completion: (() -> Void)?)
Suggestion: `(() -> Void)?` -> `Completion?`

2020-11-11 10:26 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +        rootViewController.dismiss(animated: animated, completion: { [weak self] in
Yes, right. But the `rootViewController` of type `RootViewController`. We have just one instance of the `RootViewController` the tit is the root of the app.

2020-11-11 10:32 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallController/CallRouter.swift
> +}
Good point. Maybe `CallQualityAnimator`? What do you think about?

2020-11-16 10:49 UTC, David-Henner approved these changes

2020-11-16 12:04 UTC, merged