[Feature] Add notification to fetch feature config
wireapp/wire-ios pull request #4728
Opened 2020-11-24 06:22 UTC by KaterinaWire

## What's new in this PR?

Trigger app lock config fetch when app becomes active.

##  Dependencies
https://wearezeta.atlassian.net/browse/SQSERVICES-83

2020-11-24 07:02 UTC, johnxnguyen approved these changes

2020-11-24 07:03 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateCalculator.swift
> +        notifyToFetchFeatureConfig()
@marcomaddy1982 is this a good place to put this?

2020-11-24 09:18 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +        notifyToFetchFeatureConfig()
So the idea is that the `AppStateCalculator` would just calculate the `appState` and not doing any there business logic. You could try to do that in the `AppRootRouter`. Anyway, the `AppRootRouter` it is not completed and one day the idea is moving out from there all the business logic not related to navigation.

2020-11-24 09:39 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateCalculator.swift
> +        notifyToFetchFeatureConfig()
Yup makes sense, so we thought another place would be in the `AppLockPresenter`.

2020-11-24 09:40 UTC, johnxnguyen requested changes

2020-11-24 09:40 UTC, johnxnguyen commented on Wire-iOS/Sources/AppStateCalculator.swift
> +        NotificationCenter.default.post(name: FeatureConfigRequestStrategy.needsToFetchFeatureConfigNotificationName, object: nil)
As discussed, you may need to post a `NotificationInContext` object because this is the kind of notification being observed in the request strategy.

2020-11-24 09:40 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppStateCalculator.swift
> +        notifyToFetchFeatureConfig()
Yes, I guess I saw in the other PR. :-)

2020-11-24 12:14 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateCalculator.swift
> +        NotificationCenter.default.post(name: FeatureConfigRequestStrategy.needsToFetchFeatureConfigNotificationName, object: nil)
I will keep the same notification for now

2020-11-24 12:19 UTC, KaterinaWire commented on Wire-iOS/Sources/AppStateCalculator.swift
> +        notifyToFetchFeatureConfig()
@johnxnguyen We talked about adding a feature change observer to the `AppLockPresenter`.
But post notification about fetching feature we still need do it during the `applicationDidBecomeActive` event. 
I put it in `AppRootRouter` , as @marcomaddy1982 suggested.

2020-11-25 07:22 UTC, johnxnguyen approved these changes
If we use a downstream object sync for fetching single features, we would need to change this. But for now 👍

2020-12-04 06:29 UTC, typfel requested changes

2020-12-04 06:29 UTC, typfel commented on Wire-iOS/Sources/AppRootRouter.swift
> +        updateTeamFeature()
Is the long term plan to refetch all feature config every time the app becomes active

2020-12-04 06:29 UTC, typfel commented on Wire-iOS/Sources/AppRootRouter.swift
> +        updateTeamFeature()
You want to fetch the feature configs after logging/registration? We usually do this in our slow sync.

2020-12-04 10:44 UTC, KaterinaWire commented on Wire-iOS/Sources/AppRootRouter.swift
> +        updateTeamFeature()
It's a temp solution while we do not have update events from the BE.

2020-12-04 10:44 UTC, KaterinaWire commented on Wire-iOS/Sources/AppRootRouter.swift
> +        updateTeamFeature()
It's a temp solution.

2020-12-04 10:52 UTC, typfel approved these changes

2020-12-04 10:55 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppRootRouter.swift
> +extension AppRootRouter {
So I suppose that also this a temp solution?

2020-12-06 21:01 UTC, KaterinaWire commented on Wire-iOS/Sources/AppRootRouter.swift
> +extension AppRootRouter {
Yes, I added a comment to remove it in the future

2020-12-06 23:00 UTC, merged