[Feature] Hide / show app lock
wireapp/wire-ios pull request #4729
Opened 2020-11-24 06:26 UTC by KaterinaWire

## What's new in this PR?

Show App-lock feature in Wire settings based on BE App-lock status value.

### Dependencies

https://wearezeta.atlassian.net/browse/SQSERVICES-56

2020-11-24 07:07 UTC, johnxnguyen commented on WireCommonComponents/AppLock.swift
> +    public var isEnabled: Bool?
I think it would be fine to make `isEnabled` non optional and default to `true`. We should think of these default values as being applicable for non team users too, because in their case they will never get the config from the BE.

2020-11-24 11:53 UTC, KaterinaWire commented on WireCommonComponents/AppLock.swift
> +    public var isEnabled: Bool?
Updated

2020-11-24 12:04 UTC, johnxnguyen requested changes
It would be good to have a test for this.

2020-11-25 11:54 UTC, KaterinaWire commented
> It would be good to have a test for this.

@johnxnguyen 
It's no so easy, because the logic of show or hide App Lock feature is based on the App Lock rules, which I can't mock.

2020-12-03 06:55 UTC, typfel approved these changes

2020-12-03 07:14 UTC, marcomaddy1982 commented
@KaterinaWire since @johnxnguyen is off I took the freedom to review your PR and approve it. There is just test failing `testForOptionsGroupScrollToBottom` that could be a flaky tests.

2020-12-03 07:14 UTC, marcomaddy1982 approved these changes

2020-12-03 21:27 UTC, johnxnguyen approved these changes

2020-12-06 21:37 UTC, merged