[Fix]: On iPad no Spinner and Network Alert is shown when logout
wireapp/wire-ios pull request #4730
Opened 2020-11-24 09:26 UTC by marcomaddy1982

## What's new in this PR?

### Issues

on iPad when there is no connectivity and the user is logging out, after entering password and tapping OK dialog is closed, but nothing happens, no spinner is shown and no alert is shown.

### Causes

The `topMostViewController` is not of type `SpinnerCapableViewController` but `KeyboardAvoidingViewController`

### Solutions

when the `topMostViewController` is an `KeyboardAvoidingViewController` check if its `viewController` is of type `SpinnerCapableViewController` then activate the spinner and show the alert using it as presenter.

2020-11-24 09:35 UTC, typfel requested changes
Would it be an option to make `KeyboardAvoidingViewController` implement `SpinnerCapable`? I guess we could avoid the if statement then.

2020-11-24 09:58 UTC, David-Henner reviewed
I agree with Jacob's comment. 
If not possible, then I think it would make sense to extract the `if` statement out of the method for clarity

2020-11-24 10:02 UTC, marcomaddy1982 commented
> SpinnerCapable



> Would it be an option to make `KeyboardAvoidingViewController` implement `SpinnerCapable`? I guess we could avoid the if statement then.

Actually this was my first idea but then I opted for the solution I've implemented. Cause I found not really logic having a `KeyboardAvoidingViewController` as `SpinnerCapable` :-). Anyway, of course we could try to go for this other solution (if it works cause I didn't try).

2020-11-24 10:29 UTC, marcomaddy1982 commented
@typfel @David-Henner: `SpinnerCapable` works.

2020-11-24 10:37 UTC, typfel approved these changes
<deleted>

2020-11-24 12:03 UTC, David-Henner approved these changes

2020-11-26 09:46 UTC, typfel commented
@marcomaddy1982 ready to merge this?

2020-11-30 10:12 UTC, merged