Chore: xcode12 update
wireapp/wire-ios pull request #4742
Opened 2020-11-26 17:43 UTC by billypchan

## What's new in this PR?

minimal change to build with Xcode 12 on Azure

2021-02-18 16:45 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				);
```suggestion

```

2021-02-19 13:17 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				);
```suggestion

```

2021-02-23 06:48 UTC, typfel requested changes

2021-02-23 06:48 UTC, typfel commented on Wire-iOS.xcodeproj/project.pbxproj
> +				EXCLUDED_ARCHS = "i386 arm64";
Shouldn't this go into the [Base.xcconfig](https://github.com/wireapp/wire-ios/blob/develop/Wire-iOS/Resources/Configuration/Project-Base.xcconfig)

Same thing applies for the other build settings changes.

2021-02-23 06:48 UTC, typfel commented on carthageXcode12.sh
> +
```suggestion
```

2021-02-23 06:48 UTC, typfel commented on carthageXcode12.sh
> +#!/usr/bin/env bash
So this scripts is currently duplicated in the `wire-ios-shared-resources` but the plan is to remove once the Carthage fix is out?

2021-02-23 13:53 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				EXCLUDED_ARCHS = "i386 arm64";
It will be fixed in https://github.com/wireapp/wire-ios/pull/4963

2021-02-23 13:55 UTC, billypchan commented on carthageXcode12.sh
> +#!/usr/bin/env bash
yes, it is only need when building app, I will keep this script here til Carthage is fixed.

2021-02-23 14:46 UTC, johnxnguyen commented on azure-pipelines.yml
> +    DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/chore/xcode12"
Does this need to point to the master branch?

2021-02-23 14:46 UTC, johnxnguyen commented on carthageXcode12.sh
> +#!/usr/bin/env bash
What is the issue with Carthage?

2021-02-24 11:39 UTC, typfel commented on carthageXcode12.sh
> +#!/usr/bin/env bash
The issue described [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) and and in the Carthage 0.37.0 [release notes](https://github.com/Carthage/Carthage/releases/tag/0.37.0)

tl;dr we must use a workaround until we migrate our frameworks to be `XCFrameworks`.

2021-02-24 11:41 UTC, typfel commented on fastlane/Fastfile
> +            if cache_carthage == "Yes"
Can you explain this Carthage cache option?

2021-02-24 12:35 UTC, billypchan commented on fastlane/Fastfile
> +            if cache_carthage == "Yes"
This is for speeding up building on Jenkins by reusing the Carthage folder from the last build, I will add some comments for it.

2021-02-24 15:54 UTC, billypchan commented on setup.sh
> +./Scripts/download-assets.sh -b "chore/xcode12_simulator"
```suggestion
./Scripts/download-assets.sh "$@"
```

2021-02-24 20:25 UTC, billypchan commented on setup.sh
> +./Scripts/download-assets.sh -b "fix/xcode12-debug-simulator"
```suggestion
./Scripts/download-assets.sh "$@"
```

2021-02-24 22:15 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64 i386";
```suggestion
```

2021-02-24 22:15 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64 i386";
```suggestion
```

2021-02-25 13:52 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				SDKROOT = iphoneos;
```suggestion
```

2021-02-25 13:52 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				SDKROOT = iphoneos;
```suggestion
```

2021-02-25 17:57 UTC, billypchan commented on setup.sh
> +./Scripts/download-assets.sh -b fix/xcode12-debug-simulator
```suggestion
./Scripts/download-assets.sh "$@"
```

2021-03-02 12:54 UTC, billypchan commented on fastlane/Fastfile
> +            if cache_carthage == "Yes"
comment added

2021-03-02 12:54 UTC, billypchan commented on azure-pipelines.yml
> +    DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/chore/xcode12"
TODO added

2021-03-02 12:57 UTC, johnxnguyen approved these changes

2021-03-02 14:53 UTC, marcomaddy1982 approved these changes

2021-03-02 14:54 UTC, marcomaddy1982 commented
@billypchan Approved but some tests are failing.

2021-03-02 14:56 UTC, billypchan commented
@marcomaddy1982 the snapshot updates are done here: https://github.com/wireapp/wire-ios/pull/4956. When that one is passed we can merge that PR to here.

2021-03-03 09:24 UTC, merged