[Refactor] Use Applock in user session
wireapp/wire-ios pull request #4748
Opened 2020-12-02 08:40 UTC by KaterinaWire

## What's new in this PR?

Instead of using the static properties of the `AppLock` class, we will use the applock instance of `UsserSession`.

This PR is one in a series for refactoring for AppLock. Full description of refactoring you can find here:
wireapp/wire-ios-data-model/pull/1078

Needs releases with:

- [ wireapp/wire-ios-sync-engine/pull/1351 ]

2020-12-02 09:06 UTC, johnxnguyen commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +    }
You only need the self user so it would be better to just pass in that through the initializer rather than a context.

2020-12-02 09:06 UTC, johnxnguyen commented on Wire-iOS/Sources/Authentication/Event Handlers/Initial Sync/AuthenticationInitialSyncEventHandler.swift
> -            }
Note, we are removing the the custom passcode flow here, but still need to do it elsewhere. It would be good to create a ticket so we don't forget about this.

2020-12-02 09:06 UTC, johnxnguyen commented on Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory+AppLock.swift
> +    }
This is one of those cases where we probably can reasonably expect there to always be a user session available, but the use of singletons doesn't allow us to be certain about this. I wonder if we can initialize an instance of `SettingsPropertyFactory` with the current user session. @typfel thoughts?

2020-12-02 09:06 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
> +    var appLock: AppLockController? {
As a note, if we had a `locked` app state, we could create the app lock module only when necessary and inject an instance of `AppLockController`, then we wouldn't have to worry about optionals. But that's an improvement to think about later.

2020-12-02 09:08 UTC, typfel requested changes

2020-12-02 09:08 UTC, typfel commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +        userSessionMock = UserSessionMock(moc: uiMOC)
Some options: 
- Change the `AppLockController` to take a `UserType` instead of `ZMUser`
- Expose protocol type of the `AppLockController` on the ZMUserSession.

2020-12-02 09:08 UTC, typfel commented on Wire-iOS/Sources/Authentication/Event Handlers/Initial Sync/AuthenticationInitialSyncEventHandler.swift
> -            // append passcode step if new registered or first time login but passcode is not store.(Upgrade from pervious version)
You decided not to ask the user to set passcode during login/registration?

2020-12-02 09:08 UTC, johnxnguyen approved these changes

2020-12-02 09:10 UTC, typfel commented on Wire-iOS/Sources/Authentication/Event Handlers/Initial Sync/AuthenticationInitialSyncEventHandler.swift
> -            // append passcode step if new registered or first time login but passcode is not store.(Upgrade from pervious version)
John answered this question.

2020-12-02 09:18 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +        userSessionMock = UserSessionMock(moc: uiMOC)
The reason I used `ZMUser` instead of `UserType` in `AppLockController` is because we need to get a `team` from the user. The `UserType` protocol does not provide a `team`.

2020-12-02 09:21 UTC, typfel commented on Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory+AppLock.swift
> +    }
Yes, that would make sense.

Seems like we already initialise the `SettingsPropertyFactory` with the current user session, it's abstracted by the `ZMUserSessionInterface`though, which doesn't expose much functionality. It was probably added for mocking purposes in the tests.

I would propose to use the same strategy as in the interactors and inject a composed protocol of all the necessary user session protocols.

2020-12-02 09:22 UTC, KaterinaWire commented on WireCommonComponents/AppLock.swift
>  public struct AppLockRules: Decodable {
Yes, we use it now for `ShareExtension`, because we need to provide a bundle configuration to initialise the `ApplockController`.

2020-12-02 09:23 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
> +    var appLock: AppLockController? {
Wasn't this `locked` app state already introduced by another PR from @KaterinaNikolaenko that was never merged. Will you revisit that PR soon and then also make this improvement?

2020-12-02 09:26 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +    }
Fixed

2020-12-02 09:34 UTC, typfel commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +        userSessionMock = UserSessionMock(moc: uiMOC)
Then option 2 would be the way to go.

or you could expose the `team` on the `UserType` and update `TeamType` to expose the properties you need. But be overkill since you don't want to test the internals of `AppLockController` in the UI...

2020-12-02 09:48 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockInteractor.swift
> +    var appLock: AppLockController? {
Yes, we discussed with @johnxnguyen to have that PR become part of this refactoring. But it will take time to fix all merge conflicts.

2020-12-02 09:51 UTC, marcomaddy1982 commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +                                                     useCustomCodeInsteadOfAccountPassword: false,
It is not align well here.

2020-12-02 09:52 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +        userSessionMock = UserSessionMock(moc: uiMOC)
Do I understand you correctly about the second option:
instead of heaving 
`var appLockController: AppLockController` in ZMUserSession

to have something like this:

```
protocol AppLockType {
    var isActive: Bool { get set }
    var lastUnlockedDate: Date { get set }
    var isCustomPasscodeNotSet: Bool { get }
    var config: AppLockController.Config { get }
    
    func persistBiometrics()
}

var appLockController: AppLockType?

```

2020-12-02 10:16 UTC, KaterinaWire commented on Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory+AppLock.swift
> +    }
Yes, we initialise `SettingsPropertyFactory`  with the current user session, but `userSession` is optional too.

2020-12-02 10:19 UTC, typfel commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +        userSessionMock = UserSessionMock(moc: uiMOC)
Exactly

2020-12-02 10:22 UTC, typfel commented on Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory+AppLock.swift
> +    }
> Yes, we initialise `SettingsPropertyFactory` with the current user session, but `userSession` is optional too.

We can change it to be not optional. The unwrapping can happen higher up somewhere.

2020-12-02 22:03 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +        userSessionMock = UserSessionMock(moc: uiMOC)
Implemented

2020-12-02 22:03 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockInteractorTests.swift
> +                                                     useCustomCodeInsteadOfAccountPassword: false,
Fixed

2020-12-03 07:42 UTC, marcomaddy1982 commented
@KaterinaWire since @johnxnguyen  is off I took the freedom to review your PR and approve it.

2020-12-03 07:42 UTC, marcomaddy1982 approved these changes

2020-12-03 10:16 UTC, KaterinaWire commented on Wire-iOS/Sources/Authentication/Event Handlers/Initial Sync/AuthenticationInitialSyncEventHandler.swift
> -            }
Done 
https://wearezeta.atlassian.net/browse/SQSERVICES-103

2020-12-03 10:23 UTC, KaterinaWire commented on Wire-iOS/Sources/Components/Settings/SettingsPropertyFactory+AppLock.swift
> +    }
I would do this refactoring later, because we also initialise `SettingsPropertyFactory` with `nil`parameters in `AVSMediaManager`. These changes will covert some another classes not related to this PR.

I created a ticket not to forget about it:
https://wearezeta.atlassian.net/browse/SQSERVICES-104

2020-12-06 20:26 UTC, merged