clean up tests and do not set up observer when tests
wireapp/wire-ios pull request #4759
Opened 2020-12-08 16:47 UTC by billypchan

## What's new in this PR?

Do not create unnecessary observers when testing
Clean up tests which do not release release resources

2020-12-08 17:09 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
> +            }
If the observer registration is not required to be done before the lines below (where we call the `update...()` methods) then I think we could move observer registration to the end of `viewDidLoad`. Then assess if tests are running in a guard statement and return early if they are. That way we can avoid nesting `if` statements

2020-12-08 17:09 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
> +        if !ProcessInfo.processInfo.isRunningTests {
I'd also change this with a guard statement

2020-12-08 17:21 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
> +            }
I moved set up observer code to a new method.

2020-12-08 17:22 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
> +            }
even better 👍

2020-12-08 17:26 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
> +        if !ProcessInfo.processInfo.isRunningTests {
also moved to a seperated method

2020-12-08 17:42 UTC, David-Henner approved these changes

2020-12-09 07:03 UTC, typfel requested changes
I think the nilling in the  `deinit` is unnecessary and you anyway not starting any observers in the tests.

2020-12-09 07:03 UTC, typfel commented on Wire-iOS/Sources/UserInterface/ConversationList/BackgroundViewController.swift
> +    deinit {
Also redundant

2020-12-09 08:43 UTC, billypchan commented
@typfel removed token clean up in deinit

2020-12-09 09:02 UTC, typfel approved these changes

2020-12-09 09:46 UTC, merged