[Feature] Update decryption error message to include button to reset the session
wireapp/wire-ios pull request #4763
Opened 2020-12-09 10:16 UTC by typfel

## What's new in this PR?

Update decryption error message to include button to reset the session

Needs releases with:

- [ ] https://github.com/wireapp/wire-ios-data-model/pull/1087

### Notes

There will be some UI tweaks to the appearance of this message in a separate PR.

2020-12-10 13:13 UTC, billypchan requested changes

2020-12-10 13:13 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+MessageFormatting.swift
> +    }
We should use `enum` here since we never create a Wire struct instance.

```suggestion
extension CGFloat {
    enum DefaultParagraph {
        static let spacing: CGFloat = 8
    }

```

2020-12-10 13:13 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+MessageFormatting.swift
> +    }
and this can be put outside extension NSAttributedString

2020-12-10 17:26 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
> +        return (BaseLocalizationString + ".reset_session").localized.localizedUppercase
Shouldn't enough just `(BaseLocalizationString + ".reset_session").localizedUppercase`?

2020-12-11 06:43 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConfigurationMessageCell/Components/ConversationSystemMessageCell.swift
> +        return (BaseLocalizationString + ".reset_session").localized.localizedUppercase
The `localizedUppercase` is misleading in this case. It converts a string to uppercase following the rules of the current locale, it doesn't anything with localisation strings.

2020-12-11 06:44 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+MessageFormatting.swift
> +    }
👍 I'll find a better place for it.

2020-12-11 07:27 UTC, KaterinaWire approved these changes

2020-12-11 07:39 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+MessageFormatting.swift
> +    }
Moved it to `CGFloat+Const.swift`

2020-12-11 08:20 UTC, billypchan approved these changes

2021-01-05 12:18 UTC, billypchan approved these changes

2021-01-05 12:21 UTC, marcomaddy1982 approved these changes

2021-01-07 17:04 UTC, merged