fix: CallInfoConfigurationTests without ZMUser
wireapp/wire-ios pull request #4766
Opened 2020-12-09 15:27 UTC by billypchan

## What's new in this PR?

### Issues

On XCode 12, test suite may crash at `CallInfoViewControllerAccessoryType` is deallocing

### Causes

Unknown, but we should not use `ZMUser` for tests to prevent any side effect

### Solutions

Use `MockUserType` instead of `ZMUser` for testing.

2020-12-11 09:55 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    }
is this necessary because of the change from `ZMUser` to `UserType` ?

2020-12-11 10:37 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    }
I will add a similar change to https://github.com/wireapp/wire-ios-sync-engine/pull/1358/files, to remove the unnecessary casting.

2020-12-11 13:46 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    }
@David-Henner the equal checker is needed sine UserType is not necessary to be hashable.

2020-12-11 13:54 UTC, David-Henner approved these changes

2020-12-16 07:42 UTC, johnxnguyen requested changes

2020-12-16 07:42 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    }
I think there's an issue with the way you're casting and checking equality. Consider

```swift
let user1: ZMSearchUser = ...
let user2: ZMSearchUser = ...

// This evaluates to true, but it shouldn't
.incoming(user1) == .incoming(user2)
```

In this case, casting both `lhsUser` and `rhsUser` to `ZMUser` will fail, so the expression will be `nil == nil`. I think what you want to do is assert that if the left side is a `ZMUser`, then try to cast the right size as `ZMUser`. 

Similarly with `NSObject`, if the user type doesn't inherit from `NSObject` then you may get in the same situation of comparing `nil == nil`.

2020-12-16 07:53 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    }
I see that `UserType` extends `NSObjectProtocol`, so you can expect the cast to `NSObject` to always succeed.

2020-12-16 11:20 UTC, KaterinaWire approved these changes

2020-12-16 14:36 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    }
To get rid of the compare method, I use generic for the associated values. Since both `ZMUser` and `MockUserType` are subclasses of `NSObject`, we can use `NSObject` as the common generic type.

2020-12-17 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    case outgoing(degradedUser: User?)
This approach means there's a lot of casting since we lose all information about what the original user class was. Did you consider to use `HashBox` or something like that to give equatable conformance to `UserType`?

2020-12-17 15:55 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +    case outgoing(degradedUser: User?)
Refactored this PR with HashBoxed usertype

2020-12-17 17:09 UTC, David-Henner approved these changes

2020-12-17 17:09 UTC, David-Henner commented
There are two approvals on this PR but I would suggest to wait for @johnxnguyen 's review

2020-12-18 07:09 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallDegradationViewController/CallDegradationController.swift
> +            visibleAlertController = UIAlertController.degradedCall(degradedUser: degradeduser as? UserType, confirmationBlock: { [weak self] (continueDegradedCall) in
```suggestion
            visibleAlertController = UIAlertController.degradedCall(degradedUser: degradeduser?.value, confirmationBlock: { [weak self] (continueDegradedCall) in
```

2020-12-18 08:48 UTC, johnxnguyen approved these changes

2020-12-18 08:49 UTC, merged