[Feature] Notify user of feature changes
wireapp/wire-ios pull request #4774
Opened 2020-12-16 11:03 UTC by KaterinaWire

## What's new in this PR?

If mandatory app lock has been enabled or disabled, we should inform the user of the change.

Here is a design spec:
zpl://screen?pid=5f0f1143f783828d19da7721&sid=5fbbd5b02956135e8e9f3849 or https://zpl.io/bArgMpp

Needs releases with:

- [ https://github.com/wireapp/wire-ios-data-model/pull/1090 ]

2020-12-16 13:07 UTC, johnxnguyen requested changes

2020-12-16 13:07 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +        label.accessibilityIdentifier = "createPasscodeTitle"
According to the design specs, this view controller has dynamic content depending on where it gets presented, e.g the title can be "Create a passcode" and "There was a change in Wire".

You'll need to make this content dynamic, one way is to create a view model and inject different view models depending on where it's being created.

2020-12-16 13:07 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +        let headingText = NSAttributedString(string: "create_passcode.info_label_v2".localized) && baseAttributes && regularFont
Same here, this copy needs to be dynamic.

2020-12-16 13:07 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +final class WarningViewController: UIViewController {
This could have a more descriptive name (there's no indication that it is to do with app lock).

2020-12-16 13:07 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +        self.variant = variant ?? ColorScheme.default.variant
You could make `variant` non optional and simply provide the default value in the argument list.

2020-12-16 13:07 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +    private func onOkCodeButtonPressed(sender: AnyObject?) {
Suggestion: `confirmButtonTapped`

2020-12-16 13:07 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AuthenticationType.current == .unavailable || (UIDevice.isSimulator && AuthenticationType.current == .passcode) else {
What's this for?

2020-12-16 14:07 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +
Lis sent me this copy in 1:1 chat, but yes, I didn't find this screen in Zeplin.

2020-12-16 14:07 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"warning_screen.info_label.forced_applock" = "Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nNext time, unlock Wire the same way you unlock your phone.";
But we have it in Zeplin

2020-12-16 14:08 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = " Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
It's from Zeplin.

2020-12-16 14:41 UTC, KaterinaWire commented on Wire-iOS Tests/AppLock/AppLockPresenterTests.swift
> +        resetMocksValues()
Yes, don't need.
Removed.

2020-12-16 14:42 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
> +
Done

2020-12-16 14:42 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+FeatureChange.swift
> +    func showAFeatureChangeWarningScreenIfNeeded(callback: ResultHandler?) {
Done

2020-12-16 14:42 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +final class WarningViewController: UIViewController {
Renamed with `AppLockChangeWarningViewController`

2020-12-16 14:42 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +        self.variant = variant ?? ColorScheme.default.variant
Done

2020-12-16 14:42 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +    private func onOkCodeButtonPressed(sender: AnyObject?) {
Done

2020-12-16 14:44 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AuthenticationType.current == .unavailable || (UIDevice.isSimulator && AuthenticationType.current == .passcode) else {
It was done for Josh and automation testing on the simulator. Seems like there's no way to disable the device passcode on the simulator.

2020-12-16 14:54 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +
Will ask Eva

2020-12-16 14:54 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"warning_screen.info_label.forced_applock" = "Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nNext time, unlock Wire the same way you unlock your phone.";
Will ask Eva

2020-12-16 14:54 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = " Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
Will ask Eva

2020-12-16 14:55 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +        let headingText = NSAttributedString(string: "create_passcode.info_label_v2".localized) && baseAttributes && regularFont
Will ask Eva about copy and should it be dynamic

2020-12-16 14:55 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +        label.accessibilityIdentifier = "createPasscodeTitle"
Will ask Eva about copy and should it be dynamic

2020-12-16 15:06 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockPresenter.swift
> +                : appLockInteractorInput.evaluateAuthentication(description: AuthenticationMessageKey.deviceAuthentication)
Fixed

2020-12-16 18:36 UTC, David-Henner commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = " Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
```suggestion
"create_passcode.info_label_v2" = "Your organization needs to lock your app when Wire is not in use to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
```

It seems the copy might change anyway but here is my suggestion to fix typos

2020-12-16 18:36 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +final class AppLockChangeWarningViewController: UIViewController {
The file name and the class name aren't not the same, shouldn't they be?

2020-12-16 18:36 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +import WireSyncEngine
I'm a bit surprised to see `WireDataModel` and `WireSyncEngine` imported here. Are they needed?

2020-12-17 07:37 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/AppLockChangeWarningViewController.swift
> +    ///   - variant: color variant for this screen. When it is nil, apply app's current scheme
Need to update the comment since `variant` is not optional.

2020-12-17 07:37 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AuthenticationType.current == .unavailable || (UIDevice.isSimulator && AuthenticationType.current == .passcode) else {
Then I suggest to document its purpose, either with a comment or using variable names.

2020-12-17 13:12 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/AppLockChangeWarningViewController.swift
> +    ///   - variant: color variant for this screen. When it is nil, apply app's current scheme
Fixed

2020-12-17 13:12 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +import WireSyncEngine
You are right, `WireSyncEngine` is enough

2020-12-17 13:12 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/WarningViewController.swift
> +final class AppLockChangeWarningViewController: UIViewController {
Fixed

2020-12-17 13:13 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +        let headingText = NSAttributedString(string: "create_passcode.info_label_v2".localized) && baseAttributes && regularFont
Add a context to this screen

2020-12-17 13:13 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +        label.accessibilityIdentifier = "createPasscodeTitle"
Add a context to this screen

2020-12-17 13:15 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = " Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
Could you check typos?

2020-12-17 13:15 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"warning_screen.info_label.forced_applock" = "Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nNext time, unlock Wire the same way you unlock your phone.";
Could you check typos?

2020-12-17 13:24 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/SelfProfile/SelfProfileViewController.swift
> +        guard AuthenticationType.current == .unavailable || (UIDevice.isSimulator && AuthenticationType.current == .passcode) else {
Added a comment

2020-12-17 13:25 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +                  context: Context) {
Typically callbacks should be the last argument so that they can be passed in as a trailing closure.

2020-12-17 13:25 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = "Your organization needs to lock your app when Wire is not in use to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
```suggestion
"create_passcode.info_label_forced_applock" = "Your organization needs to lock your app when Wire is not in use to keep the team safe.\n\nCreate a passcode to unlock Wire. Please remember it, as ";
```

2020-12-17 13:25 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = "Your organization needs to lock your app when Wire is not in use to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
Is there something missing at the end? "Please remember it, as ....?"

2020-12-17 13:25 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = "Your organization needs to lock your app when Wire is not in use to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
Oh I see, it's because the next part is highlighted. I see that this is existing behavior, but it's not a good thing to do because it makes it difficult for translators.

2020-12-17 13:25 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"warning_screen.info_label.forced_applock" = "Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nNext time, unlock Wire the same way you unlock your phone.";
```suggestion
"warning_screen.info_label.forced_applock" = "Your organization needs to lock your app when Wire is not in use to keep the team safe.\n\nNext time, unlock Wire the same way you unlock your phone.";
```

2020-12-17 13:25 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"warning_screen.info_label.forced_applock" = "Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nNext time, unlock Wire the same way you unlock your phone.";
To avoid duplication, you could split this copy at the new lines.

2020-12-17 13:25 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +
```suggestion
"warning_screen.info_label.non_forced_applock" = "Your organization does not need app lock anymore. From now, you can access Wire without any obstacles.";

```

2020-12-17 13:27 UTC, johnxnguyen requested changes
Don't forget to update tests to account for the different contexts.

2020-12-18 09:42 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/AppLockChangeWarningViewController.swift
> +    required init(callback: ResultHandler? = nil,
I think callback should be the last parameter here too

2020-12-18 10:45 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Warning/AppLockChangeWarningViewController.swift
> +    required init(callback: ResultHandler? = nil,
Fixed

2020-12-18 10:46 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupViewController.swift
> +                  context: Context) {
Fixed

2020-12-18 11:01 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"create_passcode.info_label_v2" = "Your organization needs to lock your app when Wire is not in use to keep the Team safe.\n\nCreate a passcode to unlock Wire. Please, remember it, as ";
Yes, I agree, but we have it already for "create_passcode.info_label"  string

2020-12-18 11:04 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"warning_screen.info_label.forced_applock" = "Your organization needs to lock you app when Wire is not in used to keep the Team safe.\n\nNext time, unlock Wire the same way you unlock your phone.";
I created a separate localized string for common text.

2020-12-18 11:48 UTC, KaterinaWire commented
> Don't forget to update tests to account for the different contexts.

@johnxnguyen Added tests

2020-12-18 12:45 UTC, johnxnguyen requested changes
The old snapshots ("Create a passcode") seem to have indentation issues. Are you joining the separate strings with a space or new line?

2020-12-21 09:10 UTC, David-Henner approved these changes

2020-12-22 10:59 UTC, johnxnguyen approved these changes

2020-12-22 12:54 UTC, merged