[Fix] Delete passcode if app lock is disabled in team settings
wireapp/wire-ios pull request #4850
Opened 2021-01-18 22:49 UTC by KaterinaWire

## What's new in this PR?

https://wearezeta.atlassian.net/browse/SQSERVICES-203

### Issues
Disabling app lock in team settings doesn't delete the custom passcode in keychain. 

### Solutions

Delete the passcode when the client receives a notification that the team admin has disabled mandatory app lock.

2021-01-19 08:01 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+FeatureChange.swift
> +            }
I think we can solve this more generally by trying to delete the passcode whenever the app lock is turned off (either explicitly by the user or implicitly when the config changes). This would likely happen in the data model.

2021-01-19 10:06 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+FeatureChange.swift
> +                }
```suggestion
                try? appLock.deletePasscode()
```

2021-01-19 10:08 UTC, johnxnguyen requested changes
Please add a test.

2021-01-19 23:37 UTC, KaterinaWire commented
> Please add a test.

I added a test, but it required additional changes.

2021-01-20 06:33 UTC, typfel requested changes
Just minor nitpicks otherwise it looks good 👍

2021-01-20 06:33 UTC, typfel commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
> +    // For tests
I would remove this comment. We want to reach the point where we only interact with the user session through protocols and this is one step in that direction not only something we do for tests.

2021-01-20 06:33 UTC, typfel commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+FeatureChange.swift
> +            !appLock.isActive else {
To me it's nicer if we create the VC only after all the checks have been passed like this:

```suggestion
        guard 
            let appLock = appLock,
            appLock.needsToNotifyUser,
            !appLock.isActive
            let warningVC = changeWarningViewController, else {
```

2021-01-20 09:00 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController.swift
> +    // For tests
Removed

2021-01-20 09:18 UTC, typfel approved these changes

2021-01-20 09:30 UTC, johnxnguyen approved these changes

2021-01-20 09:37 UTC, merged