[Fix] Password validation
wireapp/wire-ios pull request #4854
Opened 2021-01-21 13:46 UTC by KaterinaWire

## What's new in this PR?

### Issues

During password validation, we separately received validation error that password is tooShort, or a list of other password mismatches (e.g. uppercase, lowercase, digits). This is an issue in UI project, because we can update theCreate password screen with information that password satisfies minimum length or other requirements.

E.g. User A is entering the part of the password: Qwe1

**Expectation**
To see that this part satisfies 3 rules: uppercase, lowercase and digits.

**Outcome**
The password does not satisfy any requirements, because it's less than the minimum number of characters (error = tooShort).

https://wearezeta.atlassian.net/browse/SQSERVICES-208

### Solutions

Modify the structure of `PasswordValidationResult` to be able to contain a variety of rule violations:

```
public enum PasswordValidationResult: Equatable {

    /// The password is valid.
    case valid

	/// The password is invalid due to the violations.
	case invalid(violations: [Violation])

	public enum Violation {

	    /// The password is too short.
	    case tooShort
	
	    /// The password is too long.
	    case tooLong
	
	    /// The password contains a disallowed character.
	    case disallowedCharacter(Unicode.Scalar)
	
	    /// The password does not satisfy a requirement for a character class.
	    case missingRequiredClasses(Set<PasswordCharacterClass>)
	}
}
```
Needs releases with:

- [ wireapp/wire-ios-utilities/pull/104 ]

### Notes

`PasscodeValidationResult`, `PasscodeRuleSet`, `PasscodeCharacterClass` have been moved from `WireUtilities`.

2021-01-21 14:58 UTC, johnxnguyen commented on Wire-iOS/Sources/Authentication/Interface/Helpers/TextFieldValidator.swift
> +                return ""
If you're only interested in the `invalid` case you can simplify this with:

```swift
case .invalidPassword(.invalid(let violations)):
  return ...
```

2021-01-21 14:58 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupInteractor.swift
> +            interactorOutput?.passcodeValidated(result: .invalid(violations: []))
This doesn't really make any sense, I would expect that there is always at least one violation. Which situations lead to this case?

2021-01-21 18:13 UTC, typfel commented on Wire-iOS/Sources/Authentication/Helpers/PasscodeRules+Shared.swift
> +extension PasscodeRuleSet {
Aren't this password rules also used during registration?

2021-01-21 18:26 UTC, KaterinaWire commented on Wire-iOS/Sources/Authentication/Interface/Helpers/TextFieldValidator.swift
> +                return ""
Yes, I'm interested only in the invalid case, but I should provide default value for all cases. I rewrited this part

```
case .invalidPassword(let validationResult):
            switch validationResult {
            case .invalid(let violations) where violations.contains(.tooLong):
                return "password.guidance.toolong".localized
            default:
                return PasscodeRuleSet.localizedErrorMessage
            }
```

2021-01-21 18:30 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/CustomAppLock/Setup/PasscodeSetupInteractor.swift
> +            interactorOutput?.passcodeValidated(result: .invalid(violations: []))
Yes, you are right. We will get `error = .invalidPassword(result) `or `error = nil` according to this code:
```
let result = PasscodeRuleSet.shared.validatePasscode(text)
return result != .valid ? .invalidPassword(result) : nil
```

2021-01-21 18:36 UTC, KaterinaWire commented on Wire-iOS/Sources/Authentication/Helpers/PasscodeRules+Shared.swift
> +extension PasscodeRuleSet {
I moved `PasscodeRuleSet` class from `Utilities`. In the `Utilities` we use the word `Password` to name the classes, but in the UI we use the `Passcode`. I thought that it would be better if the names will match.

2021-01-22 06:33 UTC, typfel commented on Wire-iOS/Sources/Authentication/Helpers/PasscodeRules+Shared.swift
> +extension PasscodeRuleSet {
IMO it's better to keep the `Password` prefix since it's used for all our password validation: backup protection, registration and applock passcode, since that's more generic.

2021-01-22 06:41 UTC, typfel requested changes
Please move the `PasscodeRulesSet` and related to classes out of the `AppLock` folder into a non feature related folder. (for example: `Sources/Helpers/PasswordRules/`) and change the prefix back to `Password` since these rules are not only related to the passcode.

2021-01-22 06:51 UTC, johnxnguyen commented on Wire-iOS/Sources/Authentication/Interface/Helpers/TextFieldValidator.swift
> +        case invalidPassword(PasscodeValidationResult)
Now that we have all violations held in a single `invalid` case, it would make more sense to changes this case to `invalidPassword(Violations)`.

2021-01-22 06:51 UTC, johnxnguyen commented on Wire-iOS/Sources/Authentication/Helpers/PasscodeRules+Shared.swift
> +extension PasscodeRuleSet {
I think the terms "password" and "passcode" are interchangeable since both refer to a string of characters (regardless of what kind of characters).

2021-01-22 06:59 UTC, typfel commented on Wire-iOS/Sources/Authentication/Helpers/PasscodeRules+Shared.swift
> +extension PasscodeRuleSet {
I think in the context of mobile phones most people will think of an n-digit code when they read "passcode", might not be correct put that's what passcode means in the iOS world. I would prefer to keep using the word password at least for the generic code related to passwords.

2021-01-22 10:47 UTC, KaterinaWire commented
> Please move the `PasscodeRulesSet` and related to classes out of the `AppLock` folder into a non feature related folder. (for example: `Sources/Helpers/PasswordRules/`) and change the prefix back to `Password` since these rules are not only related to the passcode.

@typfel  Done

2021-01-22 10:59 UTC, typfel approved these changes

2021-01-22 11:16 UTC, KaterinaWire commented on Wire-iOS/Sources/Authentication/Interface/Helpers/TextFieldValidator.swift
> +        case invalidPassword(PasscodeValidationResult)
Done

2021-01-22 12:19 UTC, johnxnguyen approved these changes

2021-01-22 16:46 UTC, merged