[Feature] Add "Speaker / All" switch to call overlay
wireapp/wire-ios pull request #4855
Opened 2021-01-21 15:55 UTC by David-Henner

## What's new in this PR?

- Creates a new UI component `RoundedSegmentedView`. It behaves similarly to `UISegmentedControl`, which was too rigid to satisfy design requirements. 
- Adds new component to the `CallActionsView` 
- Removes unused code

2021-01-21 19:06 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/RoundedSegmentedView.swift
> +private extension UIButton {
Having a `private extension` is a good idea but another idea could be use a custom UIButton which `override` the `isSelect: Bool` instead to create a new method on the UIButton (also if private) :-) . Basically something like: 

```
class CustomButton: UIButton {
    override var isSelected: Bool {
        didSet {
            backgroundColor = isSelected ? .white : .clear
            setTitleColor(isSelected ? .black : .white, for: .normal)
        }
    }
}
```swift

Anyway, it is up to also in this manner is perfectly fine.

2021-01-21 19:16 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/RoundedSegmentedView.swift
> +    func roundedSegmentedView(_ view: RoundedSegmentedView, didSelectSegmentAtIndex index: Int)
This is just preference I have: in this case I like more to use a `actionBlock` (for instance you could add to the `init` method) than use the delegate pattern. The reason is the following: when I initialise the object I know directly which action is associated to it, on the contrary using the delegate pattern the logic related to the action is place where the delegate is implemented that sometimes for big class is not always super easy to find :-).
Anyway, it is just a thought, feel free to use your favourite approach :-).

2021-01-21 19:22 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/RoundedSegmentedView.swift
> +    func setSelected(_ selected: Bool, forItemAt index: Int) {
why don't just do:

```swift
for (i, button) in buttons.enumerated() {
  button.set(selected: i == index)
}
```
Am I missing something, i honestly don't understand the guard at the beginning :-)

2021-01-22 14:12 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/RoundedSegmentedView.swift
> +    func roundedSegmentedView(_ view: RoundedSegmentedView, didSelectSegmentAtIndex index: Int)
Good point. I like the idea of making the action clearer and easier to find on the consumer side.

2021-01-22 14:18 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/RoundedSegmentedView.swift
> +    func setSelected(_ selected: Bool, forItemAt index: Int) {
If `selected = false`, then the `guard` ensures we're only unselecting the button at the given index, and not selecting all other buttons.

Your suggestion to use `buttons.enumerated()` is better than fetching the index each time though, so I'll update it.
And I'll see if I can find a clearer way to write this method.

2021-01-25 06:42 UTC, typfel requested changes

2021-01-25 06:42 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/RoundedSegmentedView.swift
> +        setTitleColor(selected ? .black : .white, for: .normal)
You don't need to update this every time the selection changes since a UIButton can have different colours depending on its state. Instead you can do the following once during the button setup:

```
setTitleColor(.white, for: .normal)
setTitleColor(.black, for .selected)
setBackgroundImage(UIImage.singlePixelImage(with: .clear), for: .normal)
setBackgroundImage(UIImage.singlePixelImage(with: .white), for: .selectedl)
```

2021-01-25 06:42 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/RoundedSegmentedView.swift
> +    func roundedSegmentedView(_ view: RoundedSegmentedView, didSelectSegmentAtIndex index: Int)
A variant of this is to expose something like:
```
`func addButton(title: String, actionHandler: () -> Void)`
```

A benefit of having one handler per button is that the user of the `RoundedSegmentedView` doesn't need to look at the `index` to figure out which action he/she should perform.

2021-01-25 16:13 UTC, marcomaddy1982 approved these changes

2021-01-25 16:13 UTC, marcomaddy1982 commented
Seems good for me!! Thanks 👍 @David-Henner

2021-01-25 20:22 UTC, typfel approved these changes

2021-01-26 10:31 UTC, merged