[Fix] Unlock share extension with a custom passcode
wireapp/wire-ios pull request #4893
Opened 2021-02-04 13:29 UTC by KaterinaWire

## What's new in this PR?
https://wearezeta.atlassian.net/browse/SQSERVICES-225

### Issues

The share extension has no user interface to allow entering a custom passcode, which means that if the users rely on this custom passcode (i.e they can’t use biometrics) then they will not be able to unlock the share extension.

### Causes

This hasn't been implemented before.

### Solutions
1. Added a simplified version  of `UnlockViewController` to the Share extension. This viewController required a passcode field (`AccessoryTextField`) that is implemented in the UI target and contains a heavy logic. For this reason, I created `BaseAccessoryTextField` with basic logic that could be used for both the UI and the shareExtension targets.

2. Some extensions were opened for the Share extension.

### Notes

Working on adding tests now.

2021-02-05 07:25 UTC, johnxnguyen reviewed
So which types did you need to move to common components?

2021-02-05 07:25 UTC, johnxnguyen commented on Wire-iOS Share Extension/UIButton+SetIcon.swift
> +        setImage(image.withRenderingMode(renderingMode), for: state)
```suggestion        
        setImage(image.withRenderingMode(.alwaysTemplate), for: state)
```

2021-02-05 07:25 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Components/UIColor+Const.swift
> +        static var buttonLightGraphite: UIColor = UIColor(rgb:(141, 152, 159))
We should be using the colors from the color scheme. Are these new colors?

2021-02-05 07:25 UTC, johnxnguyen commented on Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
> +final class AccessoryTextField: BaseAccessoryTextField, TextContainer, Themeable {
I think the `Base` prefix isn't very descriptive, so I would suggest to rename these types to something like:

```swift
final class ValidatedTextField: AccessoryTextField
```

2021-02-05 07:25 UTC, johnxnguyen commented on Wire-iOS Share Extension/AccessoryTextField.swift
> +        iconButton.tintColor = UIColor.Team.textColor
A team color seems a bit out of place here.

2021-02-05 07:25 UTC, johnxnguyen commented on Wire-iOS Share Extension/AccessoryTextField.swift
> +        iconButton.accessibilityLabel = "Reveal passcode".localized
Is this accessibility label a key or content?

2021-02-05 07:25 UTC, johnxnguyen commented on Wire-iOS Share Extension/ShareExtensionViewController.swift
> +                self.showChooseConversation()
Probably we should change this to

```swift
guard self.localAuthenticationStatus == .granted else { return }
self.showChooseConversation()
```

2021-02-05 12:29 UTC, KaterinaWire commented on Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
> +final class AccessoryTextField: BaseAccessoryTextField, TextContainer, Themeable {
Yes, it makes sense to have `ValidatedTextField` in the UI. But for Share extension, I would give the name: 
`final class PasscodeTextField: AccessoryTextField`
because it's for passcode only and we are not doing any validation.

2021-02-05 13:39 UTC, KaterinaWire commented on Wire-iOS Share Extension/AccessoryTextField.swift
> +        iconButton.accessibilityLabel = "Reveal passcode".localized
It was a content. I changed it to the key.

2021-02-05 13:39 UTC, KaterinaWire commented on Wire-iOS Share Extension/ShareExtensionViewController.swift
> +                self.showChooseConversation()
Fixed

2021-02-05 13:47 UTC, KaterinaWire commented on Wire-iOS Share Extension/AccessoryTextField.swift
> +        iconButton.tintColor = UIColor.Team.textColor
I used the same color as we are using in a current   `AccessoryTextField`.

2021-02-05 13:48 UTC, johnxnguyen commented on Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
> +final class AccessoryTextField: BaseAccessoryTextField, TextContainer, Themeable {
Sounds good to me 👍🏻

2021-02-05 13:53 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Components/UIColor+Const.swift
> +        static var buttonLightGraphite: UIColor = UIColor(rgb:(141, 152, 159))
These colors are using by UnlockViewController in the `Share extension`. This colours are using by `UnlockViewController` in  Share extension. For this screen, we always use dark mode.

2021-02-05 14:34 UTC, KaterinaWire commented on Wire-iOS/Sources/Authentication/Interface/Views/AccessoryTextField.swift
> +final class AccessoryTextField: BaseAccessoryTextField, TextContainer, Themeable {
Done

2021-02-05 15:00 UTC, KaterinaWire commented
> So which types did you need to move to common components?

`ColorScheme.swift`.

2021-02-05 15:02 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Components/UIColor+Const.swift
> +        static var buttonLightGraphite: UIColor = UIColor(rgb:(141, 152, 159))
I copied these colors from the `ColorScheme`. So, I think it's better to move `ColorScheme` to the Common components.

2021-02-05 18:25 UTC, David-Henner commented on Wire-iOS Share Extension/ShareExtensionViewController.swift
> +                    completion()
doesn't this mean that `completion()` will be called twice because of the `defer` statement?

2021-02-08 13:31 UTC, johnxnguyen requested changes
You should probably delete the old `AccessoryTextFieldTests/` snapshot directory.

2021-02-08 13:43 UTC, KaterinaWire commented
> `AccessoryTextFieldTests/` snapshot directory

Deleted

2021-02-08 13:43 UTC, KaterinaWire commented on Wire-iOS Share Extension/ShareExtensionViewController.swift
> +                    completion()
Yes, you are right. I removed `defer` statement.

2021-02-08 13:46 UTC, KaterinaWire commented
@johnxnguyen Could you please help with the copies in the popup? Eva asked, because Lis is on vacation now.
"share_extension.unlock.alert.title"
"share_extension.unlock.alert.message"

2021-02-08 13:49 UTC, KaterinaWire commented
@johnxnguyen @David-Henner I will add tests in the separate PR, because it's not a trivial task. I can't just add Wire-Share extension Tests or add a test to the Wire-iOS Tests, that requires more research.

2021-02-08 13:52 UTC, David-Henner approved these changes

2021-02-08 13:53 UTC, johnxnguyen commented
> Could you please help with the copies in the popup? Eva asked, because Lis is on vacation now.

@KaterinaNikolaenko  I think the title is unnecessary here. Then I would change the message to:
```
"share_extension.unlock.alert.message" = "Open Wire to create a passcode";
```

2021-02-08 13:53 UTC, johnxnguyen approved these changes

2021-02-08 14:58 UTC, merged