Remove MessageDetailsViewControllerTests CoreDataSnapshotTestCase subclassing
wireapp/wire-ios pull request #4894
Opened 2021-02-04 14:20 UTC by billypchan

## What's new in this PR?

Remove `MessageDetailsViewControllerTests` `CoreDataSnapshotTestCase` subclassing and use Swift snapshot testing instead.

2021-02-04 15:08 UTC, KaterinaWire commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var localParticipantsContainUser: Bool = false
For me, the name of the property is not very clear. When I read the property name, I have a question about which User we are talking about.

2021-02-04 15:27 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift
> +        guard let conversation = self.conversationLike else {
Just a general question. Since the conversation is now deprecated, there are some warnings in the UI project. Are you going to open another PR and replace `conversation` with `conversationLike`?

2021-02-04 15:52 UTC, typfel commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var localParticipantsContainUser: Bool = false
So the `SwiftMockConversation` doesn't have a list users?

2021-02-04 15:53 UTC, billypchan commented on Wire-iOS/Sources/Helpers/syncengine/ZMMessage+Likes.swift
> +        guard let conversation = self.conversationLike else {
Yes, clean up will be done before ` feature/abstract-conversation` is merged.

2021-02-04 15:55 UTC, billypchan commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var localParticipantsContainUser: Bool = false
renamed to `mockLocalParticipantsContainUserReturn`

2021-02-04 16:15 UTC, billypchan commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var localParticipantsContainUser: Bool = false
@typfel since `ZMConversation` has the arrays of `ZMUser` and we don't want to mock those arrays, this mocking method mocks `localParticipants` (type: `[ZMUser]`) has a user or not.

2021-02-05 11:16 UTC, KaterinaWire commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var localParticipantsContainUser: Bool = false
What if we just rename this property to `isLocalParticipantsEmpty` or something like this? It would be cleare what we are going to mock.

2021-02-05 11:27 UTC, KaterinaWire commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var localParticipantsContainUser: Bool = false
But I don't insist. It is just my opinion.

2021-02-05 11:27 UTC, KaterinaWire approved these changes

2021-02-15 11:43 UTC, johnxnguyen commented
FYI @billypchan there's a lot of conflicts. I'll wait for them to be resolved first before reviewing.

2021-02-15 13:20 UTC, johnxnguyen commented on Wire-iOS Tests/MessageDetails/MessageDetailsViewControllerTests.swift
> +		//        }
Is this relevant?

2021-02-15 16:19 UTC, billypchan commented on Wire-iOS Tests/MessageDetails/MessageDetailsViewControllerTests.swift
> +		//        }
cleared

2021-02-15 19:06 UTC, johnxnguyen requested changes
Please correct the indentation issues.

2021-02-16 08:22 UTC, johnxnguyen approved these changes

2021-02-16 08:43 UTC, merged