refactor UserSearchResultsViewControllerTests
wireapp/wire-ios pull request #4905
Opened 2021-02-08 13:22 UTC by billypchan

## What's new in this PR?

Refactor `UserSearchResultsViewControllerTests` with Swift snapshot testing and prevent creating `ZMUser`s

2021-02-08 13:36 UTC, johnxnguyen requested changes
There are quite a few issues with indentation, looks like your editor is using 2 spaces.

2021-02-08 13:36 UTC, johnxnguyen commented on Wire-iOS Tests/UserSearchResultsViewControllerTests.swift
> +		for name in XCTestCase.usernames {
Where is `XCTestCase.usernames` defined? Why is it an extension on `XCTestCase`?

2021-02-08 13:40 UTC, billypchan commented on Wire-iOS Tests/UserSearchResultsViewControllerTests.swift
> +		for name in XCTestCase.usernames {
`usernames` was a property `CoreDataSnapshotTestCase`. I put it on its super class `XCTestCase` after refactoring. We can also put it in another class like `MockUserType`

2021-02-08 13:59 UTC, johnxnguyen commented on Wire-iOS Tests/UserSearchResultsViewControllerTests.swift
> +		for name in XCTestCase.usernames {
I think `MockUserType` is a more suitable place to put it.

2021-02-08 15:02 UTC, johnxnguyen approved these changes

2021-02-10 16:06 UTC, marcomaddy1982 approved these changes

2021-02-10 16:08 UTC, merged