[Refactoring]: SQCORE-363 Unify Login/Registration API
wireapp/wire-ios pull request #4924
Opened 2021-02-10 14:13 UTC by marcomaddy1982

## What's new in this PR?

### Issues

The scope of the following PR is apply in the UI  the changes related to the refactoring of the SE made in the [Unify Login/Registration API PR](https://github.com/wireapp/wire-ios-sync-engine/pull/1388)

### Dependencies

[sync-engine](https://github.com/wireapp/wire-ios-sync-engine/pull/1388)

2021-02-11 14:04 UTC, typfel requested changes

2021-02-11 14:04 UTC, typfel commented on Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
> +    var authenticationStatus: ZMAuthenticationStatus {
Who uses access this property? Can it be removed?

2021-02-11 14:05 UTC, typfel commented
Will you can run a regression run against these changes?

2021-02-11 14:47 UTC, marcomaddy1982 commented on Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
> +    var authenticationStatus: ZMAuthenticationStatus {
Right thanks!!!

2021-02-11 14:49 UTC, marcomaddy1982 commented
> Will you can run a regression run against these changes?

Yes we have to run regression on this. That's why there is the label "Do not merge" cause I will create first a playground build once all the SE PRs are merged and this approved.

2021-02-11 14:54 UTC, marcomaddy1982 commented on Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
> +    var authenticationStatus: ZMAuthenticationStatus {
Maybe I could change the access modifier to `private` instead of removing completely.

2021-02-11 16:15 UTC, typfel commented on Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
> +    var authenticationStatus: ZMAuthenticationStatus {
But it's not used at all so why keep it?

2021-02-11 16:23 UTC, marcomaddy1982 commented on Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
> +    var authenticationStatus: ZMAuthenticationStatus {
Sorry I got confused with `registrationStatus: RegistrationStatus`, my bad. Anyway now r`egistrationStatus: RegistrationStatus` is `private`

2021-02-11 16:51 UTC, marcomaddy1982 commented on Wire-iOS/Sources/Authentication/Coordinator/AuthenticationCoordinator.swift
> +    var authenticationStatus: ZMAuthenticationStatus {
Done

2021-02-11 16:52 UTC, typfel approved these changes

2021-02-12 09:41 UTC, johnxnguyen approved these changes

2021-02-17 10:33 UTC, merged