[Feature]: SQCORE-212: Hide Search Icon when EAR is enabled.
wireapp/wire-ios pull request #4929
Opened 2021-02-11 11:23 UTC by marcomaddy1982

## What's new in this PR?

Currently when EAR is being enable the search icon in a conversation is disabled, this behaviour could confuse the user cause the icon is visible but he/she couldn’t use it.  

To avoid this when EAR is being enabled the search icon in a conversation will be no longer visible.

2021-02-11 13:59 UTC, typfel requested changes

2021-02-11 13:59 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
> +            SecurityFlags.forceEncryptionAtRest.isEnabled == false,
You can remove this since `session.encryptMessagesAtRest` is always true if `SecurityFlags.forceEncryptionAtRest.isEnabled` is true.

2021-02-11 14:23 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
> +            SecurityFlags.forceEncryptionAtRest.isEnabled == false,
@typfel I know this,  but I added also it cause we should hide he search icon when `SecurityFlags.forceEncryptionAtRest.isEnabled` is `false`,  and `session.encryptMessagesAtRest` is `true` cause enabled from the user.

2021-02-11 14:28 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
> +            SecurityFlags.forceEncryptionAtRest.isEnabled == false,
Right, but you achieve this behaviour by only checking  `session.encryptMessagesAtRest == false`. If the user toggles EAR `session.encryptMessagesAtRest` will be `true`.

2021-02-11 14:42 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
> +            SecurityFlags.forceEncryptionAtRest.isEnabled == false,
Now I remember why i put both checks in the `guard` statements,  I tried again and correct me if I'm wrong. The scenariois the following:
1) in the `Security-Flags.xcconfig` file  `FORCE_ENCRYPTION_AT_REST_ENABLED=1`
and 
2) user disabled EAR

having just `session.encryptMessagesAtRest` in the `guard` the result is that the search icon is visible.

2021-02-15 11:54 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
> +            SecurityFlags.forceEncryptionAtRest.isEnabled == false,
How is it possible that the user disables EAR when it's being forced?

2021-02-15 12:40 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
> +            SecurityFlags.forceEncryptionAtRest.isEnabled == false,
So we found that `SecurityFlags` exists only in the UI project and is not used to influence the value of the `encryptMessagesAtRest` property on the user session. The old flag `encryptionAtRestEnabledByDefault` in `session_manager.json` is used for this purpose.

So, the logic here is correct, but I would say it's dangerous to have two different flags for the same purpose. We should remove one of them.

2021-02-15 12:40 UTC, johnxnguyen approved these changes

2021-02-15 12:51 UTC, KaterinaWire approved these changes

2021-02-15 13:16 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+NavigationBar.swift
> +            SecurityFlags.forceEncryptionAtRest.isEnabled == false,
@johnxnguyen thanks for helping clarify

2021-02-15 14:59 UTC, merged