[Fix] App Lock Screen copy when biometrics are disabled
wireapp/wire-ios pull request #4936
Opened 2021-02-12 17:30 UTC by KaterinaWire

## What's new in this PR?

https://wearezeta.atlassian.net/browse/SQSERVICES-198

### Issues

When EAR is enabled and there're no biometrics on the device, we show an `Unlock` button on the Applock screen, but this button does nothing (we can't unlock Wire with a custom passcode).

### Solutions

Rename the button and open the device settings when the user press it.

2021-02-12 19:18 UTC, johnxnguyen reviewed
What happens when the user sets a passcode and comes back to the app? Will the view refresh?

2021-02-12 19:18 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockView.swift
> +            UIApplication.shared.open(url, options: [:], completionHandler: nil)
Do this just open the settings? Can we open to the passcode page?

2021-02-12 19:18 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockView.swift
> +        self.authenticationType = authenticationType
You don't need to store this as a property if you pass it to the `setupActionButton` method.

2021-02-15 16:40 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockView.swift
> +            UIApplication.shared.open(url, options: [:], completionHandler: nil)
Yes, it opens the settings. I've made some research on how to open specific settings. There are many articles that suggest using URL schemes (e.g.` UIApplication.shared.open(URL(string: "App-prefs:Bluetooth"))`), but Apple could reject the app if we take this approach.
Here are a couple of links explaining it:
https://stackoverflow.com/questions/28152526/how-do-i-open-phone-settings-when-a-button-is-clicked
https://developer.apple.com/forums/thread/100471
https://developer.apple.com/forums/thread/65007

2021-02-15 18:34 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Overlay/AppLockView.swift
> +        self.authenticationType = authenticationType
I merged this PR with the `develop` branch. There are new changes.

2021-02-15 19:39 UTC, johnxnguyen requested changes
I think I replaced the old lock view tests with the app lock module view tests. I think you can delete the snapshots in the `AppLockViewSnapshotTests/` folder.

Also, please add tests for the event.

2021-02-15 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return "registration.push_access_denied.settings_button.title".localized
I think we should start to scope localized strings to the module so we avoid to use strings from other parts of the app. This is something that I will do for the other strings in the module, but I think it's worth pointing out here to keep it in mind for the future.

2021-02-15 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.swift
> +        case openSettingsTapped
```suggestion
        case openSettingsButtonTapped
```

2021-02-15 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.LockView.swift
>              onReauthRequested?()
Since the name of the button changed, I'd change the names here too.

2021-02-15 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +        }
I would expect something called `onEvent` to be a function. I think a more suitable name would be `buttonEvent` or `buttonAction`.

2021-02-15 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +        }
You could simplify this with:

```swift
switch self {
case .locked(.unavailable):
    return openSettingsTapped
default:
    return .unlockButtonTapped
}
```

2021-02-15 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +        }
Now that you send the event from here, you can remove it from the `setUpViews` method.

2021-02-15 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
> +    }
This is navigation so I would say it's the responsibility of the router. I would add a new action case `presentDeviceSettings`, ask the router to perform it, then have the router call this code.

2021-02-16 08:02 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
> +    }
I would also add the control `UIApplication.shared.canOpenURL`.

2021-02-16 08:03 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.LockView.swift
>              onReauthRequested?()
At this point I would also change the naming of the label `authenticateLabel`

2021-02-16 08:05 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return "registration.push_access_denied.settings_button.title".localized
Shouldn’t we merge SwiftGen? if yes, why don't start using it?

2021-02-16 08:18 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return "registration.push_access_denied.settings_button.title".localized
It is merged, and yes, we should start to use it. But I was thinking that this key should be replaced anyway, it could be included in: https://github.com/wireapp/wire-ios/pull/4939

2021-02-16 17:35 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
> +    }
Done

2021-02-16 17:35 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +        }
Done

2021-02-16 17:36 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +        }
Done

2021-02-16 17:36 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.LockView.swift
>              onReauthRequested?()
Done

2021-02-16 17:44 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return "registration.push_access_denied.settings_button.title".localized
Should I copy this string to the `App lock module section` and create a key like "appLockModule.button.open_settings.title"? And it also means we should rename the current key for the button title.

2021-02-16 18:15 UTC, KaterinaWire commented
> I think I replaced the old lock view tests with the app lock module view tests. I think you can delete the snapshots in the `AppLockViewSnapshotTests/` folder.
> 
> Also, please add tests for the event.

The snapshots were removed and tests added.

2021-02-16 18:20 UTC, KaterinaWire commented
> What happens when the user sets a passcode and comes back to the app? Will the view refresh?

Unfortunately no

2021-02-16 18:49 UTC, johnxnguyen requested changes

2021-02-16 18:49 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return L10n.Localizable.Registration.PushAccessDenied.SettingsButton.title
I think now we should add a new localized string for the settings button, and change the key for the unlock button:

```
"appLockModule.unlockButton.title" = "Unlock";
"appLockModule.goToSettingsButton.title" = "Go to settings";
```

2021-02-16 18:49 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Router.swift
> +        }
If we make this all an extension on `UIApplication`, then we can hide away all details and make it reusable:

```swift
extension UIApplication {

    func openSettings() {
        if let url = URL(string: openSettingsURLString), canOpen(url) {
            open(url, options: [:], completionHandler: nil)
        }
    }

}
```

2021-02-16 18:51 UTC, johnxnguyen commented
> Unfortunately no

So I would expect that when coming back to the app after setting a passcode, the user would be asked to enter the passcode.

2021-02-17 10:02 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Router.swift
> +        }
Make sense 👍

2021-02-17 11:24 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Router.swift
> +        }
Done

2021-02-17 12:42 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return "registration.push_access_denied.settings_button.title".localized
I see two options:

1. Add a new key in the app lock module section (see other comment about this)
2. Or add a new key in a "general" section, and use that key here in app lock, but also wherever the existing key is used.

I would go with option 1. I don't think it's so bad to have some duplicate localized strings since it's low effort to translate them (just duplicate translations).

2021-02-17 13:45 UTC, marcomaddy1982 approved these changes

2021-02-17 14:16 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return L10n.Localizable.Registration.PushAccessDenied.SettingsButton.title
I added those strings

2021-02-17 14:17 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.View.swift
> +                return "registration.push_access_denied.settings_button.title".localized
Added a new key

2021-02-17 19:46 UTC, johnxnguyen requested changes
I would also add a test that the view sends the `applicationDidEnterForeground` event.

2021-02-17 19:46 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
> +
I think it might be better to use `.initiateAuthentication` since that is the same flow that happens when `.viewDidLoad` is processed.

2021-02-18 11:55 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
> +
Done

2021-02-18 11:57 UTC, KaterinaWire commented
@johnxnguyen I added the `isAuthenticationNeeded` property to the Interactor as we discussed this morning.

2021-02-18 12:06 UTC, johnxnguyen requested changes
We should still write a test that the view sends the `applicationWillEnterForeground` event to the presenter.

2021-02-18 12:06 UTC, johnxnguyen commented on Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
> +        XCTAssertNil(session.lock)
I would prefer to avoid adding assertions in the **when**, it seems unnecessary and clutters the test a bit.

2021-02-18 12:06 UTC, johnxnguyen commented on Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
> +        XCTAssertEqual(session.lock, .screen)
I would also avoid assertions here too (and in previous tests). If you want to express that lock is of type screen, then I would explicitly set it in  **given**.

2021-02-18 12:06 UTC, johnxnguyen commented on Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
> +        XCTAssertTrue(waitForGroupsToBeEmpty([sut.dispatchGroup]))
There's no need to wait because we're not doing any async operations.

2021-02-18 12:13 UTC, KaterinaWire commented on Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
> +        XCTAssertNil(session.lock)
Fixed

2021-02-18 12:13 UTC, KaterinaWire commented on Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
> +        XCTAssertEqual(session.lock, .screen)
Fixed

2021-02-18 12:13 UTC, KaterinaWire commented on Wire-iOS Tests/App Lock/Tests/AppLockModuleInteractorTests.swift
> +        XCTAssertTrue(waitForGroupsToBeEmpty([sut.dispatchGroup]))
Fixed

2021-02-18 14:38 UTC, KaterinaWire commented
> We should still write a test that the view sends the `applicationWillEnterForeground` event to the presenter.

@johnxnguyen I added a test

2021-02-18 14:40 UTC, johnxnguyen approved these changes

2021-02-19 07:54 UTC, merged