[Feature] inform users of empty active speakers view
wireapp/wire-ios pull request #4941
Opened 2021-02-16 09:33 UTC by David-Henner

## What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues. (Optional)_

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here. (Optional)_

Needs releases with:

- [ ] GitHub link to the pull request

### Notes

_Specify here any other facts that you think are important for this issue. (Optional)_

### Attachments

_Attachments like images, videos, etc. (Optional)_

2021-02-17 15:12 UTC, johnxnguyen requested changes

2021-02-17 15:12 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
> +        showLoadingView(title: "call.grid.no_active_speakers".localized)
You can now use the type safe localization keys:

```swift
showLoadingView(title: L10n.Localizable.Call.Grid.noActiveSpeakers)
```

2021-02-17 16:37 UTC, billypchan approved these changes

2021-02-18 14:24 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
> +        showLoadingView(title: "call.grid.no_active_speakers".localized)
Right! thanks for the reminder :)

2021-02-18 15:57 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/VideoGridView/VideoGridViewController.swift
> +        showLoadingView(title: "call.grid.no_active_speakers".localized)
done here 866bc9b :)

2021-02-18 19:43 UTC, johnxnguyen approved these changes

2021-02-18 19:53 UTC, merged