[Fix]: Handle gracefully when device runs out of disk space
wireapp/wire-ios pull request #4999
Opened 2021-03-01 10:57 UTC by marcomaddy1982

## What's new in this PR?

### Issues

See the [issue](https://wearezeta.atlassian.net/browse/SQCORE-429)

When there was a problem to load the database in case we run out of disk space (or for any other error), the database was dropped. This means that the user was losing all the previous conversation

### Solutions

Now a screen similar to the `blacklisted` or `jailbroken` is shown but with a different message

### Dependencies

data-model: https://github.com/wireapp/wire-ios-data-model/pull/1144
sync-engince:  https://github.com/wireapp/wire-ios-sync-engine/pull/1411

2021-03-03 06:45 UTC, typfel requested changes
Look like some linters warnings was introduced in AppStateCalculator

2021-03-03 06:45 UTC, typfel commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"databaseloadingfailure.alert.message" = "The database could be loaded.";
```suggestion
"databaseloadingfailure.alert.message" = "The database could not be loaded.";
```

2021-03-03 06:45 UTC, typfel commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"databaseloadingfailure.alert.message" = "The database could be loaded.";
This copy is pending a review?

2021-03-03 09:24 UTC, marcomaddy1982 commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"databaseloadingfailure.alert.message" = "The database could be loaded.";
Yes, this is just temp copy. Better if I mention on the ticket description.

2021-03-03 10:30 UTC, KaterinaWire commented
@marcomaddy1982 Everything is fine for me, I don't have comments. Could you notify when the copies will be approved by the design team?

2021-03-03 10:32 UTC, KaterinaWire approved these changes

2021-03-05 12:36 UTC, marcomaddy1982 commented
> Look like some linters warnings was introduced in AppStateCalculator

Solved

2021-03-05 13:34 UTC, typfel commented on Wire-iOS/Sources/UserInterface/BlockerViewController.swift
> +            title: "databaseloadingfailure.alert.title".localized,
What about using the type safe localization John introduced in https://github.com/wireapp/wire-ios/pull/4911

2021-03-05 18:19 UTC, marcomaddy1982 commented on Wire-iOS/Sources/UserInterface/BlockerViewController.swift
> +            title: "databaseloadingfailure.alert.title".localized,
Done

2021-03-09 08:17 UTC, typfel approved these changes

2021-03-11 10:32 UTC, typfel approved these changes

2021-03-18 08:52 UTC, KaterinaWire approved these changes

2021-03-18 14:52 UTC, merged