[Fix] Overlapping app state transitions
wireapp/wire-ios pull request #5028
Opened 2021-03-22 15:05 UTC by johnxnguyen

## What's new in this PR?

### Issues

We have been experiencing several crashes lately when the trying to access the `SelfUser.current`, typically from the conversation list or in the conversation content.

### Causes

`SelfUser.current` intentionally crashes when `SelfUser.provider == nil`. The self user provider is configured during the app state transition:

- The provider is set when `applicationWillTransition(to: .authenticated)` is called, and
- The provider is reset when `applicationDidTransition(to: appState)`, where `appState != .authenticated`.

The problem however is that we can repeatedly call these methods in any order, for example:

```swift
// The self user isn't set yet, so SelfUser.current will crash.
applicationWillTransition(to: .migrating)

// This will set the provider, SelfUser.current won't crash.
applicationWillTransition(to: .authenticated)

// This will reset the provider, SelfUser.current will crash
applicationDidTransition(to: .migrating)

// Here we typically cause a load of the conversation list, which will
// result in an eventual call to SelfUser.current. But it's not set,
// so it will crash.
applicationDidTransition(to: .authenticated)
```

### Solutions

Consider transitions (delimited by `applicationWillTransition` and `applicationDidTransition`) as atomic, meaning that we only begin a transition once the previous one (if any) has completed.

### Note

This is just a draft implementation, I'm looking for feedback whether there is a cleaner/simpler way to achieve this.

2021-03-22 15:06 UTC, johnxnguyen commented on Wire-iOS/Sources/AppRootRouter.swift
> -
This wasn't being used anywhere.

2021-03-22 15:07 UTC, johnxnguyen commented on Wire-iOS/Sources/AppRootRouter.swift
>      private func transition(to appState: AppState, completion: @escaping () -> Void) {
I want to make this inaccessible so that we avoid to call it directly rather than through `enqueueTransition(to:completion)`

2021-03-22 15:37 UTC, marcomaddy1982 commented
The approach is correct in my opinion> Now i don't remember in detail but I guess the idea you have implemented is something I have tried to implement in the in the `RootViewController`. But what i have done is more for the animation transition from a state to another. See the method:

```swift
private func transition(from fromViewController: UIViewController,
                            to toViewController: UIViewController,
                            animated: Bool = false,
                            completion: (() -> Void)?)
```

At this point it seems that it was not enough.

2021-03-22 17:15 UTC, marcomaddy1982 approved these changes

2021-03-23 06:51 UTC, typfel requested changes

2021-03-23 06:51 UTC, typfel commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
So it's very important that we always call  `applicationWillTransition(to: appState)` followed by `applicationDidTransition(to: appState)` now, since otherwise the dispatch group will never be unlocked. Looking at the switch it seems like we don't call `applicationDidTransition(to: appState)` in the `.locked` case.

It's quite easy to introduce such an error so how can we structure the code to make such errors impossible?

2021-03-23 06:51 UTC, typfel commented on Wire-iOS/Sources/AppRootRouter.swift
>      private func transition(to appState: AppState, completion: @escaping () -> Void) {
The options I can I think of:
1. Move the state transition methods to a separate file
1. Move the state transition methods to separate extension inside this file 
1. Merge `transition(to:completion:)` into `enqueueTransition(to:completion)`

Maybe option 2 is nicer since you could then at least still keep the `appStateTransitionGroup` and `appStateTransitionQueue` `fileprivate`.

2021-03-23 06:51 UTC, typfel commented on Wire-iOS/Sources/AppRootRouter.swift
> -
Was used by AppLock previously I think.

2021-03-23 07:30 UTC, johnxnguyen commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
Good catch, I didn't noticed that we weren't always calling the completion. The completion needs to be passed when we set the view controller, and I see that we duplicate this code for every switch case in separate methods.
One thing we could do is to extract the code that creates view controllers out to another method, so then we would only have a single place where we call 

 ```swift
rootViewController.set(childViewController: childViewController, completion: completion)
```

This would likely reduce the size of `transition(to:completion:)` so much so that it would be fine to merge it into the `enqueueTransition(to:completion:)` method body.

2021-03-23 08:26 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppRootRouter.swift
>      private func transition(to appState: AppState, completion: @escaping () -> Void) {
I like more then the other the solution number 2  too.

2021-03-23 09:19 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
@johnxnguyen @typfel: IMHO here I would just add the `completion` also to the `showAppLock`  method. The reason is because really verbose to extract the code that creates view controllers out to another method. Moreover there is a special case in the `showUnauthenticatedFlow` where after `set(childViewController: childViewController, completion: completion)  ` we do another operation:

```swift
rootViewController.set(childViewController: navigationController,
                               completion: completion)

presentAlertForDeletedAccountIfNeeded(error)
```
and I guess this particular scenario complicate a bit the solution you wanna to adopt in the comment.

2021-03-23 09:39 UTC, typfel commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
@marcomaddy1982 I think John idea solves the problem in simple way. Only adding a the completion block to to the `showAppLock` method still makes easy to re-introduce this error the next time someone adds a new  app state.

Couldn't we remove the special case for `showUnauthenticatedFlow` by moving the `presentAlertForDeletedAccountIfNeeded(error)` to `applicationDidTransition(to appState: AppState)`.

2021-03-23 09:40 UTC, johnxnguyen commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
I found that indeed it's not so easy to extract out view controller creation, specifically for the unauthenticated and authenticated states. There's a bit of decoupling needed and consideration about how to handle cases where we return early (i.e abort a transition so to speak).

One thing though that it's not enough to simply add the completion for the `locked` state. You'd also need to add it to any `guard` that returns early, as I mentioned above.

2021-03-23 09:46 UTC, typfel commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
Ok, it's more complicated. Then maybe I agree to first do the fix this with the current system and do the re-factoring separately since the code freeze is today.

2021-03-23 09:46 UTC, johnxnguyen commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
I agree, but I would also say that refactoring should take a high priority for the subsequent release.

2021-03-23 10:01 UTC, marcomaddy1982 commented on Wire-iOS/Sources/AppRootRouter.swift
> +        applicationWillTransition(to: appState)
the suggestion made by @johnxnguyen is now pushed.

2021-03-23 10:03 UTC, marcomaddy1982 commented
@johnxnguyen  I added you as assigner anyway if you approve the changes I have made add a comment cause since you created you can not approve it.

2021-03-23 10:07 UTC, typfel approved these changes

2021-03-23 10:07 UTC, johnxnguyen reviewed
@marcomaddy1982  I approve 👍🏻

2021-03-23 10:18 UTC, merged