[Fix] pinch-to-zoom should not zoom out nor pan un-zoomed
wireapp/wire-ios pull request #5044
Opened 2021-04-01 16:46 UTC by David-Henner

## What's new in this PR?

### Issues

Pinch-to-zoom should not allow:
- Zooming out. Only scaling the view to identity and upwards should be allowed.
- Panning when the view is not zoomed.

### Causes

--

### Solutions

Updated gesture handlers logic to conform to the rules.

2021-04-06 07:09 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Calling/VideoGridView/Video Previews/VideoPreviewView.swift
> +
to standardize the folder name, we should not have a space in the path ` Wire-iOS/Sources/UserInterface/Calling/VideoGridView/Video Previews/VideoPreviewView.swift `

2021-04-06 07:10 UTC, billypchan requested changes
remove space in `Video Previews` folder

` Wire-iOS/Sources/UserInterface/Calling/VideoGridView/Video Previews/VideoPreviewView.swift `

2021-04-06 09:03 UTC, marcomaddy1982 approved these changes

2021-04-07 06:57 UTC, billypchan approved these changes

2021-04-07 09:17 UTC, merged