[Fix] EAR users must explicitly unlock app
wireapp/wire-ios pull request #5054
Opened 2021-04-14 12:00 UTC by KaterinaWire

## What's new in this PR?

### Issues
If the App lock is shown then the user must explicitly tap the button to authenticate with `touchID` or `faceID`.
This's especially sensitive for EAR users as they should always unlock Wire after switching to another app or moving Wire to the foreground. 

### Causes
It was a temporary fix for an issue introduced in iOS 14.  
You can find the issue description here: wireapp/wire-ios/pull/4983

### Solutions
Since the `viewDidAppear` method is called when the application is in the background, and we would like to avoid this, check the state of the application at this point. This will prevent re-trigger the authentication when Wire is in the background.

### Notes

https://wearezeta.atlassian.net/browse/SQSERVICES-302

2021-04-14 12:34 UTC, johnxnguyen requested changes
I'm glad to know that the solution is much simpler than I thought! However I have one issue: 

by moving logic from the interactor to the view, we're undermining the purpose of Viper to remove all logic from the view. I would like to see the solution you have take place only within the interactor and presenter. 

One way you can achieve this is to add a new request `initiateAuthenticationIfAppIsActive`, which you would send to the interactor when the presenter handles the `viewDidAppear` event. Then you can keep the application state logic in the `executeRequest(_ request: AppLockModule.Request)` method of the interactor.

2021-04-14 16:16 UTC, KaterinaWire commented
> I'm glad to know that the solution is much simpler than I thought! However I have one issue:
> 
> by moving logic from the interactor to the view, we're undermining the purpose of Viper to remove all logic from the view. I would like to see the solution you have take place only within the interactor and presenter.
> 
> One way you can achieve this is to add a new request `initiateAuthenticationIfAppIsActive`, which you would send to the interactor when the presenter handles the `viewDidAppear` event. Then you can keep the application state logic in the `executeRequest(_ request: AppLockModule.Request)` method of the interactor.

I agree with you, having this logic in the view is not the best approach. As you suggested, I added a new request `initiateAuthenticationIfAppIsActive`. But I'm not sure about interactor now. 
We also have to check `isAuthenticationNeeded`, `needsToCreateCustomPasscode` for the new request, and it seems like a duplicate code.

2021-04-15 06:20 UTC, johnxnguyen commented
>  But I'm not sure about interactor now.
We also have to check isAuthenticationNeeded, needsToCreateCustomPasscode for the new request, and it seems like a duplicate code.

@KaterinaNikolaenko here's an (untested) idea to avoid duplication:

```swift
enum Request {
  // Modify the existing case.
  case initiateAuthentication(requireActiveApp: Bool)
  ...
}


func handle(request: Request) {
  switch request {
  // Check for this case first and return early if needed.
  case .initiateAuthentication(requireActiveApp: true) where appState != .active:
    return

  // Otherwise handle the request as we did previously.
  case .initiateAuthentication where !isAuthenticationNeeded:
    ...
  }
}


```

2021-04-15 09:54 UTC, KaterinaWire commented
> > But I'm not sure about interactor now.
> > We also have to check isAuthenticationNeeded, needsToCreateCustomPasscode for the new request, and it seems like a duplicate code.
> 
> @KaterinaNikolaenko here's an (untested) idea to avoid duplication:
> 
> ```swift
> enum Request {
>   // Modify the existing case.
>   case initiateAuthentication(requireActiveApp: Bool)
>   ...
> }
> 
> 
> func handle(request: Request) {
>   switch request {
>   // Check for this case first and return early if needed.
>   case .initiateAuthentication(requireActiveApp: true) where appState != .active:
>     return
> 
>   // Otherwise handle the request as we did previously.
>   case .initiateAuthentication where !isAuthenticationNeeded:
>     ...
>   }
> }
> ```

I've made a manual testing and it seems to work.

2021-04-15 10:01 UTC, johnxnguyen approved these changes

2021-04-15 10:44 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/App Lock/AppLockModule.Presenter.swift
> +        case .viewDidAppear, .unlockButtonTapped:
Done

2021-04-15 12:00 UTC, typfel approved these changes

2021-04-15 14:32 UTC, merged