[Feature] Show LH system message
wireapp/wire-ios pull request #5096
Opened 2021-05-17 08:17 UTC by KaterinaWire

## What's new in this PR?
If users don't want/support LH, they will be kicked-out from group conversations because there is a user under LH in that group, and a system message will be shown.
There is an additional field `”reason”: “legalhold-policy-conflict”` in events `"conversation.member-leave"` data, which should initiate a new system message.

Needs releases with:
- [ wireapp/wire-ios-transport/pull/182 ]
- [ wireapp/wire-ios-data-model/pull/1158 ]

### Notes
https://wearezeta.atlassian.net/browse/SQSERVICES-442

### Attachments
https://zpl.io/a7mLl18
or
zpl://screen?pid=6053348d8def481ae6cb3aa7&sid=606f34344a6925513d48786d

2021-05-17 12:41 UTC, johnxnguyen requested changes
It would be nice to have a snapshot test for the new system messages.

2021-05-17 12:41 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"content.system.conversation.you.removed.legalhold" = "%@ were removed from this group, becausethere are users with Legal Hold.";
```suggestion
"content.system.conversation.you.removed.legalhold" = "%@ were removed from this group, because there are users with Legal Hold.";
```

2021-05-17 12:41 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"content.system.conversation.you.removed.legalhold" = "%@ were removed from this group, becausethere are users with Legal Hold.";
Hmm... I'm wondering why we need a placeholder for the "You" part... do you know?

2021-05-17 12:41 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
> +        }
A guard may be easier to read here:

```swift
guard case .removed(reason: .legalHoldPolicyConflict) = message.actionType else { return nil }
var result = ...
return result
```

2021-05-17 14:20 UTC, KaterinaWire commented
> It would be nice to have a snapshot test for the new system messages.

I haven't checked that snapshots were not pushed.
Done

2021-05-17 14:32 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
> +        }
Fixed

2021-05-17 14:44 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"content.system.conversation.you.removed.legalhold" = "%@ were removed from this group, becausethere are users with Legal Hold.";
Because when someone removed me from a conversation, I can see the system message in that conversation "**Usernamer** removed you". So if I'm removed from the conversation due to a legal hold policy conflict, I will see a system message "You were removed from this group..."
At least that's my opinion on this placeholder.

2021-05-17 15:36 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"content.system.conversation.you.removed.legalhold" = "%@ were removed from this group, because there are users with Legal Hold.";
Just noticed the comma, for me it feels strange. I don't know if this copy has been approved yet... let me check and get back to you.

2021-05-21 09:04 UTC, typfel approved these changes

2021-05-24 07:05 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCellViewModel.swift
> +
So if the self user is in a list of names, we only mention the self user? Why? It seems like it makes things more complicated.

2021-05-24 07:05 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCellViewModel.swift
> +        if case .removed(reason: .legalHoldPolicyConflict) = action, sortedUsersWithoutSelf.count == 0 { return "started" }
Could you elaborate what this line is for?

2021-05-24 07:05 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
> +            let isSelfUserIncluded = isSelfIncludedInUsers || names.names.count > 1
How is it that if there is more than one name then the self user is included?

2021-05-24 07:05 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
> +            return result += " " + moreInfo
The copy states that the like should say "Learn more".

2021-05-24 07:05 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
> +            return result += " " + moreInfo
I know that your following the existing implementation here in regards to constructing the attributed string, but it might make sense to use the markdown technique here too because we want to do it anyway.

2021-05-25 15:50 UTC, johnxnguyen approved these changes

2021-05-25 16:02 UTC, KaterinaWire commented on Wire-iOS Tests/ConversationMessageCell/ConversationSystemMessageTests.swift
> +//    }
Removed

2021-05-25 16:03 UTC, KaterinaWire commented on Wire-iOS Tests/PeoplePickerControllerTests/people-01.json
> +    {
Removed changes

2021-05-25 16:04 UTC, KaterinaWire commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"content.system.conversation.other.removed.legalhold" = "%@ was removed from this conversation because legal hold has been activated.";
There is a case for plural.

2021-05-25 16:05 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCellViewModel.swift
> +
Yes it makes things more complicated, but it was discussed with Eva

2021-05-25 16:05 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsCellViewModel.swift
> +        if case .removed(reason: .legalHoldPolicyConflict) = action, sortedUsersWithoutSelf.count == 0 { return "started" }
I added a comment here

2021-05-25 16:06 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ParticipantsStringFormatter.swift
> +            let isSelfUserIncluded = isSelfIncludedInUsers || names.names.count > 1
This part was changed and added comments

2021-05-25 20:42 UTC, merged