[Feature] Showing an alert when new connections can't be added
wireapp/wire-ios pull request #5103
Opened 2021-05-24 18:39 UTC by KaterinaWire

## What's new in this PR?

When we receive `error code 412` in response to posting a new connection, an alert will be shown with an error message.

Needs releases with:

- [ wireapp/wire-ios-sync-engine/pull/1441 ] 

### Notes
https://wearezeta.atlassian.net/browse/SQSERVICES-445

2021-05-24 19:39 UTC, johnxnguyen approved these changes

2021-05-24 19:39 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
> +                                                alertAction: .ok(style: .cancel))
```suggestion
        typealias ErrorString = L10n.Localizable.Error

        let alertController = UIAlertController(title: ErrorString.Conversation.title,
                                                message: ErrorString.Connection.missingLegalholdConsent,
                                                alertAction: .ok(style: .cancel))
```

2021-05-25 07:17 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(showError), name: ZMConnectionLimitNotification.missingLegalHoldConsent, object: nil)
Does `ZMConnectionLimitNotification` need updating or renaming?

2021-05-25 07:27 UTC, typfel commented
Note that it's also possible to send a connection request by navigating to a user from  the conversations details screen.

2021-05-25 07:28 UTC, typfel requested changes

2021-05-25 07:28 UTC, typfel commented on Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
> +    func showError() {
A more detailed methods name since it's not clear from the context which kind we'll show.

2021-05-25 07:28 UTC, typfel commented on Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(showError), name: ZMConnectionLimitNotification.missingLegalHoldConsent, object: nil)
You added a an `addObserver` method in SE which you don't use here.

2021-05-25 13:24 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchResultsViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(showError), name: ZMConnectionLimitNotification.missingLegalHoldConsent, object: nil)
I guess I do not need addObserver method in `SE`, I can remove it there. @typfel  What do you think?

2021-05-25 13:29 UTC, KaterinaWire commented
> Note that it's also possible to send a connection request by navigating to a user from the conversations details screen.

@typfel Would it be a good solution to add the same observer to the  conversations details screen? I don't want to add it to the Profile screen because the user can close it before the BE response.

2021-05-25 13:31 UTC, typfel commented
> > Note that it's also possible to send a connection request by navigating to a user from the conversations details screen.
> 
> @typfel Would it be a good solution to add the same observer to the conversations details screen? I don't want to add it to the Profile screen because the user can close it before the BE response.

Yes, I think that would work. It's not 100% foolproof since the conversation details can also be closed.

2021-05-25 14:09 UTC, KaterinaWire commented
> > > Note that it's also possible to send a connection request by navigating to a user from the conversations details screen.
> > 
> > 
> > @typfel Would it be a good solution to add the same observer to the conversations details screen? I don't want to add it to the Profile screen because the user can close it before the BE response.
> 
> Yes, I think that would work. It's not 100% foolproof since the conversation details can also be closed.

@typfel I added this observer to the Profile screen. Anyway, it's a solution for this release. In the future, the connect button will be hidden and the user will have a chance to see a reason why it's not possible to make connect request  before sending the request.

2021-05-25 19:38 UTC, merged