[Fix] Crash when leaving large call
wireapp/wire-ios pull request #5185
Opened 2021-07-26 16:40 UTC by David-Henner

## What's new in this PR?

### Issues

When hanging up a large conference call from the last page of the call grid, the app crashes

### Causes

Upon hanging up the call, the call configuration is updated and propagated to `CallGridViewController`.
Consequently, `requestVideoStreamsIfNeeded(forPage:Int)` is called. This method slices the `dataSource` array containing all streams by using the range of indexes of the elements presumed to be in the given page.

The range of indexes is calculated this way:
```
let startIndex = page * gridView.maxItemsPerPage
var endIndex = startIndex + gridView.maxItemsPerPage
endIndex = min(endIndex, dataSource.count)
```

Using `min(endIndex, dataSource.count)` ensures `endIndex` won't be out of `dataSource` bounds.

However, there is a risk for `endIndex` to be lower than `startIndex` (which is what caused the crash in this case) or for `startIndex` to be out of `dataSource`'s bounds

### Solutions

`guard` against `startIndex` being out of bounds and against `endIndex` being lower than `startIndex`

2021-07-26 21:21 UTC, KaterinaWire approved these changes

2021-07-27 14:10 UTC, billypchan commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
> +              endIndex > startIndex
We can simpler the guard like `dataSource.indices.contains(startIndex)`

2021-07-27 14:13 UTC, billypchan requested changes
clean up checker

2021-07-27 15:14 UTC, billypchan approved these changes

2021-07-28 08:47 UTC, merged