AVS xcframework
wireapp/wire-ios pull request #5196
Opened 2021-08-04 09:30 UTC by billypchan

## What's new in this PR?

refactor `download-avs.sh` for AVS in XCFramework format.

2021-08-10 13:21 UTC, typfel requested changes

2021-08-10 13:21 UTC, typfel commented on Wire-iOS.xcodeproj/project.pbxproj
> +				"ARCHS[sdk=iphoneos*]" = arm64;
Shouldn't this be defined in the xcconfig?

2021-08-10 13:21 UTC, typfel commented on Wire-iOS.xcodeproj/project.pbxproj
> +				"ARCHS[sdk=iphoneos*]" = arm64;
Same thing applies for all other changes in the .pbxproj

2021-08-10 14:36 UTC, billypchan commented on Wire-iOS.xcodeproj/project.pbxproj
> +				"ARCHS[sdk=iphoneos*]" = arm64;
This configs are needed since this version of AVS does not have armv7 binary, will be removed after release train is merged.

2021-08-11 08:56 UTC, typfel commented on Wire-iOS/Wire-Info.plist
> +	<dict>
Unrelated whitespace changes.

2021-08-11 08:56 UTC, typfel approved these changes

2021-08-11 08:59 UTC, billypchan commented on Wire-iOS/Wire-Info.plist
> +	</array>
```suggestion
<array/>
```

2021-08-11 09:01 UTC, johnxnguyen approved these changes

2021-08-11 09:01 UTC, merged