[Feature] Conference calling feature flag alerts
wireapp/wire-ios pull request #5227
Opened 2021-08-24 23:41 UTC by KaterinaWire

## What's new in this PR?
Update alerts according to the new design.

### Attachments
https://zpl.io/bJLvLv3

2021-08-25 06:23 UTC, johnxnguyen requested changes
Please remove private api usage in the alerts.

2021-08-25 06:23 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        alert.setValue(createMessageView(configuration), forKey: "contentViewController")
This looks like private api. Are you trying to add the url to the alert? If so, we have to do it with a button.

2021-08-25 06:23 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        alert.setValue(createMessageView(configuration), forKey: "contentViewController")
Same here.

2021-08-25 06:23 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +            presentConferenceCallingAvailableAlert()
I guess this should be under `.conferenceCallingIsAvailableAlert`.

2021-08-25 06:23 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        presentConferenceCallingUnavailableAlertForAdmin()
I think it would be more readable to do only unwrap in the guard and more the rest of the conditions outside:

```swift
guard let selfUser = ZMUser.selfUser() else { return }

if selfUser.teamRole.isOne(of: .admin, .owner) {
  // present this
} else {
  // present that
}
```

2021-08-25 07:50 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +            presentConferenceCallingAvailableAlert()
Yes, and this method is under `.conferenceCallingIsAvailableAlert`. I added a comment on the line above to ask Anette about a popup when a user is downgraded to a free plan.

2021-08-25 08:00 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +            presentConferenceCallingAvailableAlert()
Sorry, I mean to say, this method call `presentConferenceCallingAvailableAlert()` looks like it should be under the `conferenceCallingIsAvailable` case, instead of the `conferenceCallingIsUnavailable` case.

I think you need to switch the todo comment with the present method.

2021-08-30 05:34 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        alert.setValue(createMessageView(configuration), forKey: "contentViewController")
Removed

2021-08-30 05:34 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        alert.setValue(createMessageView(configuration), forKey: "contentViewController")
Removed

2021-08-30 05:34 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        presentConferenceCallingUnavailableAlertForAdmin()
Done

2021-08-30 05:35 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +            presentConferenceCallingAvailableAlert()
Changed.
We now only have one  `.conferenceCallingIsUnavailable` case.

2021-08-30 06:28 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
I'm commenting here, but I'm referring to a few lines above: these are some old notes so you can delete them.

2021-08-30 06:28 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        }))
One way to make these alert methods more readable is to refactor the action code into private extensions, something like:

```swift
private extension UIAlertAction {

  static func link(title: String, url: URL, presenter: UIViewController) -> Self {
    return .init(title: title, style: .default) { _ in 
      let browserViewController = BrowserViewController(url: url)
      presenter.present(browserViewController, animated: true
    }
  }

}
```

2021-08-30 09:31 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
I removed the comments above

2021-08-30 09:32 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        }))
Done

2021-08-30 11:13 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        }
Probably best to play it safe and capture the presenter weakly, to avoid a possible retain cycle:

```swift
        return .init(title: title, style: .default) { [weak presenter] _ in
            let browserViewController = BrowserViewController(url: url)
            presenter?.present(browserViewController, animated: true)
        }
```

2021-08-30 13:07 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/MainController/ZClientViewController+ConferenceCallingAvailabilty.swift
> +        }
Fixed

2021-08-30 13:08 UTC, johnxnguyen approved these changes

2021-08-31 05:18 UTC, typfel approved these changes

2021-08-31 12:31 UTC, merged