Replace localisable string
wireapp/wire-ios pull request #5238
Opened 2021-09-02 13:11 UTC by KaterinaWire

## What's new in this PR?

According to [design spec](https://zpl.io/aMX9v3N), we should rename the `Pictures` section to `Images`.
We only use this string for the title on the search screen, so it is safe to simply rename it.

2021-09-03 14:09 UTC, billypchan approved these changes

2021-09-03 14:09 UTC, billypchan requested changes
Seems snapshots needs update after this change.

2021-09-03 15:33 UTC, KaterinaWire commented
> Seems snapshots needs update after this change.

Updated

2021-09-06 11:19 UTC, billypchan approved these changes

2021-09-06 11:40 UTC, David-Henner approved these changes

2021-09-06 11:44 UTC, merged