Fix: Empty markdown produces invisible messages
wireapp/wire-ios pull request #5379
Opened 2021-11-10 14:45 UTC by agisilaos

## What's new in this PR?

### Issues

It's possible to create invisible messages by sending empty markdown such as: {{# }}, {{> }} and ****. These messages create an empty heading, block quote and bold text. Additionally, if the user receives these messages, they will see nothing either.

### Solutions
A possible solution is to show the raw text if the markdown would render it invisible. So it checks if `attrStr.string` contains any of the symbols in the enum and based on that and the value of the text we return either 

`result = NSMutableAttributedString(string: text)`

or

result = NSMutableAttributedString(string: attrString)

--

Added some unit tests to cover the cases as well. 

### Notes

https://wearezeta.atlassian.net/browse/SQSERVICES-293

2021-11-12 08:38 UTC, typfel requested changes

2021-11-12 08:38 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
> +        case bracket = "{ }\n"
Why do we need to these two cases? Doesn't rendered markdown and the original text render to the same string?

2021-11-12 08:38 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
>          if let attrStr = try? down.toAttributedString(using: style) {
I think we can simplify this by removing the inner if statement.

something like:

```
if let attrStr = try? down.toAttributedString(using: style), !attrStr.isEmptyMarkdown {
     result = NSMutableAttributedString(attributedString: attrStr)
} else {
     result = NSMutableAttributedString(string: text)
}
```

2021-11-12 08:38 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
> +            if symbols.contains(attrStr.string), !symbols.contains(text) {
Can you explain what `!symbols.contains(text)` solves/prevents?

2021-11-12 08:38 UTC, typfel commented on Wire-iOS.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
You should revert this.

2021-11-12 08:38 UTC, typfel commented on Wire-iOS.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
You should revert this.

2021-11-12 08:52 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
> +        case bracket = "{ }\n"
The newLineWithStar method is needed when user just types `**` and the bracket when user types { }

> Doesn't rendered markdown and the original text render to the same string?

Unfortunately it doesn't work like that, without these two cases then many symbols are invisible when sending a message.

2021-11-12 09:00 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
>          if let attrStr = try? down.toAttributedString(using: style) {
Which are you referring to as inner if statement? The one related to the symbols check?

2021-11-12 09:29 UTC, billypchan commented
I would recommend make a patch or extension to `Down` to handle this issue (@johnxnguyen)

2021-11-12 09:31 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
>          if let attrStr = try? down.toAttributedString(using: style) {
I don't see how we can simplify the if statement in this case since we need to check for the symbols etc.

2021-11-12 09:49 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
> +            if symbols.contains(attrStr.string), !symbols.contains(text) {
Nothing really. Interesting catch! I left it there based on the thinking of my previous implementation and I thought it was still needed.

2021-11-12 09:58 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
> +            if symbols.contains(attrStr.string), !symbols.contains(text) {
Nothing really, I left it there based on the previous implementation I had in mind but it is not needed anymore.

2021-11-15 09:18 UTC, typfel commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
>          if let attrStr = try? down.toAttributedString(using: style) {
In my example above the symbols check would be done inside the new computed property `isEmptyMarkdown`

2021-11-15 10:57 UTC, johnxnguyen reviewed
I think it's worth considering adding this functionality to the Down framework. There you would have access to the syntax tree, which means to you avoid relying on string matching and instead query the tree nodes, and subsequently adjust the rendering output there. This change in behavior could be put behind a configurable setting.

2021-11-16 13:09 UTC, johnxnguyen reviewed
If the aim is to avoid displaying markdown messages that contain no visible characters, and instead falling back to the raw text, then why can't we simply check for an empty attributed string?

```swift
static func markdown(from text: String, style: DownStyle) -> NSMutableAttributedString {
        let down = Down(markdownString: text)
        let result: NSMutableAttributedString

        if let attrStr = try? down.toAttributedString(using: style) {
            result = .init(attributedString: attrStr)
        } else {
            result = NSMutableAttributedString(string: text)
        }

        if result.string.last == "\n" {
            result.deleteCharacters(in: NSMakeRange(result.length - 1, 1))
        }

        guard !result.string.isEmpty else {
            return .init(string: text)
        }

        return result
    }
```

2021-11-16 13:41 UTC, agisilaos commented on Wire-iOS Tests/NSAttributedString+DownTests.swift
> +        XCTAssertEqual(sut, NSMutableAttributedString(string: plainTextSymbol))
@johnxnguyen Can you elaborate a bit more on that? After messing around and trying to understand what's the best way to test `NSMutableAttributedString`. I found out the the process above is the most accurate.

2021-11-16 13:42 UTC, agisilaos commented
@johnxnguyen Regarding your comment: (Since I can't reply directly)

> I don't quite understand how { }\n produces empty markdown, since I don't believe { } corresponds to any markdown syntax (at least that I'm aware of.

For some reason that's the value of the `attrString.string` when user types { }. That's why it's been added as a case. So as a result when you type { } it produces an invisible message.

2021-11-16 14:05 UTC, johnxnguyen commented
> For some reason that's the value of the attrString.string when user types { }.

@agisilaos Down may be adding a newline at the end of the string after rendering the document node, which is probably why we're deleting trailing newline characters. So if you type `{ }` it would produce `{ }\n`. But I still don't see how that produces an invisible message, you still see `{ }` (at least I do).

2021-11-16 14:06 UTC, johnxnguyen commented on Wire-iOS Tests/NSAttributedString+DownTests.swift
> +        XCTAssertEqual(sut, NSMutableAttributedString(string: plainTextSymbol))
What exactly do we want to test? The string content and the styling? Or just the string content?

2021-11-16 14:07 UTC, agisilaos commented on Wire-iOS Tests/NSAttributedString+DownTests.swift
> +        XCTAssertEqual(sut, NSMutableAttributedString(string: plainTextSymbol))
content I guess since we're talking about raw output.

2021-11-16 14:16 UTC, johnxnguyen commented on Wire-iOS Tests/NSAttributedString+DownTests.swift
> +        XCTAssertEqual(sut, NSMutableAttributedString(string: plainTextSymbol))
Ok, in that case equating the attributed string might lead to unexpected test results because the styling would also be considered.

2021-11-16 14:27 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/Utility/NSAttributedString+Down.swift
> +            if symbols.contains(attrStr.string), !symbols.contains(text) {
After John's comments we simplified it a lot more: 8dfc769

2021-11-16 14:34 UTC, johnxnguyen requested changes

2021-11-16 14:34 UTC, johnxnguyen commented on Wire-iOS Tests/NSAttributedString+DownTests.swift
> +        XCTAssertEqual(sut.string, plainTextSymbol)
I don't think you need this test at all, since (I don't believe) it relates to any markdown.

2021-11-18 07:06 UTC, johnxnguyen approved these changes

2021-11-18 09:12 UTC, typfel requested changes

2021-11-18 09:12 UTC, typfel commented on Wire-iOS.xcodeproj/project.pbxproj
> -		A961465F273C0B8D00986596 /* SearchGroupSelectorSnapshotTests.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SearchGroupSelectorSnapshotTests.swift; sourceTree = "<
Removing `SearchGroupSelectorSnapshotTests` from the project needs to be reverted?

2021-11-18 10:32 UTC, typfel approved these changes

2021-11-18 13:33 UTC, merged