refactor: Analytics Events to work with the new mechanism
wireapp/wire-ios pull request #5424
Opened 2021-11-25 15:50 UTC by agisilaos

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

I continue the work @johnxnguyen started to unify and simplify the approach we do the analytics work. With this PR I transition the following events to work with the new mechanism:

- `app.open`
- `calling.initiated_call`
- `calling.joined_call`
- `calling.established_call`
- `e2ee.failed_message_decryption`

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2021-11-25 15:53 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+Guests.swift
We need to think of a new name for this file since `guestAttributes` has been deleted and not being used. Or to delete it all together when we make sure the code here isn't being used anywhere else.

2021-11-25 16:00 UTC, johnxnguyen requested changes
Nice work, just had a few comments.

2021-11-26 08:45 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.joinedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
In line `94` outgoing is set to false.So in line `101`, it should be set to `.incoming`.

2021-11-26 12:09 UTC, David-Henner commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.joinedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
I agree. Call direction should be `incoming`

2021-11-26 12:11 UTC, David-Henner commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.establishedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
It can be either way. it means that the data channel is established between the participants, regardless of who initiated the call.

2021-11-26 12:36 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.establishedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
So in this case the direction should be outgoing correct? @David-Henner

2021-11-26 17:18 UTC, KaterinaWire approved these changes

2021-11-26 20:24 UTC, David-Henner commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.establishedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
No. In this case there is no direction to report. The direction should be reported earlier either when we receive an incoming call, or when we start an outgoing call.

2021-11-29 14:26 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.establishedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
It makes sense that there's no direction here. @agisilaos do we report the direction when answering or starting a call?

2021-11-29 14:28 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.establishedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
Ah I see that we do report the direction when joining a call. I guess in the case that we start the call, it's also implicit that the direction is outgoing. Then let's remove the direction for this case.

2021-11-29 14:29 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                Analytics.shared.tagEvent(.establishedCall(asVideoCall: video, callDirection: .outgoing, in: conversation))
@johnxnguyen From what we discussed this AM I'm planning to remove `callDirection` from the establishedCall event.  Thank you so much @David-Henner for your input!

2021-11-29 14:45 UTC, agisilaos commented
@johnxnguyen I think we're good to go for a final review! Everything is in place.

2021-11-30 07:15 UTC, johnxnguyen approved these changes

2021-11-30 07:15 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
> +    }
Does this need to be deleted?

2021-11-30 08:19 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
> +    }
Nope, this is for the `.joinedCall` Event. I removed the direction only in the `.establishedCall`

2021-11-30 08:19 UTC, merged