chore: merge 3.93 release branch
wireapp/wire-ios pull request #5436
Opened 2021-11-30 11:30 UTC by billypchan

Merge the changes from release branch. (Xcode 12.4 changes are not included.)

2021-11-30 11:34 UTC, billypchan commented on Cartfile.resolved
> +
```suggestion
```

2021-11-30 11:40 UTC, KaterinaWire approved these changes

2021-12-02 10:40 UTC, typfel requested changes

2021-12-02 10:40 UTC, typfel commented on setup.sh
> +[[ ${CARTHAGE_VERSION[0]} -gt 0 || ${CARTHAGE_VERSION[1]} -ge 38 ]] || die "Carthage should be at least version 0.36"
```suggestion
[[ ${CARTHAGE_VERSION[0]} -gt 0 || ${CARTHAGE_VERSION[1]} -ge 38 ]] || die "Carthage should be at least version 0.38"
```

2021-12-02 13:05 UTC, typfel approved these changes

2021-12-02 13:05 UTC, merged