refactor: `CallEnded` event to work with the new analytics event
wireapp/wire-ios pull request #5438
Opened 2021-11-30 16:12 UTC by agisilaos

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

This is the last big refactor for a major analytics event to make it work with the new analytics mechanism. @johnxnguyen I will leave some comments for you.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2021-11-30 16:15 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            Analytics.shared.tagEvent(.endedCall(asVideoCall: video, callDirection: .outgoing, callDuration: duration, callParticipants: participants, videoEnabled: toggleVideo, screenShareEnabled: s
@johnxnguyen I don't think that we should provide a reason for why the call ended. I suppose that we get that from the system like we do with some other things like `video`, `toggle video`. That's why I mentioned my `callEndedReason` implementation is not right. What you think?

2021-11-30 16:16 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +// swiftlint:disable line_length
This is because our method regarding `endedCall` exceeds 250 characters

2021-12-02 07:52 UTC, johnxnguyen requested changes

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
> +    /// Expected to refer to a value of type `AnalyticsCallParticipantsType`.
This should refer to a `RoundedInt`.

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
> +    enum ReasonCallEnded: String, AnalyticsAttributeValue {
I suggest to call this `CallEndReason`, I think it's simpler and more direct.

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
> +    static func endedCall(asVideoCall: Bool, callDirection: CallDirection, callDuration: Double, callParticipants: Double, videoEnabled: Bool, screenShareEnabled: Bool, callEndedReason: ReasonCallEnd
You can split long method signatures over multiple lines to stay within the line length limit. For example:

```swift
static func endedCall(asVideoCall: Bool,
                      callDirection: CallDirection,
                      callDuration: CallDuration,
                      ...,
                      conversation: ZMConversation) -> AnalyticsEvent {
  ...
} 
```

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +// swiftlint:disable line_length
I think it would be better to split long lines over multiple lines. See the comment below.

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let toggleVideo = callInfo.toggledVideo ? true : false
```suggestion
            let toggleVideo = callInfo.toggledVideo
```

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let participants = Double(callInfo.maximumCallParticipants)
I suggest adding an new init for `RoundedInt` that accepts an integer, so you wouldn't need to do the cast here.

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let screenShare = conversation.voiceChannel?.videoState ==  .screenSharing ? true : false
@David-Henner is the `videoState` the current video state? And of who, the self user?

We're supposed to be sending  bool indicating that screen sharing was enabled at least once by any user.

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            Analytics.shared.tagEvent(.endedCall(asVideoCall: video, callDirection: .outgoing, callDuration: duration, callParticipants: participants, videoEnabled: toggleVideo, screenShareEnabled: s
Why shouldn't we provide a value? Or are you wondering, where do we get the reason from?

2021-12-02 07:52 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            Analytics.shared.tagEvent(.endedCall(asVideoCall: video, callDirection: .outgoing, callDuration: duration, callParticipants: participants, videoEnabled: toggleVideo, screenShareEnabled: s
I also don't think this is the right place to tag the event. This enclosing method is for extracting the attributes (in the legacy way). Let's move this to a better place, such as the calling method `tag(callEvent: CallEvent, in conversation: ZMConversation, callInfo: CallInfo)`.

Actually, that goes for other events we're tagging here, such as screen sharing.

2021-12-02 08:46 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            Analytics.shared.tagEvent(.endedCall(asVideoCall: video, callDirection: .outgoing, callDuration: duration, callParticipants: participants, videoEnabled: toggleVideo, screenShareEnabled: s
> Why shouldn't we provide a value? Or are you wondering, where do we get the reason from?

I think the latter. Where do we get the reason from? And if we provide a reason from where do we get it? @johnxnguyen

2021-12-02 08:56 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let participants = Double(callInfo.maximumCallParticipants)
How that would look like? @johnxnguyen

2021-12-02 09:05 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let participants = Double(callInfo.maximumCallParticipants)
If I do

`let duration = RoundedInt(Int(-establishedDate.timeIntervalSinceNow), factor: 6)`

I will have to change the type of my duration from `Double` to `RoundedInt` correct?

2021-12-02 09:20 UTC, agisilaos commented
> I also don't think this is the right place to tag the event. This enclosing method is for extracting the attributes (in the legacy way). Let's move this to a better place, such as the calling method tag(callEvent: CallEvent, in conversation: ZMConversation, callInfo: CallInfo). Actually, that goes for other events we're tagging here, such as screen sharing.

@johnxnguyen Let's tackle this one on a separate PR when we're going to clean things up. Good point though.

2021-12-02 11:09 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            Analytics.shared.tagEvent(.endedCall(asVideoCall: video, callDirection: .outgoing, callDuration: duration, callParticipants: participants, videoEnabled: toggleVideo, screenShareEnabled: s
The reason is provided as an associated value in the enum case `ended(reason: ...)`. In this switch, it's being discarded, but you could just bind it to a variable and convert it to the type you need.

2021-12-02 11:15 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let toggleVideo = callInfo.toggledVideo ? true : false
Given a the variable 'let isThisBoolTrue: Bool`, then all of these code blocks are equivalent:

```swift
let result = isThisBoolTrue ? true : false
```

```swift
let result: Bool
if isThisBoolTrue {
  result = true
} else {
  result = false
}
```

```swift
let result = isThisBoolTrue
```

In my opinion, the last one is most concise and readable.

2021-12-02 11:19 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let participants = Double(callInfo.maximumCallParticipants)
I'm not sure what the existing initializer for `RoundedInt` is, but I'm suggesting that `RoundedInt` should have different initializers with different numeric types so you don't need to cast a number in order to create the `RoundedInt`. For instance:

```swift
extension RoundedInt {
 
  init(_ value: Int) {
    init(Double(value))
  }

}
```

2021-12-02 11:27 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let participants = Double(callInfo.maximumCallParticipants)
We already have a public extension for `RoundedInt` so I will add it there.

2021-12-02 11:30 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let toggleVideo = callInfo.toggledVideo ? true : false
So this should be applied for all constants?
```swift
let video = conversation.voiceChannel?.isVideoCall ?? false
let toggleVideo = callInfo.toggledVideo ? true : false
let screenShare = conversation.voiceChannel?.videoState ==  .screenSharing ? true : false
```

2021-12-02 11:31 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            Analytics.shared.tagEvent(.endedCall(asVideoCall: video, callDirection: .outgoing, callDuration: duration, callParticipants: participants, videoEnabled: toggleVideo, screenShareEnabled: s
So in this case should we leave it as it is?

2021-12-02 11:53 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            Analytics.shared.tagEvent(.endedCall(asVideoCall: video, callDirection: .outgoing, callDuration: duration, callParticipants: participants, videoEnabled: toggleVideo, screenShareEnabled: s
I would love to know how I can do that. 🤔

2021-12-02 13:39 UTC, David-Henner commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let screenShare = conversation.voiceChannel?.videoState ==  .screenSharing ? true : false
`videoState` is the current video state of the self user

2021-12-02 13:43 UTC, David-Henner commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let screenShare = conversation.voiceChannel?.videoState ==  .screenSharing ? true : false
If you need to observe screen sharing state for each participant it can be done using the `WireCallCenterCallParticipantObserver`

2021-12-02 15:05 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let screenShare = conversation.voiceChannel?.videoState ==  .screenSharing ? true : false
@johnxnguyen thoughts?

2021-12-03 07:26 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                                                     callClosedReason: reason, conversation: conversation))
```suggestion
                                                     callClosedReason: reason,
                                                     conversation: conversation))
```

2021-12-03 07:26 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
> +                          callParticipants: Double,
```suggestion
                          callParticipants: Int,
```

I think an Int is more suitable here.

2021-12-03 07:26 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallStateEvents.swift
> +    /// Expected to refer to a value of type `AnalyticsCallEndedReasonType`.
```suggestion
    /// Expected to refer to a value of type `CallClosedReason`.
```

2021-12-03 07:26 UTC, johnxnguyen commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let screenShare = conversation.voiceChannel?.videoState ==  .screenSharing ? true : false
Let's see do a pairing session to see if we can get not only the current video state, but if someone shared the screen at least once.

2021-12-03 09:50 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                let video = conversation.voiceChannel?.isVideoCall ?? false
suggests a clearer name
```suggestion
                let isVideoCall = conversation.voiceChannel?.isVideoCall ?? false
```

2021-12-03 09:51 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                let participants = Double(callInfo.maximumCallParticipants)
```suggestion
                let maximumCallParticipants = Double(callInfo.maximumCallParticipants)
```

2021-12-03 09:51 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                let screenShare = conversation.voiceChannel?.videoState ==  .screenSharing
```suggestion
                let isSharingScreen = conversation.voiceChannel?.videoState ==  .screenSharing
```

2021-12-03 09:52 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
> +                guard let establishedDate = callInfo.establishedDate else { return }
put this guard outside the if let to return earlier

2021-12-03 09:57 UTC, billypchan commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            let video = conversation.voiceChannel?.isVideoCall ?? false
```suggestion
            let isVideoCall = conversation.voiceChannel?.isVideoCall ?? false
```

2021-12-03 09:58 UTC, billypchan commented on Wire-iOS/Sources/Analytics/Events/Analytics+CallEvents.swift
> +            guard let establishedDate = callInfo.establishedDate else { return [:] }
move this to top

2021-12-03 10:00 UTC, billypchan reviewed
code suggestion

2021-12-03 10:44 UTC, billypchan commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
>              if let callInfo = callInfos[conversationId] {
It would be cleaner to merge the guard let below with this if let

2021-12-03 10:50 UTC, agisilaos commented on Wire-iOS/Sources/Analytics/AnalyticsCallingTracker.swift
>              if let callInfo = callInfos[conversationId] {
Hmm how so? What would be the difference?

2021-12-06 07:18 UTC, johnxnguyen approved these changes

2021-12-06 09:15 UTC, agisilaos commented
@billypchan Took care of all your comments and suggestions. PR's ready for another check.

2021-12-06 09:37 UTC, billypchan approved these changes

2021-12-06 09:38 UTC, merged