feat: Separate access controls for Guests and Services SQSERVICES-1052
wireapp/wire-ios pull request #5516
Opened 2022-01-13 14:56 UTC by agisilaos

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

With this PR we separate access controls for Guests and Services in the UI Project. As you will see there was a lot of renaming stuff going around. It was hard to work on this mostly because of the naming in some cases. So:

- I took the time to rename stuff and separate guests and services in terms of the naming of methods, properties, classes etc. In addition to that I created separate files for all services classes to make sure they're truly separated. 
- Cleaned up all the files related to guests.

# TODO:
- [ ] Fix all the todo's I left in various places when I make the changes in data model.
- [ ] Add Tests for Services
- [ ] Update copy as soon as I hear back from Astrid
- [ ] Check if anything else needs renaming for better understanding of the flow and code

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] https://github.com/wireapp/wire-ios-sync-engine/pull/1644

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation Options/ConversationGuestOptionsViewModel.swift
> +    private func computeVisibleRowsForGuests() -> [CellConfiguration] {/// TODO: copy?
The name can stay the same, since this view model is only about guests.

```suggestion
    private func computeVisibleRows() -> [CellConfiguration] {/// TODO: copy?
```

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation Options/ConversationServicesOptionsViewController.swift
> +        // We shouldn't display an error message if the services is disabled. There's a UI element that explains why the user cannot use/create links to join the conversation.
What is this comment referring to? Guest links are irrelevant to services.

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation Options/ConversationServicesOptionsViewModel.swift
> +                case .failure(let error): self.delegate?.viewModel(self, didReceiveError: error)
```suggestion
                case .failure(let error): 
                    self.delegate?.viewModel(self, didReceiveError: error)
```

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingGuests.swift
> +            confirmTitle: "guest_room.remove_services.action".localized,
Services aren't related to guest rooms, so perhaps it's better to change the localisation keys to avoid confusion.

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Create/Cells/ConversationCreateOptionsCell.swift
> +        status = "conversation.create.options.subtitle".localized(args: guests, services, receipts)
It's preferred to use the `L10n` enum for typesafe localisation keys. In this case, it would probably look something like:

```swift
status = L10n.Localizable.Conversation.Create.Options.subtitle(guests, services, receipts)
```

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Create/Cells/ConversationCreateServicesCell.swift
> +        title = "conversation.create.services.title".localized
Use the `L10n` enum to get the localised string.

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Create/ConversationCreationController.swift
> +                let noGuests = result.filter {$0.isOnSameTeam(otherUser: selfUser) }
```suggestion
                let noGuests = result.filter { $0.isOnSameTeam(otherUser: selfUser) }
```

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation/Create/Sections/ConversationCreateServicesSectionController.swift
> +        footerText = "conversation.create.services.subtitle".localized
Use the `L10n` enum for localised strings.

2022-02-07 09:26 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/GroupDetails/Cells/GroupDetailsServicesCell.swift
> +            status = key.localized
Use the `L10n` enum for localised strings.

2022-02-07 10:04 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation Options/ConversationServicesOptionsViewController.swift
> +        // We shouldn't display an error message if the services is disabled. There's a UI element that explains why the user cannot use/create links to join the conversation.
Need to clean up a couple of things. Will do now.

2022-02-07 10:08 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingGuests.swift
> +            confirmTitle: "guest_room.remove_services.action".localized,
In this case this is in method:

```swift
 static func confirmRemovingServices(_ completion: @escaping (Bool) -> Void) -> UIAlertController {
        return confirmController(
            title: "guest_room.remove_services.message".localized,
            confirmTitle: "guest_room.remove_services.action".localized,
            completion: completion
        )
    }
    ```
    
So it is about services. Maybe should we rename the file or move this method to a separate file.

2022-02-07 11:39 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/GroupDetails/Cells/GroupDetailsServicesCell.swift
> +            status = key.localized
@johnxnguyen Fixed it in all of the other cases. Not sure how to do this here.

2022-02-07 12:19 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingGuests.swift
> +            confirmTitle: "guest_room.remove_services.action".localized,
Sure we can do that, but I was referring to the localisation keys `guest_room.remove_services.message` and `guest_room.remove_services.action`, that they should be something like `conversation_options.remove_services.message`.

2022-02-07 12:22 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/GroupDetails/Cells/GroupDetailsServicesCell.swift
> +            status = key.localized
Something like:

```swift
typealias ServicesOptionCell = L10n.Localizable.GroupDetails.ServicesOptionCell
let key = isOn ? ServicesOptionCell.enabled : ServicesOptionCell.disabled
```

2022-02-09 10:33 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingGuests.swift
> +            confirmTitle: "guest_room.remove_services.action".localized,
Just fixed it! @johnxnguyen

2022-02-09 12:38 UTC, johnxnguyen requested changes

2022-02-09 12:38 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"services_room.remove_services.action" = "Remove";
"services_room" doesn't make much sense, I suggest something "conversation_options.allow_services.title"

2022-02-09 12:38 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingServices.swift
> +            confirmTitle: "services_room.remove_services.action".localized,
Use the `L10n` enum for localised strings.

2022-02-10 09:50 UTC, agisilaos commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"services_room.remove_services.action" = "Remove";
@johnxnguyen If we change it from `services_room` to `conversation_options` we will have to follow the same pattern with Guests as well.

2022-02-10 10:26 UTC, johnxnguyen reviewed
Some snapshots are not working (they're showing red error snapshots), I think related to the alerts.

2022-02-10 11:44 UTC, agisilaos commented
@johnxnguyen I think that was the case even before my changes occurred and I have a feeling that's not related.

2022-02-11 16:33 UTC, sb88k reviewed
There are some snapshot test cases created warning image instead of the testing view's snapshot.
For example, this one
ReferenceImages/14_4_0/ConversationOptionsViewControllerTests/testThatItRendersRemoveGuestsWarning.1.png

2022-02-14 10:16 UTC, agisilaos commented
> There are some snapshot test cases created warning image instead of the testing view's snapshot.
For example, this one
ReferenceImages/14_4_0/ConversationOptionsViewControllerTests/testThatItRendersRemoveGuestsWarning.1.png

@sb88k It is not because of the changes I was able to verify that assumption by looking at the[ git history](https://github.com/wireapp/wire-ios/blob/develop/Wire-iOS%20Tests/ReferenceImages/15_0_0/ConversationOptionsViewControllerTests/testThatItRendersRemoveGuestsAndServicesWarning.1.png).

2022-02-14 11:18 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation Options/ConversationServicesOptionsViewController.swift
> +        return cell as! UITableViewCell
I think that I need. Otherwise I get an error like this:

`Cannot convert return expression of type 'CellConfigurationConfigurable' to return type 'UITableViewCell'`

2022-02-14 11:39 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"services_room.remove_services.action" = "Remove";
Ideally yes we'd also have `conversation_options.guests`, but changing the localisation key for the existing strings will mean they have to be re-translated, so typically we don't do that. It's better to pick appropriate localisation keys when the keys are added.

2022-02-14 11:40 UTC, johnxnguyen commented
> @johnxnguyen I think that was the case even before my changes occurred and I have a feeling that's not related.

@agisilaos perhaps we can still fix them here though. Look like you just need to set a non zero frame size on the view that is being snapshotted.

2022-02-14 11:42 UTC, agisilaos commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"services_room.remove_services.action" = "Remove";
So we will change the set of strings for services, and leave the guests strings as it is?

2022-02-14 14:11 UTC, johnxnguyen commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"services_room.remove_services.action" = "Remove";
Yes

2022-02-14 17:14 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/AddContacts/AddParticipantsViewController.swift
> +    var includeServices: Bool {
Where do we use this property?

2022-02-14 17:24 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation Options/Conversation+OptionsConfiguration.swift
> +            allowServicesChangedHandler?(allowServices)
I think it won't work if `allowGuestsChanged` is false and `allowServicesChanged` is true. I suggest something like this:
```
if changeInfo.allowGuestsChanged {
   allowGuestsChangedHandler?(allowGuests)
} 
if changeInfo.allowServicesChanged {
  allowServicesChangedHandler?(allowServices)
}
```

2022-02-14 17:27 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation Options/ConversationGuestOptionsViewModel.swift
> +        if !allowGuests && configuration.areGuestPresent {
We might need to adjust the comment above

2022-02-14 17:30 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation Options/UIAlertController+ConfirmRemovingServices.swift
> +            title: "services_room.remove_services.message".localized,
You can use the L10n enum for localised strings

2022-02-14 17:32 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationViewController+ConversationContentViewControllerDelegate.swift
> +            zmLog.error("Illegal Operation: Trying to show guest options for non-group conversation")
In the error message, we are talking about guests.

2022-02-16 14:19 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Conversation Options/Conversation+OptionsConfiguration.swift
> +            allowServicesChangedHandler?(allowServices)
@KaterinaWire So we remove the guard statements from here?

2022-02-16 14:24 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Conversation Options/Conversation+OptionsConfiguration.swift
> +            allowServicesChangedHandler?(allowServices)
Yes, @KaterinaWire is right.

2022-02-16 15:51 UTC, KaterinaWire commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var allowServices: Bool = false
Do we use it in tests or is it part of some protocol? Then why don't we have allowGuests?

2022-02-16 15:53 UTC, KaterinaWire commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var allowServices: Bool = false
It might be better to add it next to the `allowGuests` property. It will be easier to search for it.

2022-02-16 15:54 UTC, KaterinaWire commented on Wire-iOS Tests/Mocks/MockConversation.swift
> +    var accessRoles: Set<ConversationAccessRoleV2> = [.teamMember]
It would also be nice to have this property next to the old `accessRole`.

2022-02-18 10:25 UTC, johnxnguyen approved these changes

2022-02-18 10:33 UTC, merged