feat: add classification in profile FS-97
wireapp/wire-ios pull request #5544
Opened 2022-02-03 12:52 UTC by sb88k

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Show security classification view in user profile and connection screens

2022-02-07 09:52 UTC, johnxnguyen requested changes
You'll need to update some snapshot tests.

2022-02-07 15:44 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/ConnectRequests/IncomingConnectionView.swift
> +            securityLevelView.topAnchor.constraint(equalTo: userDetailView.bottomAnchor),
```suggestion
            userDetailView.bottomAnchor.constraint(lessThanOrEqualTo: securityLevelView.topAnchor),

            securityLevelView.centerXAnchor.constraint(equalTo: centerXAnchor),
```

2022-02-07 15:44 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/ConnectRequests/IncomingConnectionView.swift
> +            securityLevelView.topAnchor.constraint(equalTo: userDetailView.bottomAnchor),
duplicate constraint

2022-02-07 15:44 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/UserProfile/ProfileViewController.swift
>          incomingRequestFooter.translatesAutoresizingMaskIntoConstraints = false
```suggestion
        [usernameDetailsView,
        securityLevelView,
        tabsView,
        profileFooterView,
        incomingRequestFooter].prepareForLayout()
```

2022-02-09 07:48 UTC, johnxnguyen reviewed
The design spec shows the security level view with a border only on the top and bottom edge, but the snapshots show a full border around all edges.

2022-02-09 12:27 UTC, johnxnguyen approved these changes
Looks good, you just need to update the dependencies since I merged my branches.

2022-02-09 14:31 UTC, David-Henner approved these changes

2022-02-09 15:05 UTC, merged