feat: add security level banner in conversation FS-98
wireapp/wire-ios pull request #5545
Opened 2022-02-04 09:57 UTC by sb88k

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Add and show the security level banner in the conversation screen

2022-02-07 09:53 UTC, johnxnguyen requested changes
We need to update some snapshot tests

2022-02-07 15:48 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
> +    let securityLevelView = SecurityLevelView()
```suggestion
    private let securityLevelView = SecurityLevelView()
```

2022-02-07 15:48 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Conversation/InputBar/ConversationInputBarViewController.swift
> +            securityLevelView.trailingAnchor.constraint(equalTo: securityLevelView.superview!.trailingAnchor),
Is it necessary to force unwrap the `superview`? Since `securityLevelView` is a subview of `view`, can't we just use `view` instead of `superview`?

2022-02-09 12:28 UTC, johnxnguyen approved these changes

2022-02-09 14:33 UTC, David-Henner approved these changes

2022-02-09 15:18 UTC, merged