feat:Added feature to mute and unmute calls through settings-SQCall-470
wireapp/wire-ios pull request #5604
Opened 2022-03-21 16:27 UTC by johnranj

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

# What's new in this PR?

### Issues

Incoming call sound disturbs while any user is partaking in an ongoing call

### Solutions

Provide a switch toggle in the setting is set to mute incoming calls when the user is on a call, and when the user in fact is on a call, then the incoming call makes no ringing sound.

### Testing

To do.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-03-21 16:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5604) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5604) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=5604) it.</sub>

2022-03-23 13:22 UTC, David-Henner requested changes
Looks good 👍

2022-03-23 13:22 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Options.swift
> +            footer: "self.settings.mute_other_call.description".localized,
Best to use the auto generated localisation helpers

2022-03-23 13:22 UTC, David-Henner commented on Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
> +    }
Instead of creating a new func, you could just change the access level of `configureDefaultSounds` from private to internal, and call it directly.

2022-03-23 13:22 UTC, David-Henner commented on Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
> +    func configureWithUnMuteFromSettings() {
I'd rename this to something more explicit, maybe `unregisterCallRingingSounds` or `disableCallRingingSounds` or similar

2022-03-23 13:22 UTC, David-Henner commented on Wire-iOS/Sources/Components/Settings.swift
> +    case disableMuteCallKit = "UserDefaultDisableMuteCallKit"
I find the naming confusing here. I'd rename it to something more explicit, like `muteIncomingCallsWhileInACall` or `muteOtherCalls`

2022-03-23 13:22 UTC, David-Henner commented on WireCommonComponents/SettingsPropertyName.swift
> +    case disableMuteCallKit = "DisableMuteCallKit"
same comment to rename this as the one above

2022-03-23 13:22 UTC, David-Henner commented on Wire-iOS/Sources/Helpers/syncengine/SessionManager+Convenience.swift
> +    func updateMuteCallFromSettings() {
```suggestion
    func updateMuteOtherCallsFromSettings() {
```

2022-03-23 13:23 UTC, David-Henner commented on Wire-iOS/Resources/Base.lproj/Localizable.strings
> +"self.settings.mute_other_call.description" = "Set all incoming calls to not making a sound when you are already on a call.";
Copy from the ticket https://wearezeta.atlassian.net/browse/SQCALL-460

2022-03-23 13:25 UTC, David-Henner commented on Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
> +        }
So, this only unregister the sounds of the calls incoming while already in a call? Or does it also unregister the sounds of incoming calls while not on a call?

2022-03-28 14:29 UTC, johnranj commented on Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
> +        }
It will unregister the sounds of the calls in icoming while in a call

2022-03-29 06:32 UTC, johnxnguyen commented on Wire-iOS/Sources/Helpers/syncengine/SessionManager+Convenience.swift
> +        let isMuteCallEnabled: Bool = !(Settings.shared[.muteIncomingCallsWhileInACall] ?? false)
If `Settings.shared[.muteIncomingCallsWhileInACall]` is `false`, or if it has no value, then `isMuteCallEnabled` will be `true`. Is that correct? I would expect that if the setting is false or doesn't exist, then `isMuteCallEnabled` would also be false.

2022-03-29 06:35 UTC, johnxnguyen commented on Wire-iOS/Sources/Helpers/syncengine/SessionManager+Convenience.swift
> +        if isMuteCallEnabled && hasAudioPermissions {
Why do we need to check for audio permissions?

2022-03-29 08:34 UTC, johnranj commented on Wire-iOS/Sources/Helpers/syncengine/SessionManager+Convenience.swift
> +        let isMuteCallEnabled: Bool = !(Settings.shared[.muteIncomingCallsWhileInACall] ?? false)
If Settings.shared[.muteIncomingCallsWhileInACall] is false isMuteCallEnabled = !(false ?? false) = !(true) = false so isMuteCallEnabled will be false

2022-03-29 13:04 UTC, johnxnguyen approved these changes
Looks good to me 👍🏻

2022-04-04 13:45 UTC, David-Henner approved these changes
Approved but please take a look at my comment :)

2022-04-04 13:45 UTC, David-Henner commented on Wire-iOS/Sources/Helpers/sound/AVSMediaManager+CustomSounds.swift
> +    internal func configureDefaultSounds() {
```suggestion
    func configureDefaultSounds() {
```

By default funcs are already internal

2022-04-04 15:33 UTC, merged