feat: Advanced Screen (Within Settings Screen): Dynamic Type Support (Partially Implemented) - ACC-99
wireapp/wire-ios pull request #5675
Opened 2022-05-23 12:14 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ x] contains a reference JIRA issue number like `SQPIT-764`
  - [ x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

With this PR, we fixed the problem of linear font scaling. Now it's non-linear and better represents each level of accessibility when the user wants to have bigger or smaller text. </br>

Take a look at the previous implementation:
| iPhone 8 - English  | iPhone 8 - German  |  iPhone SE - English | iPhone SE - German  |
|---|---|---|---|
| <img width="548" alt="Screenshot 2022-05-12 at 08 21 49" src="https://user-images.githubusercontent.com/50630878/169814592-48919ce7-79bb-4dd5-8a6f-a4c328ce68d9.mp4">  | <img width="548" alt="Screenshot 2022-05-12 at 08 26 22" src="https://user-images.githubusercontent.com/50630878/169814623-131afbce-2ac0-4958-881e-cae73ab8d6f4.mp4">  | <img width="548" alt="Screenshot 2022-05-12 at 09 54 36" src="https://user-images.githubusercontent.com/50630878/169814725-2bcf0788-e3a6-41f4-bf23-26f1c1ea12d5.mp4"> | <img width="548" alt="Screenshot 2022-05-12 at 08 25 21" src="https://user-images.githubusercontent.com/50630878/169814736-8d6cc067-946e-4f3f-bf9d-c961a38126c3.mp4">  |

*And how it looks like now*:
| iPhone 8 - English  | iPhone 8 - German  |  iPhone SE - English | iPhone SE - German  |
|---|---|---|---|
| <img width="548" alt="Screenshot 2022-05-12 at 08 21 49" src="https://user-images.githubusercontent.com/50630878/169815673-a0a51b29-865b-4016-866c-d6d06dac56af.mp4">  | <img width="548" alt="Screenshot 2022-05-12 at 08 26 22" src="https://user-images.githubusercontent.com/50630878/169815739-a994872a-a306-4d55-a8f2-55905bb302ae.mp4">  | <img width="548" alt="Screenshot 2022-05-12 at 09 54 36" src="https://user-images.githubusercontent.com/50630878/169815813-e6431864-1d0f-491d-9e95-2d168b0867f3.mp4"> | <img width="548" alt="Screenshot 2022-05-12 at 08 25 21" src="https://user-images.githubusercontent.com/50630878/169815827-7a24806c-09be-4747-9a34-d2b2d3bb1370.mp4">  |
### Issues

Basically my task was to:
[x] Fix the colour of the arrows in cells. As we have been discussing we can wait till min. versions of the app will be 13 and use SF symbol here to do not search for a walkaround of the problem that SF Symbol will easily fix.
[ ] Fix truncated text in Reset Push Notifications Token label when Dynamic type has been applied. It has been finished.

Besides of that, we have found out that the font scaling used until now isn't working as it should be because sometimes font might seem too small/big. That's why this PR contains mostly a way to fix that.

### Solutions

The solution for this is to implement a new function that returns the size for each contentCategorySize and FontSize.
Currently, each size is being calculated based on https://stablekernel.com/article/supporting-accessibility-larger-text-in-ios/ and Apple human interface guidelines.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-05-23 12:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5675) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5675) before we can accept your contribution.<br/><hr/>**PawelB** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=5675) it.</sub>

2022-05-24 08:15 UTC, johnxnguyen commented on WireCommonComponents/FontScheme.swift
> +        return 17
`UIContentSizeCategory.large` is the default size, and previously the default point size for `FontSize.small` was 11. On the one hand, the design team is rethinking what point sizes to use, but on the other hand, we don't want to change the existing design at this point.

You may notice that although the CI reports a green check, it does so erroneously as there are a lot of test failures. This is expected when the default point sizes are changed.

My suggestion would be to use the default point sizes as a starting point, then determine the maximum and minimum point sizes around that default.

2022-05-24 08:17 UTC, BrzozowskiPawel commented on WireCommonComponents/FontScheme.swift
> +        return 17
@johnxnguyen Yes, you are right. This is the case that I want to disguise on today's meeting :D

2022-05-25 07:46 UTC, agisilaos requested changes

2022-05-25 08:41 UTC, BrzozowskiPawel commented on WireCommonComponents/FontScheme.swift
> +    // SMALLL
@agisilaos as we have talked about this is now part of another feature:
https://github.com/wireapp/wire-ios/pull/5677

But you are more than right I will change it there

2022-05-25 08:43 UTC, BrzozowskiPawel commented on Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
> +      language = "de"
Yes of course. It's not set to system language as it was on default.
I will focus more to do not push things like this anymore.

2022-05-25 10:05 UTC, johnxnguyen approved these changes
Looks good, but don't forget to remove the changes for the language in the scheme.

2022-05-25 10:37 UTC, agisilaos approved these changes

2022-05-25 11:16 UTC, merged