feat: Archive Screen: Dynamic Type Support - ACC-93
wireapp/wire-ios pull request #5682
Opened 2022-05-26 09:22 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

In this PR I have implemented dynamic font size support for the navbar in the archive screen. Before these changes users had to go back from the archive screen and then reopen this screen to see the updated font size in the nav bar. Now it's instantly updating whenever the user uses font accessibility.

![ip8_de](https://user-images.githubusercontent.com/50630878/170458159-1173b83c-ae1b-4fee-acda-1b86bcb5faab.gif)
![ip8_en]()
![ipSE_de]()
![ipSE_en](f)

| iPhone 8 - English  | iPhone 8 - German  |  iPhone SE - English | iPhone SE - German  |
|---|---|---|---|
| <img width="548" alt="Screenshot 2022-05-12 at 08 21 49" src="https://user-images.githubusercontent.com/50630878/170458172-4defd999-20c2-4598-86ab-35bba7d696f4.gif">  | <img width="548" alt="Screenshot 2022-05-12 at 08 26 22" src="https://user-images.githubusercontent.com/50630878/170458159-1173b83c-ae1b-4fee-acda-1b86bcb5faab.gif">  | <img width="548" alt="Screenshot 2022-05-12 at 09 54 36" src="https://user-images.githubusercontent.com/50630878/170458182-ae4b816d-0990-4e6c-989a-12bbaadd54b7.gif"> | <img width="548" alt="Screenshot 2022-05-12 at 08 25 21" src="https://user-images.githubusercontent.com/50630878/170458177-db46256c-c004-41ec-8948-c801798d1eed.gif">  |

### Issues

The issue was that the user could not see font size changes in real-time. It was obligated to go back from the archive screen and then reopen it again to see applied changes.

### Causes (Optional)

Before this update navbar has a basic UILabel responsible for displaying text in the navbar.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-05-27 10:35 UTC, KaterinaWire approved these changes

2022-05-30 07:37 UTC, agisilaos requested changes
Looking good, we need to change a small think and I think it would be good for merging. @BrzozowskiPawel

2022-05-30 07:37 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/ArchivedNavigationBar.swift
> +            color: .textBackground)
I think that in this case you also need to include the variant and set it to dark. Like this:

```suggestion
        let label = DynamicFontLabel(
             fontSpec: .mediumSemiboldFont,
             color: .textBackground
             variant: .dark)
```

2022-05-30 07:51 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ArchivedNavigationBar.swift
> +            color: .textBackground)
Yes @agisilaos you are right but take a look at how it's looking on the develop right now:
![image](https://user-images.githubusercontent.com/50630878/170943652-1d2e762d-71f3-43bb-87e4-07e7375e22f3.png)

And after the change that you have suggested it will look like this:
![image](https://user-images.githubusercontent.com/50630878/170944029-878563e9-5852-4150-8cab-b0681bc229c9.png)

2022-05-30 07:52 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ArchivedNavigationBar.swift
> +            color: .textBackground)
So there are 2 different colours of the text, I can do as you say but will it be good?

2022-05-30 08:29 UTC, agisilaos approved these changes

2022-05-30 10:04 UTC, merged