feat: arrow/chevron color fix. Multiple ACC tickets.
wireapp/wire-ios pull request #5684
Opened 2022-05-27 13:40 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

This pull request resolves the issue with the grey/black arrow (chevron) being displayed If a cell has another list presented when clicked. 

### Solutions

The solution is to implement accessoryView set as SF Symbol with the selected colour. Also, we have deleted unnecessary cell type to make it more clear.

![ip8_de]()
![ip8_en]()
![ipSE_de]()
![ipSE_en]()

| iPhone 8 - English  | iPhone 8 - German  |  iPhone SE - English | iPhone SE - German  |
|---|---|---|---|
| <img width="548" alt="Screenshot 2022-05-12 at 08 21 49" src="https://user-images.githubusercontent.com/50630878/170710700-7be21de0-cc26-4ad9-84a1-800ff6a92070.gif">  | <img width="548" alt="Screenshot 2022-05-12 at 08 26 22" src="https://user-images.githubusercontent.com/50630878/170710672-43e5eadb-27e6-46c0-a06d-3881c7c42333.gif">  | <img width="548" alt="Screenshot 2022-05-12 at 09 54 36" src="https://user-images.githubusercontent.com/50630878/170710717-fd73da52-c088-4b1d-894f-35b8a511cd34.gif"> | <img width="548" alt="Screenshot 2022-05-12 at 08 25 21" src="https://user-images.githubusercontent.com/50630878/170710710-f29ab6c8-a287-4993-b4a3-0bf7381d0ca6.gif">  |

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-05-27 14:48 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenCellDescriptor.swift
> +extension UITableViewCell {
There's a few lint issues to fix here. I would also suggest to move this to a separate file.

2022-05-30 08:25 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenCellDescriptor.swift
> +extension UITableViewCell {
@johnxnguyen it's all done. You can take a look once again :D

2022-05-30 08:50 UTC, agisilaos commented on Wire-iOS.xcodeproj/project.pbxproj
> -		EE12922827E47E6D00C9CC60 /* Wire Share Extension.appex in Embed App Extensions */ = {isa = PBXBuildFile; fileRef = 168A16A91D9597C2005CFA6C /* Wire Share Extension.appex */; settings = {ATTRIBUTES
This doesn't look right? @johnxnguyen

2022-05-30 11:25 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Settings/SettingWhiteChevronUITableViewExtension.swift
> +extension UITableViewCell {
The convention for files containing extensions is to call them after the class name + a description for the extension. For instance `UITableViewCell+DisclosureIndicator.swift`.

2022-05-30 11:25 UTC, johnxnguyen commented on Wire-iOS.xcodeproj/project.pbxproj
> -		EE12922827E47E6D00C9CC60 /* Wire Share Extension.appex in Embed App Extensions */ = {isa = PBXBuildFile; fileRef = 168A16A91D9597C2005CFA6C /* Wire Share Extension.appex */; settings = {ATTRIBUTES
It's been happening for a while now, not sure why it keeps happening. But it doesn't seem harmful, just annoying.

2022-05-30 11:49 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingWhiteChevronUITableViewExtension.swift
> +extension UITableViewCell {
Thanks, I will remember to use the proper file naming in the future :D

2022-05-30 12:09 UTC, johnxnguyen commented on Wire-iOS.xcodeproj/project.pbxproj
> +		E52F448B2844E916008E11CB /* UITableViewCellDisclosureIndicator.swift in Sources */ = {isa = PBXBuildFile; fileRef = E52F448A2844E916008E11CB /* UITableViewCellDisclosureIndicator.swift */; };
Don't forget the `+`, as in `UITableViewCell+DisclosureIndicator`. ☺️

2022-05-30 12:36 UTC, BrzozowskiPawel commented on Wire-iOS.xcodeproj/project.pbxproj
> +		E52F448B2844E916008E11CB /* UITableViewCellDisclosureIndicator.swift in Sources */ = {isa = PBXBuildFile; fileRef = E52F448A2844E916008E11CB /* UITableViewCellDisclosureIndicator.swift */; };
Hahah ok sorry now I get it 😎

2022-05-31 09:41 UTC, agisilaos requested changes
We need to take care a few things before this is ready. When those two things are fixed we will be good to go. 

1. Revert the changes regarding the CountryTests
2. Change the name of the file @johnxnguyen mentioned

2022-05-31 09:42 UTC, BrzozowskiPawel commented on Wire-iOS Tests/CountryTests.swift
> +        XCTAssertEqual(countryFromDevice?.iso, "us")
OK sure thing

2022-05-31 11:23 UTC, johnxnguyen approved these changes

2022-05-31 14:35 UTC, agisilaos requested changes

2022-05-31 14:35 UTC, agisilaos commented on Wire-iOS.xcodeproj/xcshareddata/xcschemes/Wire-iOS.xcscheme
> +               </Test>
This needs to be removed.

2022-05-31 14:54 UTC, agisilaos approved these changes

2022-06-02 07:55 UTC, merged