feat: apply new color design for switch - ACC-138
wireapp/wire-ios pull request #5722
Opened 2022-06-17 12:22 UTC by BrzozowskiPawel

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/ACC-138" title="ACC-138" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />ACC-138</a>  Contrast distance from text to background (1.4.3)
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Applied a new UI for the switch. 
According to the confluence page, the UISwitch class now adopt the SwitchStyle which is responsible for the desired color of the switch.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-06-17 12:23 UTC, johnxnguyen commented
Should this be targeting `develop` or some other branch?

2022-06-17 15:09 UTC, KaterinaWire commented
@BrzozowskiPawel Have you checked the approach we want to implement on [the confluence page](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/601522245/Apply+new+color+library)?

2022-06-17 15:22 UTC, KaterinaWire commented
> Should this be targeting `develop` or some other branch?

@johnxnguyen It's not ready for review

2022-06-21 07:15 UTC, KaterinaWire commented on WireCommonComponents/WireSwitch.swift
> +struct SwitchStyle {
The name of the file should be SwitchStyle

2022-06-21 07:26 UTC, KaterinaWire commented on WireCommonComponents/WireSwitch.swift
> +    static let disabled: Self = SwitchStyle(
`disabled` is a state of the element. Styles should contain colors for all state of the specific style. For example,
```
static let beautifulStyle: Self = SwitchStyle(
         onState: SemanticColors.backgroundSwitchOnVerified,
         offState: SemanticColors.backgroundSwitchOffEnabled,
         disabled: SemanticColors.backgroundSwitchOffEnabled,
         enabled: SemanticColors.backgroundSwitchOffEnabled)
```

2022-06-21 07:27 UTC, KaterinaWire commented on WireCommonComponents/WireSwitch.swift
> +    static let disabled: Self = SwitchStyle(
Take a look at the button example on the confluence page.

2022-06-21 07:28 UTC, BrzozowskiPawel commented on WireCommonComponents/WireSwitch.swift
> +struct SwitchStyle {
Sure. And the localization is good?

2022-06-21 07:28 UTC, KaterinaWire commented on Wire-iOS/Sources/Components/WireSwitch.swift
> +struct SwitchStyle {
There 2 files `struct SwitchStyle` in this PR

2022-06-21 07:28 UTC, BrzozowskiPawel commented on WireCommonComponents/WireSwitch.swift
> +    static let disabled: Self = SwitchStyle(
Ok, this is a valid point. In the next commit it will be fixed.

2022-06-21 07:29 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Components/WireSwitch.swift
> +struct SwitchStyle {
This is probably because ot the merge issue. I will fix it.

2022-06-21 07:50 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Components/WireSwitch.swift
> +struct SwitchStyle {
@KaterinaWire this was very strange. This file hasn't been visible in the file navigator inside the xcode. After searching the finder I have found that in did there were 2 files! So this one was deleted. I have never noticed this kind of error. 
Now it's all good.

2022-06-23 08:53 UTC, agisilaos requested changes
Found some small issues that need to be fixed before it's good to be merged.

2022-06-23 08:53 UTC, agisilaos commented on Wire-iOS/Sources/Components/SwitchStyle.swift
> +    static let `default`: Self = SwitchStyle(
Same here, regarding the spacing

2022-07-01 12:18 UTC, johnxnguyen commented on Wire-iOS/Sources/Components/SwitchStyle.swift
> +}
Some suggested formatting changes:

```suggestion
public struct SwitchStyle {

    private(set) var enabledOnStateColor: UIColor
    private(set) var enabledOffStateColor: UIColor
    private(set) var disabledOnStateColor: UIColor
    private(set) var disabledOffStateColor: UIColor
    
    static let `default`: Self = SwitchStyle(
        enabledOnStateColor:
            SemanticColors.SwitchColors.backgroundSwitchOnStateEnabled,
        enabledOffStateColor: SemanticColors.SwitchColors.backgroundSwitchOffStateEnabled,
        disabledOnStateColor: SemanticColors.SwitchColors.backgroundSwitchOnStateDisabled,
        disabledOffStateColor: SemanticColors.SwitchColors.backgroundSwitchOffStateDisabled
    )
    
}
```

2022-07-01 12:18 UTC, johnxnguyen commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        public static let backgroundSwitchOffStateDisabled = UIColor(light: Asset.gray50, dark: Asset.gray50)
In the snapshots for the disabled state, the disabled colors look much darker than in the design spec. I checked the color values and they're correct, so I suspend that UIKit is darkening the switch even more in the disabled state. I wonder if it makes sense to even declare the disabled colors here if UIKit is already dimming the component. What do you think?

2022-07-01 12:18 UTC, johnxnguyen commented on Wire-iOS/Sources/Components/SwitchStyle.swift
> +    convenience init(_ style: SwitchStyle = .default) {
Better to have a argument label to make it more readable. Eg `UISwitch(.default)` vs `UISwitch(style: .default)`.

2022-07-01 12:18 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/GroupDetails/Cells/IconToggleCell.swift
> +    let toggle = UISwitch(.default)
`.default` is the default value anyway, so no need to be explicit here.

2022-07-01 12:18 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +        let switchView = UISwitch(.default)
Same here, no need to be explicit.

2022-07-01 12:18 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/UserProfile/Details/Cells/IconToggleSubtitleCell.swift
> +    private let toggle = UISwitch(.default)
Here too.

2022-07-01 12:18 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/UserProfile/Devices/ProfileClientViewController.swift
> +    private let verifiedToggle = UISwitch(.default)
Here too.

2022-07-01 12:18 UTC, johnxnguyen commented on WireCommonComponents/SemanticColors.swift
> +enum SemanticColors {
This is the second `SemanticColors` enum I've seen.. which one should be used?

2022-07-01 12:22 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        public static let backgroundSwitchOffStateDisabled = UIColor(light: Asset.gray50, dark: Asset.gray50)
Maybe you are right and we shouldn't change the disabled state. 
It's hard for me to decide should it be like this or like this. 
However, I think it can be changed as you suggested.

2022-07-01 12:22 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Components/SwitchStyle.swift
> +    convenience init(_ style: SwitchStyle = .default) {
Sure, sounds good.

2022-07-01 12:23 UTC, BrzozowskiPawel commented on WireCommonComponents/SemanticColors.swift
> +enum SemanticColors {
this is probably becasue of the merge. I will check it and delete the extra one.

2022-07-01 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5722) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: BrzozowskiPawel<br/>:x: KaterinaWire<br/>:x: agisilaos<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=5722) it.</sub>

2022-07-04 08:22 UTC, agisilaos commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        public static let backgroundSwitchOffStateDisabled = UIColor(light: Asset.gray50, dark: Asset.gray50)
@johnxnguyen @BrzozowskiPawel: So in this case we can just remove the colors for the disabledState and update the tests?

2022-07-04 10:25 UTC, johnxnguyen commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        public static let backgroundSwitchOffStateDisabled = UIColor(light: Asset.gray50, dark: Asset.gray50)
I guess so

2022-07-04 10:30 UTC, johnxnguyen requested changes
I think we should still add the argument label for the switch style and remove unnecessary default values when initializing the switch. I unresolved the relevant conversations.

2022-07-04 10:32 UTC, BrzozowskiPawel commented
@johnxnguyen I was 100% sure that I did it but unfortunately it must have disappeared when I have been merging by mistake.

2022-07-04 11:49 UTC, BrzozowskiPawel commented
All done

2022-07-04 12:23 UTC, merged