feat: apply new color design for search field - ACC-170
wireapp/wire-ios pull request #5739
Opened 2022-06-27 11:26 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

In this PR "searchFields" have been updated to conform to the norms required by the contrast accessibility.

### Issues

I have used the reveal app and also the accessibility inspector to check what are the issues with the contrast and than fix it.

### Causes (Optional)

Mostly the color contrast of the text and background. 

### Solutions

Use semantic color for the fix to make text color dependent on the used theme.

### Testing

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-06-27 13:41 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
> +extension UIImage {
I think we don't need this

2022-06-27 13:41 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
> +extension UISearchBar {
I think we don't need this

2022-06-27 13:41 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/StartUI/StartUI/SearchHeaderViewController.swift
> +        // TMP COLOR CHANGE: UIColor(red: 0.30, green: 0.34, blue: 0.21, alpha: 1.00) but it makes diffrent UI
What does it mean?

2022-06-27 13:42 UTC, KaterinaWire commented on WireCommonComponents/SemanticColors.swift
> +    static let tmpSearchBartextColor = UIColor(light: .black, dark: .white)
We should have another name

2022-06-27 13:46 UTC, BrzozowskiPawel commented on WireCommonComponents/SemanticColors.swift
> +    convenience init(light: UIColor, dark: UIColor) {
<img width="783" alt="image" src="https://user-images.githubusercontent.com/50630878/175956579-8bea038b-adce-4e36-8787-233f1937801d.png">
In the develop branch there is an initializer capable of creating an instance with ColorAsset class and for this case, we just needed a SemanticColor of basic black and white.
That's why I have decided it's the best idea to create a nice-looking extra initializer.

2022-06-28 16:45 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
> +extension UISearchBar {
Don't forget to delete it

2022-06-28 16:51 UTC, KaterinaWire commented on WireCommonComponents/SemanticColors.swift
> +            switch ColorScheme.default.variant {
Try to replace switch with this:
self.init.from(scheme: .iconSelected, variant: ColorScheme.default.variant)

2022-06-28 16:54 UTC, KaterinaWire commented on WireCommonComponents/SemanticColors.swift
> +    static let defaultSearchBarTextColor = UIColor(light: .black, dark: .white)
I think we can create some static property for black and white semantic color. I don't think we should create an initializer for just one black and white case.

2022-06-29 10:53 UTC, agisilaos requested changes
Let's take care of Katerina's comments first. Looking good. I left some comments.

2022-06-29 10:53 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
> +extension UISearchBar {
@BrzozowskiPawel I don't think that this has been resolved? Can you please delete it?

2022-06-29 10:53 UTC, agisilaos commented on WireCommonComponents/SemanticColors.swift
> +    static let defaultSearchBarTextColor = UIColor(light: Asset.black, dark: Asset.white)
Is this referring to the placeholder or the user's input?

2022-06-29 10:54 UTC, BrzozowskiPawel commented on WireCommonComponents/SemanticColors.swift
> +    static let defaultSearchBarTextColor = UIColor(light: Asset.black, dark: Asset.white)
@agisilaos User input.

2022-07-01 08:48 UTC, agisilaos approved these changes

2022-07-01 12:20 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
> +extension UISearchBar {
I've unresolved this, @BrzozowskiPawel please address this when you can.

2022-07-04 10:32 UTC, johnxnguyen reviewed
I still see an unresolved conversation from Katerina, what is the status on that? Do we need to delete that code or not?

2022-07-04 11:02 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Components/Giphy/GiphySearchViewController.swift
> +extension UISearchBar {
@agisilaos @johnxnguyen I see it but the UISearchBar extension is necessary I guess. It was about the "func imageWithColor()" as I understood and it's gone.

2022-07-04 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5739) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5739) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: BrzozowskiPawel<br/>:white_check_mark: agisilaos<br/>:x: KaterinaWire<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=5739) it.</sub>

2022-07-05 06:46 UTC, merged