fix: `StatusBarOrientation`, `Getter for scrollIndicatorInsets`, `showsPointsOfInterest`, `gray` deprecation warnings
wireapp/wire-ios pull request #5746
Opened 2022-06-29 10:23 UTC by agisilaos

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

With this PR we fix deprecation warnings related to: 

- 'showsPointsOfInterest' was deprecated in iOS 13.0: Use pointOfInterestFilter
- Getter for 'scrollIndicatorInsets' was deprecated in iOS 13.0: The scrollIndicatorInsets getter is deprecated, use the verticalScrollIndicatorInsets and horizontalScrollIndicatorInsets getters instead.
- 'statusBarOrientation' was deprecated in iOS 13.0: Use the interfaceOrientation property of the window scene instead.
- gray' was deprecated in iOS 13.0: renamed to 'UIActivityIndicatorView.Style.medium'

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-06-30 09:50 UTC, ghuMustafa approved these changes

2022-06-30 09:50 UTC, ghuMustafa commented on Wire-iOS/Sources/UserInterface/Camera/CameraController.swift
> +        let ui = UIApplication.shared.windows.first!.windowScene!.interfaceOrientation
Here we might go for optional chaining for more safe unwrapping with unknown orientation, and same for the other places where it's used.
```suggestion
        let ui = UIApplication.shared.windows.first?.windowScene?.interfaceOrientation ?? .unknown
```

2022-07-01 08:07 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Camera/CameraController.swift
> +        let ui = UIApplication.shared.windows.first!.windowScene!.interfaceOrientation
Done!

2022-07-01 08:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5746) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5746) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=5746) it.</sub>

2022-07-01 14:13 UTC, johnxnguyen requested changes

2022-07-01 14:13 UTC, johnxnguyen commented on Wire-iOS/Sources/Helpers/UIWindow+Orientation.swift
> +    }
There are two issues here:
1. Code duplication
2. If `UIWindow.isLandscape` returns false, you would like interpret that as meaning it's in portrait mode, although it could really mean that there is no window or window scene currently available.

I suggest something like:


```swift
extension UIWindow {

  static var interfaceOrientation: UIInterfaceOrientation? {
    return UIApplication
      .shared
      .windows
      .first?
      .windowScene?
      .interfaceOrientation
  }

}

```

Then call it like:

```Swift
UIWindow.interfaceOrientation?.isPortrait
```

2022-07-01 14:13 UTC, johnxnguyen commented on Wire-iOS/Sources/Helpers/UIWindow+Orientation.swift
> +    }
You could also return an `.unknown` orientation to make it non optional.

2022-07-01 14:13 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/Components/OrientableView.swift
> +        layout(forInterfaceOrientation: UIApplication.shared.windows.first?.windowScene?.interfaceOrientation ?? .unknown,
More code duplication here.

2022-07-01 14:13 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Camera/CameraController.swift
> +        let ui = UIApplication.shared.windows.first?.windowScene?.interfaceOrientation ?? .unknown
More duplication here.

2022-07-01 14:13 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Components/UINavigationBarContainer.swift
> +        let orientation = UIApplication.shared.windows.first?.windowScene?.interfaceOrientation ?? .unknown
More duplication.

2022-07-01 14:13 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Helpers/OrientationDelta.swift
> +    init(interfaceOrientation: UIInterfaceOrientation = UIApplication.shared.windows.first?.windowScene?.interfaceOrientation ?? .unknown,
More duplication

2022-07-07 06:55 UTC, johnxnguyen commented on Wire-iOS/Sources/UserInterface/Helpers/KeyboardHeight.swift
> +            return UIWindow.interfaceOrientation!.isPortrait ? 264 : 352
Better to default to portrait if the interface orientation doesn't exist rather than risking a crash due to the force unwrap.

2022-07-07 07:23 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Helpers/KeyboardHeight.swift
> +            return UIWindow.interfaceOrientation!.isPortrait ? 264 : 352
Done @johnxnguyen!

2022-07-07 07:32 UTC, johnxnguyen approved these changes

2022-07-07 07:42 UTC, merged