feat: apply new colors in settings screen- ACC-225
wireapp/wire-ios pull request #5790
Opened 2022-07-28 10:06 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Updated color for the new Figma design in the settings screen.

### Issues

The colors and design were outdated.

### Solutions

Changing the properties to match the new design.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-08-02 15:01 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/ChangingDetails/ConfirmPhoneViewController.swift
> -                cell.titleColor = UIColor(white: 1, alpha: 0.4)
You can simplify this:
cell.selectionStyle = resendEnabled ? .default : .none

2022-08-02 15:03 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientColorVariantProtocol.swift
> +            view.backgroundColor = SemanticColors.Background.settingsView
view.backgroundColor = (variant == .none) ? .clear : SemanticColors.Background.settingsView

2022-08-02 15:04 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +
Swift lint issue

2022-08-02 15:05 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +                iconImageView.setTemplateIcon(icon, size: .tiny)
Why not `iconImageView.setIcon(icon, size: .tiny, color: SemanticColors.LabelsColor.textLabelSettingsCell)` ?

2022-08-02 15:06 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +                iconImageView.setTemplateIcon(icon, size: .tiny)
Agis suggested this approach as when we use the setIcon() it's not auto updating when the user changes the theme.

2022-08-02 15:07 UTC, KaterinaWire commented
@BrzozowskiPawel I saw in `ConversationOptionsViewControllerTests` that only a few cells have separators? Is it correct?

2022-08-02 15:08 UTC, KaterinaWire commented
@BrzozowskiPawel @agisilaos  Shouldn't the cells in `ClientListViewControllerTests` have a white background in the light mode?

2022-08-02 17:22 UTC, BrzozowskiPawel commented
@KaterinaWire 
1. Yes there was an issue. Other cells should have also different UI. This was a screen that is entered thru messages. Besides of that somehow I was not able to have this sharing link on the simulator but I am fixing it already.
2. Yes this is also a valid case. I could not find this cell inside the fimga's preferences or conversation but I have finally found it and applied new design.

2022-08-04 11:05 UTC, agisilaos requested changes
I left some comments regarding to how we set the color for icons. Let's fix those first before making the PR ready to be merged.

2022-08-08 12:33 UTC, agisilaos approved these changes

2022-08-10 15:19 UTC, KaterinaWire commented on Wire-iOS Tests/DeviceManagement/ClientListViewControllerTests.swift
> +                                        credentials: nil,
Do we need these changes?

2022-08-10 15:27 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
> +                cell.isTransparent = variant == .none ? true : false
```suggestion
                cell.isTransparent = variant == .none
```

2022-08-10 15:27 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/SettingsClientViewController.swift
> +                cell.isTransparent = variant == .none ? true : false
```suggestion
                cell.isTransparent = (variant == .none)
```

2022-08-10 15:29 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> -            topSeparatorLine.isHidden = !isFirst
Why don't we need this logic?

2022-08-11 12:12 UTC, BrzozowskiPawel commented
Requested changes applied.

2022-08-12 07:59 UTC, KaterinaWire commented on Wire-iOS Tests/ChangeEmailViewControllerTests.swift
> +
Swift lint issue and commented code

2022-08-12 08:01 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
> +            let image = UIImage(systemName: "chevron.right")
Why do we need this?

2022-08-12 08:03 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/DeviceManagement/ClientListViewController.swift
> +            let image = UIImage(systemName: "chevron.right")
Don't we have a helper method `showDisclosureIndicator()` ?

2022-08-12 12:28 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let textSettingsPasswordPlaceholder = UIColor(light: Asset.gray70, dark: Asset.gray60)
We will use the placeholder color not only for settings. I would use the same as for SearchBar: `textInputViewPlaceholder`

2022-08-12 12:42 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/UIView+Borders.swift
> +    func addTopBorder(color: UIColor) {
I would create a generic method addBorder(...) with a parameter indicating what exactly the board is. As a result, we don't need to create a separate method for each border and duplicate code. I think we can define a default color as `SemanticColors.View.backgroundSeparatorCell` with a possibility to set any other color.

2022-08-12 12:44 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Availability/TitleView.swift
> +            color: SemanticColors.Icon.foregroundPlainDownArrow).withRenderingMode(.alwaysTemplate)
Why do we need `withRenderingMode(.alwaysTemplate) `?

2022-08-15 08:52 UTC, KaterinaWire approved these changes

2022-08-15 08:58 UTC, merged