feat: apply new colors in conversations list - ACC-226
wireapp/wire-ios pull request #5792
Opened 2022-08-02 20:58 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

----

# What's new in this PR?

Apply new color (without changing UI of elements) for the conversation list.
### Issues

### Solutions

Apply fimga design for the elements to change it's appearance (color).

### Testing

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-08-05 08:39 UTC, agisilaos requested changes
Left some comments and questions.

2022-08-05 08:39 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            tintColor = SemanticColors.LabelsColor.conversationListTableCellBadge
`SemanticColors.LabelsColor.conversationListTableCellBadge` is being used multiple times in this file. Instead you can create a `var iconTintColor = SemanticColors.LabelsColor.conversationListTableCellBadge` and use that variable.

2022-08-05 08:39 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            iconView.setTemplateIcon(.bellWithStrikethrough, size: iconSize)
It would be better to put the code where we set the icon and the tintColor together

```
iconView.setTemplateIcon(.bellWithStrikethrough, size: iconSize)
iconView.tintColor = SemanticColors.LabelsColor.textLabelSettingsCellBadgeReverted
```

2022-08-05 08:39 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
> +        self.tintColor = SemanticColors.LabelsColor.textLabelConversationListCell
What's this tintColor for?

2022-08-05 08:39 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
> +        imageView.setTemplateIcon(.downArrow, size: .tiny)
I don't see setting the tintColor for the imageView? Any reason why?

2022-08-05 08:39 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.swift
> -        subtitleField.textColor = .whiteAlpha64
Where we set the color for the subtitleView?

2022-08-05 09:15 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            tintColor = SemanticColors.LabelsColor.conversationListTableCellBadge
Good idea. Implemented.

2022-08-05 09:18 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            iconView.setTemplateIcon(.bellWithStrikethrough, size: iconSize)
Yes. Sorry it was like this and I inserted the border code there by accident. Should be below.

2022-08-05 09:21 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
> +        self.tintColor = SemanticColors.LabelsColor.textLabelConversationListCell
For. the arrow icon. It's in the wrong place and after your comments yesterday there should be not self but imageView.tintColor()....

2022-08-05 09:22 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListContentController/ConversationListHeaderView.swift
> +        imageView.setTemplateIcon(.downArrow, size: .tiny)
Yes, the comments above. I have put in the init instead of the computed property. Also, it should be called on the imageView instead of the self. I have fixed it and it should be good now.

2022-08-05 09:25 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListItemView.swift
> -        subtitleField.textColor = .whiteAlpha64
It's in the line 46. But I will add it here also to set it up also with the proper value. Before we were using a formatted stating to update the test and there I was taking sure that it was the valid color of the string. Should be more clear now.

2022-08-05 09:31 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            tintColor = SemanticColors.LabelsColor.conversationListTableCellBadge
After thinking I will put the tint color before the switch and only if this needs to be changed (like join or silence) I will update it and otherwise the color is the same for the rest of the badges to it can be set "default".

2022-08-08 13:45 UTC, agisilaos approved these changes

2022-08-15 10:58 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/BordersExtension.swift
> +
@agisilaos This file name should be as in develop branch

2022-08-15 11:00 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/BordersExtension.swift
> +public extension UIView {
@agisilaos Please remove this file, we don't need it anymore

2022-08-15 11:04 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/UIView+Borders.swift
> +    func addBottomBorderWithInset(color: UIColor, inset: CGFloat) {
@agisilaos  We should use addBorder(...) instead of `addBottomBorderWithInset(color: UIColor)` and `addBottomBorderWithInset(color: UIColor, inset: CGFloat)` . Could you please make changes?

I think we can change the existing method:
```
func addBorder(
        for anchor: Anchor,
        color: UIColor = SemanticColors.View.backgroundSeparatorCell,
        width: CGFloat = 1.0, 
        inset: ....)

```

2022-08-15 11:05 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Components/Controllers/ClearBackgroundNavigationController.swift
> +import WireCommonComponents
We don't need changes in this file, could you change them back and we will have less files in this PR?

2022-08-15 11:06 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation Options/ConversationGuestOptionsViewController.swift
> +        view.backgroundColor = SemanticColors.View.backgroundDefault
We don't need it. We set a background color in `setupViews()`

2022-08-15 11:09 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationListBottomBar.swift
> +            button.setIconColor(SemanticColors.Label.textConversationListCell, for: .normal)
Shouldn't we set button colors in the style for each state?

2022-08-15 11:10 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Conversation/ConversationListBottomBar.swift
> +        view.backgroundColor = SemanticColors.View.backgroundConversationList
Could you move it on the top to `separator.backgroundColor`?

2022-08-15 11:13 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
> +        view = UIView(frame: UIScreen.main.bounds)
Why do we need these changes?

2022-08-15 11:16 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
> +        self.view.backgroundColor = SemanticColors.View.backgroundConversationList
Do we really need this here? I don't think we should do that in init method. And we set a color for c`ontentContainer`

2022-08-15 11:17 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/ConversationListTopBarViewController.swift
> +        view.backgroundColor = SemanticColors.View.backgroundConversationList
We shouldn't set color in `init` method

2022-08-15 11:17 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            textLabel.textColor = UIColor.white
Why not semantic color?

2022-08-15 11:18 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            badgeView.backgroundColor = SemanticColors.LegacyColors.strongLimeGreen
We shouldn't use for new UI LegacyColors

2022-08-15 11:20 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            iconView.setTemplateIcon(.bellWithStrikethrough, size: iconSize)
We should apply style here

2022-08-15 11:20 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +                .missedCall:
Do we need this offset?

2022-08-15 11:22 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +    var isTransparent: Bool = false {
Why do we need this?

2022-08-15 11:23 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/UserProfile/Details/Cells/UserPropertyCell.swift
> +        separator.backgroundColor = .clear
All of these configs should be inside `configureSubviews()`

2022-08-15 11:41 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
> +        self.view.backgroundColor = SemanticColors.View.backgroundConversationList
It's a different color for the container and a different one for the view

2022-08-15 11:53 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/Container/ConversationListViewController.swift
> +        view = UIView(frame: UIScreen.main.bounds)
We don't. Putting them back.

2022-08-15 12:40 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListAccessoryView.swift
> +            iconView.setTemplateIcon(.bellWithStrikethrough, size: iconSize)
I don't think we can when it comes to icons.

2022-08-15 12:42 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +    var isTransparent: Bool = false {
We don't!

2022-08-16 07:56 UTC, KaterinaWire approved these changes

2022-08-16 07:57 UTC, merged