fix: Update colors for the onboarding screens ACC-230
wireapp/wire-ios pull request #5814
Opened 2022-08-23 10:29 UTC by KaterinaWire

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Fix the colors for the onboarding screens.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-08-24 07:44 UTC, ghuMustafa approved these changes

2022-08-24 09:46 UTC, BrzozowskiPawel requested changes

2022-08-24 09:46 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListOnboardHint.swift
> +
Meybe we could use `setTemplateIcon()` instead of `setIcon()` and than also set the tint color for the arrowView. 
Then there would be no need for using `traitCollectionDidChange()`.

What do you think about it?

2022-08-24 09:52 UTC, BrzozowskiPawel commented
Snapshots are updated according to the existing code.

2022-08-25 09:25 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/ConversationList/ListContent/ConversationListOnboardHint.swift
> +
Yes, you are right

2022-08-25 10:04 UTC, BrzozowskiPawel approved these changes

2022-08-25 12:04 UTC, merged