feat: fix contrast issue with the no message message in conversation search - ACC - 240
wireapp/wire-ios pull request #5827
Opened 2022-08-31 10:03 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

In this PR I have been working on the no message in conversation search. But after discussion with the design team, there were design problems with cells (it's started to blend in with the background). 
Because of that, I needed to change the color and other properties of also the cells (this is why this PR HAVE TO BE THAT BIG).

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-09-06 07:52 UTC, agisilaos requested changes
There's a couple of wrong snapshots as well as some questions I left for you in the comments . Wrong snapshots such as:

<img width="1552" alt="Screenshot 2022-09-06 at 10 51 10" src="https://user-images.githubusercontent.com/10944108/188578117-6adc1b8f-35c4-4eb6-9046-e820505f16bb.png">

2022-09-06 07:52 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
> +        return 10
Where those numbers come from?

2022-09-06 07:52 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
> +            desiredWidth = 60
Same here

2022-09-06 07:59 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
> +        return 10
This is from the Anette. We shall have max 2 rows for 5 of items.

2022-09-06 07:59 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
> +            desiredWidth = 60
The size of the cell is 60x60 now.

2022-09-06 08:00 UTC, BrzozowskiPawel commented
@agisilaos I will fix these snapshots. 
![image](https://user-images.githubusercontent.com/50630878/188579744-c3f4aac0-11e7-4051-81cc-214f2bdee593.png)
I was not sure about it as it's was other screen but that's not a problem, it will be fixed in a while.

2022-09-06 09:58 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
> +            desiredWidth = 60
Are you sure it will work well with all device sizes if we have fixed cell sizes for images and videos?

2022-09-06 10:01 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
> +        return 10
According to the comment, we have only 2 lines.

2022-09-06 10:04 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let textSettingsPlaceholder = UIColor(light: Asset.gray70, dark: Asset.gray60)
Do we use this color?

2022-09-06 10:11 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let backgroundSearchResultCellSeparator = UIColor(light: Asset.green500Light, dark: Asset.green500Light)
Where do we use `backgroundCollectionTextSearchResult`, `backgroundCollectionsViewController`,  `backgroundSearchResultCellSeparator` ?

2022-09-06 10:14 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let backgroundCollectionCell = UIColor(light: Asset.white, dark: Asset.gray90)
It confuses me that we have so many different backgrounds? Why do we have  `backgroundUserCell = UIColor(light: Asset.white, dark: Asset.gray95)`? Should we have different backgrounds?

2022-09-06 10:16 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Collections/CollectionAudioCell.swift
> +        secureContentsView.layer.cornerRadius = 12
But we specified `cornerRadius` for `view` in the line#83? Is it redundant?

2022-09-06 10:16 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Collections/CollectionFileCell.swift
> +        secureContentsView.layer.cornerRadius = 12
Same

2022-09-06 10:29 UTC, KaterinaWire commented
<img width="404" alt="Screenshot 2022-09-06 at 12 26 12" src="https://user-images.githubusercontent.com/57407805/188612760-e257bdab-24e5-489b-b5b6-b49b6e4d1fb4.png">
@BrzozowskiPawel  They have different cornerRadius

2022-09-06 10:31 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Collections/CollectionsViewController.swift
> +            desiredWidth = 60
I am waiting for final answer from Anette. I will inform you after I get it.

2022-09-06 11:26 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let textSettingsPlaceholder = UIColor(light: Asset.gray70, dark: Asset.gray60)
It's currently unused. Deleted it.

2022-09-06 11:28 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let backgroundSearchResultCellSeparator = UIColor(light: Asset.green500Light, dark: Asset.green500Light)
It must have been added by the accident as I was testing. Delated it.

2022-09-06 11:31 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let backgroundCollectionCell = UIColor(light: Asset.white, dark: Asset.gray90)
Yes because it's done according to Figma:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/50630878/188625176-fdaa5edd-197a-45c7-a076-eb0491d9b1a1.png">

2022-09-06 11:35 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Collections/CollectionAudioCell.swift
> +        secureContentsView.layer.cornerRadius = 12
Yes it's now redundant as the audio cell and secureContensView have the same color so it's at the end it 1 cell. I will fix it in both cases.

2022-09-06 11:35 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Collections/CollectionFileCell.swift
> +        secureContentsView.layer.cornerRadius = 12
Fixed.

2022-09-12 07:35 UTC, agisilaos commented
@BrzozowskiPawel Is this ready for another round of reviews?

2022-09-12 07:36 UTC, BrzozowskiPawel commented
@agisilaos yes. As we discussed the I have changed the UI but no spaces between cells.

2022-09-22 07:48 UTC, agisilaos approved these changes

2023-01-04 13:17 UTC, KaterinaWire approved these changes

2023-01-04 22:17 UTC, merged