feat: create a new color selecting in settings - ACC - 225
wireapp/wire-ios pull request #5837
Opened 2022-09-02 16:42 UTC by BrzozowskiPawel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

In this PR I have added the new color picker. It's redesigned.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-09-06 10:35 UTC, MarcinR requested changes

2022-09-06 10:35 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenCellDescriptor.swift
> +class SettingsExternalScreenColorCellDescriptor: SettingsExternalScreenCellDescriptorType, SettingsControllerGeneratorType {
that should go to separate file

2022-09-06 10:35 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenCellDescriptor.swift
> +    init(title: String,
why do you need two initializers when you're using only one?

2022-09-06 10:35 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Settings/SettingsTableColorCell.swift
> +extension UIColor {
this shouldn't be in cell class file. It's not relevant  only for this cell. Add this to existing UIColor extension file or create new one.

2022-09-06 10:53 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsTableColorCell.swift
> +extension UIColor {
Done.

2022-09-06 11:01 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenCellDescriptor.swift
> +    init(title: String,
Right. I deleted unnecessary.

2022-09-06 11:03 UTC, BrzozowskiPawel commented
@MarcinR all you requested changes are applied.

2022-09-06 12:59 UTC, MarcinR approved these changes

2022-09-08 14:09 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/AccentColorProvider.swift
> +    /// Returns the current accent color of the user.
We don't need this changes

2022-09-08 14:11 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +        private func createCellConstraints() {
```suggestion
        private func createConstraints() {
```

2022-09-08 14:13 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
> +            text: "self.settings.account_picture_group.color".localized,
L10n....

2022-09-08 14:13 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenColorCellDescriptor.swift
> +class SettingsExternalScreenColorCellDescriptor: SettingsExternalScreenCellDescriptorType, SettingsControllerGeneratorType {
Do we need `SettingsExternalScreenColorCellDescriptor` ?

2022-09-08 14:14 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +    case accentColor(AccentColor)
Do we need this?

2022-09-08 14:14 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +            case .accentColor(let accentColor):
Do we need this?

2022-09-08 14:15 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsTableColorCell.swift
> +class SettingsAppearanceCell: SettingsTableCell, CellConfigurationConfigurable {
Please change the file name

2022-09-08 16:55 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +        return false
Do we need this? I don't think that we do.

2022-09-08 19:43 UTC, BrzozowskiPawel commented
@KaterinaWire @agisilaos 
Thank you for the comments. I needed to go for the meeting in the AU and that's why I didn't finish it. I am fixing and finishing it now.

2022-09-08 19:51 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/Helpers/AccentColorProvider.swift
> +    /// Returns the current accent color of the user.
Done.

2022-09-08 19:52 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory+Account.swift
> +            text: "self.settings.account_picture_group.color".localized,
Done.

2022-09-08 19:52 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +        private func setupCellViews() {
Done.

2022-09-08 19:53 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsExternalScreenColorCellDescriptor.swift
> +class SettingsExternalScreenColorCellDescriptor: SettingsExternalScreenCellDescriptorType, SettingsControllerGeneratorType {
No. After the code redesign, it's not necessary. I have deleted it.

2022-09-08 19:54 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +    case accentColor(AccentColor)
No. The same as before I am cleaning it up now after the redesing. It's delted.

2022-09-08 19:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +    let imagePreview: UIImageView = {
Done.

2022-09-08 19:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +            case .accentColor(let accentColor):
Delted.

2022-09-08 19:56 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsTableColorCell.swift
> +class SettingsAppearanceCell: SettingsTableCell, CellConfigurationConfigurable {
Done.

2022-09-08 19:57 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsTableColorCell.swift
> +
Done.

2022-09-08 19:57 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +        return false
It's not relevant but as there is no purpose in it yes it's better to delate it. Done.

2022-09-08 20:15 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +        return false
You are right. It's the default. It's strange because it seems like I added it and I am sure that I didn't change it. Delted.

2022-09-09 13:49 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +    let badgeLabel: UILabel = {
Why not private?

2022-09-09 13:50 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/SettingsAppearanceCell.swift
> +    let subtitleLabel: UILabel = {
```suggestion

    let subtitleLabel: UILabel = {
```

2022-09-09 13:51 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    var text: String
```suggestion
    private var text: String
```

2022-09-09 13:51 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let appearanceType: AppearanceType
```suggestion
    private let appearanceType: AppearanceType
```

2022-09-09 13:51 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let presentationAction: () -> (UIViewController?)
private ?

2022-09-09 14:07 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    func colorPicker(_ colorPicker: ColorPickerController, didSelectColor color: AccentColorOption)
```suggestion
    func colorPicker(_ colorPicker: ColorPickerController, didSelectColor color: AccentColor)
```

2022-09-09 14:08 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +class AccentColorOption: Equatable {
I don't think we need `AccentColorOption`

2022-09-09 14:09 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    var selectedColor: AccentColor?
```suggestion
    let colors: [AccentColor]
    var selectedColor: AccentColor?
```

2022-09-09 14:09 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    let colors: [AccentColorOption]
```suggestion
    let colors: [AccentColor]
```

2022-09-09 14:09 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    init(colors: [AccentColorOption]) {
```suggestion
    init(colors: [AccentColor]) {
```

2022-09-09 14:16 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +            contentView.addSubview(colorNameLabel)
```suggestion
            [colorView, checkmarkView, colorNameLabel].forEach {
                contentView.addSubview($0)
            }
```

2022-09-09 14:17 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +        cell.colorNameLabel.text = colors[indexPath.row].accentColor.name
```suggestion
        cell.color = colors[indexPath.row]
        cell.colorNameLabel.text = colors[indexPath.row].name
```

2022-09-09 14:18 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    func colorPicker(_ colorPicker: ColorPickerController, didSelectColor color: AccentColorOption) {
```suggestion
    func colorPicker(_ colorPicker: ColorPickerController, didSelectColor color: AccentColor) {
```

2022-09-09 14:30 UTC, agisilaos approved these changes

2022-09-11 17:19 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsCell.swift
> +    let badgeLabel: UILabel = {
Fixed. I was researching a different approach and I accidentally left it.

2022-09-11 17:19 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/SettingsAppearanceCell.swift
> +    let subtitleLabel: UILabel = {
Fixed.

2022-09-11 17:27 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    var text: String
Fixed.

2022-09-11 17:27 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let appearanceType: AppearanceType
Fixed.

2022-09-11 17:27 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let presentationAction: () -> (UIViewController?)
Yes. Fixed.

2022-09-11 17:33 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +            contentView.addSubview(colorNameLabel)
Fixed.

2022-09-11 17:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    func colorPicker(_ colorPicker: ColorPickerController, didSelectColor color: AccentColorOption)
Done.

2022-09-11 17:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +class AccentColorOption: Equatable {
Done.

2022-09-11 17:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    let colors: [AccentColorOption]
Done.

2022-09-11 17:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    init(colors: [AccentColorOption]) {
Done.

2022-09-11 17:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +        cell.colorNameLabel.text = colors[indexPath.row].accentColor.name
Done.

2022-09-11 17:55 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/AccentColorPickerController.swift
> +    func colorPicker(_ colorPicker: ColorPickerController, didSelectColor color: AccentColorOption) {
Done.

2022-09-11 17:57 UTC, BrzozowskiPawel commented
Deleted '''AccentColorOption''' class. Now the app is using basic '''AccentColor'''.

2022-09-12 07:25 UTC, KaterinaWire commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let presentationAction: () -> (UIViewController?)
Should it be private or no? It's no private now

2022-09-12 07:39 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let presentationAction: () -> (UIViewController?)
I dont know why it's dispalting like this but it's private.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/50630878/189598745-7850a06f-6479-402d-a660-6e450f3ebc8a.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/50630878/189598789-19b42fd7-f0d2-4cce-a2ff-38826f29e366.png">

2022-09-12 07:54 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let presentationAction: () -> (UIViewController?)
@BrzozowskiPawel I think we're referring o the presentationAction and the presentationAction should be private.

2022-09-12 08:29 UTC, BrzozowskiPawel commented on Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsAppearanceCellDescriptor.swift
> +    let presentationAction: () -> (UIViewController?)
@agisilaos @KaterinaWire it cannot be private because it's a part of the protocol.
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/50630878/189607121-752f0c5b-45bd-406a-a5be-4e9c1b2fbe5e.png">

Also we have implemented it the same way in other wire files, for example: **SettingsExternalScreenCellDescriptor**.

2022-09-12 08:32 UTC, KaterinaWire approved these changes

2022-09-12 11:09 UTC, merged