feat: simple nse step2 cleanup, tests SQSERVICES-1700
wireapp/wire-ios pull request #5888
Opened 2022-09-30 12:49 UTC by MarcinR

#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

2022-10-05 12:40 UTC, marcoconti83 requested changes

2022-10-05 12:40 UTC, marcoconti83 commented on Wire Notification Service Extension/Simple/Helpers/EventDecodingProtocol.swift
> +    func decryptAndStoreEvents(events: [ZMUpdateEvent]) async -> [ZMUpdateEvent] {
It would make error detection easier if we pass in one event only, so that we don't need to rely on the array being empty to detect issues, as 8 out of 10 events might fail to decrypt, but this means that the output array is still not empty and it would be erroneously considered a success.

2022-10-05 12:40 UTC, marcoconti83 commented on Wire Notification Service Extension/Simple/SimpleNotificationService.swift
> +                let eventDecoder =   EventDecoder(eventMOC: coreDataStack.eventContext, syncMOC: coreDataStack.syncContext)
```suggestion
                let eventDecoder = EventDecoder(eventMOC: coreDataStack.eventContext, syncMOC: coreDataStack.syncContext)
```

2022-10-06 09:01 UTC, MarcinR commented on Wire Notification Service Extension/Simple/Helpers/EventDecodingProtocol.swift
> +    func decryptAndStoreEvents(events: [ZMUpdateEvent]) async -> [ZMUpdateEvent] {
👍

2022-10-11 12:35 UTC, marcoconti83 approved these changes

2022-10-12 08:27 UTC, merged