feat: simple-nse step4  SQSERVICES-1700
wireapp/wire-ios pull request #5905
Opened 2022-10-11 06:37 UTC by MarcinR

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability

2022-10-11 12:38 UTC, marcoconti83 requested changes

2022-10-12 09:06 UTC, marcoconti83 requested changes
Overall looks good, but I left some comments. 

In order to get the big picture, could you please edit the PR description to specify what is the purpose of this PR? Same like we did for https://github.com/wireapp/wire-ios/pull/5888. 
I.e., Is this PR implementing Step 4 entirely? Is it only a part of it, and more work need to follow? If so, what part is this PR addressing?

2022-10-12 09:49 UTC, MarcinR commented on Wire Notification Service Extension/Simple/Helpers/EventMessageExtractor.swift
> -    func extractMessage(fromDecodedEvent event: ZMUpdateEvent) throws -> String {
I removed EventMessageExtractor and create NotificationContentProvider. GenericMessage is created in ZMLocalNotification class

2022-10-12 09:50 UTC, MarcinR commented on Wire-iOS.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "Wire iOS Development Debug";
yes, that shouldn't be here. I removed it in step3 PR, but it wasn't mergered to this branch yet

2022-10-12 10:36 UTC, MarcinR commented on Wire Notification Service Extension/Simple/Helpers/EventMessageExtractor.swift
> -    func extractMessage(fromDecodedEvent event: ZMUpdateEvent) throws -> String {
also this whole step4

2022-10-12 10:36 UTC, merged