feat: add call events handling - SQSERVICES-1700
wireapp/wire-ios pull request #5927
Opened 2022-10-27 21:38 UTC by MarcinR

This pull requests implements Phase 4 from the [new notification extension plan](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/647725130/Notification+Service+Extension+2.0).
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability

2022-10-31 13:16 UTC, marcoconti83 requested changes
I left a few questions to answer before merging

2022-10-31 13:16 UTC, marcoconti83 commented on Wire-iOS Tests/Notification Service Extension/SimpleNotificationServiceExtension/JobTests.swift
> +}
There's a linter warning here

2022-10-31 13:16 UTC, marcoconti83 commented on Wire Notification Service Extension/Simple/Helpers/CallEventHandler.swift
> +        guard VoIPPushHelper.isAVSReady else {
I'm a bit worried about this one. If AVS is not ready (I'm not sure what that means), we will return false, therefore ignoring the call event completely.

What does it mean for AVS to be ready? 

If we ignore this event because we are not ready, 
1) what will the user see? No notification? A text notification? 
2) will iOS penalize us for receiving notifications but not invoking CallKit? 

Probably 2) is not a problem because we did not invoke `CXProvider.reportNewIncomingVoIPPushPayload` yet, right? @KaterinaNikolaenko

2022-10-31 13:16 UTC, marcoconti83 commented on Wire Notification Service Extension/Simple/Job.swift
> +            return .empty
If we return `.empty`, does it mean no notification is displayed? (which will be OK because the main app might invoke CallKit later).

2022-11-04 12:35 UTC, MarcinR commented on Wire-iOS Tests/Notification Service Extension/SimpleNotificationServiceExtension/JobTests.swift
> +}
fixed

2022-11-04 12:47 UTC, MarcinR commented on Wire Notification Service Extension/Simple/Job.swift
> +            return .empty
Correct. No PushNotification displayed

2022-11-08 09:10 UTC, marcoconti83 commented on Wire Notification Service Extension/Simple/Helpers/CallEventHandler.swift
> +        guard VoIPPushHelper.isAVSReady else {
Thanks, that makes sense!

2022-11-08 09:11 UTC, marcoconti83 approved these changes
Thanks for addressing the comments, @MarcinR !

2022-11-08 10:50 UTC, merged