Feature/api proxy support
wireapp/wire-ios pull request #5962
Opened 2022-11-22 15:25 UTC by netbe

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-11-22 15:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5962) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=5962) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: netbe<br/>:x: tmspzz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=5962) it.</sub>

2022-11-22 16:22 UTC, netbe commented on main.swift
> +setenv("CFNETWORK_DIAGNOSTICS", "3", 1)
to remove ?

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+LandingScreen.swift
> +    }
```swift
    // I would break this down into two functions

    private var shouldShowProxyAlert: Bool {
        BackendEnvironment.shared.proxy != nil
    }
    
    private func showProxyAlert(title: String, message: String) -> Bool {
        let alert = AuthenticationCoordinatorAlert(
            title: title,
            message: message,
            actions: [.ok]
       )
       executeActions([.presentAlert(alert)])
    }

    // and then use it like that

    func landingViewControllerDidChooseCreateAccount() {
       typealias Alert =  L10n.Localizable.Landing.Alert.CreateNewAccount.NotSupported

       guard !shouldShowProxyAlert else {
          return showProxyAlert(title: Alert.title, message: Alert.message)
       }

       let unregisteredUser = makeUnregisteredUser()
       stateController.transition(to: .createCredentials(unregisteredUser))
   }
```

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
> +        }
```suggestion
        if shouldUseScrollView {
            view = UIScrollView()
        } else {
            view = UIView()
        }
```

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
> +                self.replaceView()
do we need a `weak` self?

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Interface/ViewControllers/AuthenticationCredentialsViewController.swift
> +        if let navController = self.navigationController {
Personally, I prefer returning early with a `guard` instead of using an `if`

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Interface/Views/CustomBackendView.swift
> +        backendLabel.centerYAnchor.constraint(equalTo: self.centerYAnchor).isActive = true
For constraints, you can use `NSLayoutConstraint.activate([])` to avoid having to set `isActive` to true for each constraint.

**example:**
```swift
NSLayoutConstraint.activate([
   backendLabel.centerXAnchor.constraint(equalTo: self.centerXAnchor, constant: -imageSize/2),
   backendLabel.leadingAnchor.constraint(greaterThanOrEqualTo: self.leadingAnchor)
   // ...
])
```

We also tend to have a separate function for constraints, such as `activateConstraints()`, that we call after `setupViews()` 

---

You can also do this for `translatesAutoresizingMaskIntoConstraints`
```swift
[view1, view2, view3].forEach { $0.translatesAutoresizingMaskIntoConstraints = false }
// or 
[view1, view2, view3].prepareForLayout() // it's a custom helper method that does the same
```

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Interface/Views/ProxyCredentialsViewController.swift
> +        let label = DynamicFontLabel(text: L10n.Localizable.ProxyCredentials.title, fontSpec: .headerSemiboldFont, color: SemanticColors.Label.textCellSubtitle)
you can create a typealias for `L10n.Localizable.ProxyCredentials` since it's used quite a few times in this class

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
> +// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. dsSee the
```suggestion
```

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
> +        print(#function)
leftover debug print?

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
> +        subMessageLabel.text = "landing.welcome_submessage".localized
let's use the autogenerated `L10n` types here :)

2022-12-19 14:43 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationShowCustomBackendInfoHandler.swift
> +}
should this be moved in the implementation of `AuthenticationShowCustomBackendInfoHandler` so it can act as a namespace? (`AuthenticationShowCustomBackendInfoHandler.Intent` instead of `Intent`)

2022-12-21 08:57 UTC, netbe commented on Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationShowCustomBackendInfoHandler.swift
> +}
ok

2023-01-09 13:32 UTC, agisilaos requested changes
Left some comments and questions, let's take care of those before merging. Also, let's fix the SwiftLint warnings before merging that PR. We can easily do so by running `swiftlint --fix` on the terminal

2023-01-09 13:32 UTC, agisilaos commented on Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+LandingScreen.swift
> +            env.backendURL.absoluteString
We can have a single typealias here like:

```swift
typealias CustomBackendAlert = L10n.Localizable.Landing.CustomBackend.Alert
```

and use it in many places in that file

2023-01-09 13:32 UTC, agisilaos commented on Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationShowCustomBackendInfoHandler.swift
> +/**
Let's get rid of those lines

2023-01-09 13:32 UTC, agisilaos commented on Wire-iOS/Sources/Authentication/Interface/Descriptions/ViewDescriptions/PrimaryButtonDescription.swift
> +        let button = IconButton(fontSpec: .normalSemiboldFont)
The fontSpec for that button needs to be `.buttonBigSemibold` please check https://github.com/wireapp/wire-ios/pull/6054/files

2023-01-09 13:32 UTC, agisilaos commented on Wire-iOS/Sources/Authentication/Interface/Descriptions/ViewDescriptions/PrimaryButtonDescription.swift
> +        button.setTitle(title.localizedUppercase, for: .normal)
Are we sure that it needs to be Uppercase and not capitalized?

2023-01-09 13:32 UTC, agisilaos commented on Wire-iOS/Sources/Authentication/Interface/Descriptions/ViewDescriptions/LogOutViewDescription.swift
> -}
This isn't being used anywhere?

2023-01-09 13:32 UTC, agisilaos commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let separator = UIColor(light: Asset.Colors.gray50, dark: Asset.Colors.gray80)
May I suggest a more descriptive name for that color? Something like:

```suggestion
        static let backgroundSeparator = UIColor(light: Asset.Colors.gray50, dark: Asset.Colors.gray80)
```

Also the fact that we need a new color for the separator feels a bit weird since we already have a color for that. Let's quickly ask Anette about that and remove that color if necessary.

2023-01-09 13:35 UTC, netbe commented on Wire-iOS/Sources/Authentication/Interface/Descriptions/ViewDescriptions/LogOutViewDescription.swift
> -}
no it was not even inside the Xcode project if I recall correctly

2023-01-09 13:47 UTC, johnxnguyen commented on Wire-iOS.xcodeproj/project.pbxproj
> +				01BAAD2629361F8100774A4F /* (null) in Sources */,
Do you know what this is?

2023-01-09 13:52 UTC, netbe commented on Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+LandingScreen.swift
> +            env.backendURL.absoluteString
used it and moved under enum as there were twice the same code

2023-01-09 13:53 UTC, netbe commented on Wire-iOS.xcodeproj/project.pbxproj
> +				01BAAD2629361F8100774A4F /* (null) in Sources */,
not sure, maybe a ref that was left after project setup with other frameworks

2023-01-09 13:57 UTC, David-Henner approved these changes
LGTM, just left a few formatting suggestions

2023-01-09 13:57 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+LandingScreen.swift
> +    }
```suggestion
    var proxyCredentials: ProxyCredentials? {
        return proxy.flatMap { proxy in
            ProxyCredentials.retrieve(for: proxy) 
        }
    }
```

2023-01-09 13:57 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Coordinator/Coordinator+Delegates/AuthenticationCoordinator+LandingScreen.swift
> +        }
```suggestion
        proxyCredentials.flatMap { 
            AuthenticationProxyCredentialsInput(username: $0.username, password: $0.password)
        }
```

2023-01-09 13:57 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Event Handlers/Input/AuthenticationShowCustomBackendInfoHandler.swift
> +                                    actions: [.ok]))]
Suggestion to make a typealias such as 
```
typealias Alert = L10n.Localizable.Landing.CustomBackend.Alert
```

To use like below
```suggestion
        let info = [
            Alert.Message.backendName,
            env.title,
            Alert.Message.backendUrl,
            env.backendURL.absoluteString
        ].joined(separator: "\n")

        return [.presentAlert(.init(title: Alert.title,
                                    message: info,
                                    actions: [.ok]))]
```

2023-01-09 13:57 UTC, David-Henner commented on Wire-iOS/Sources/Authentication/Landing/LandingViewController.swift
> +// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. dsSee the
This is still duplicated

2023-01-09 14:16 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let textFieldLabel = UIColor(light: Asset.Colors.gray80, dark: Asset.Colors.gray50)
I would more specific about the semantic name for this color

2023-01-09 14:20 UTC, KaterinaWire commented on Wire-iOS/Sources/Helpers/SemanticColors.swift
> +        static let separator = UIColor(light: Asset.Colors.gray50, dark: Asset.Colors.gray80)
According to Figma, the separator color should be **light: Asset.Colors.gray40, dark: Asset.Colors.gray90**. @netbe Could you double check? We have `View.backgroundSeparatorCell` for this.

2023-01-09 15:05 UTC, johnxnguyen approved these changes
Also fine for me, but please also address the other reviews before merging.

2023-01-09 15:40 UTC, netbe commented on Wire-iOS/Sources/Authentication/Interface/Descriptions/ViewDescriptions/PrimaryButtonDescription.swift
> +        button.setTitle(title.localizedUppercase, for: .normal)
removed file completely

2023-01-09 15:44 UTC, agisilaos approved these changes

2023-01-09 16:41 UTC, KaterinaWire approved these changes

2023-01-12 08:54 UTC, merged