feat: New calling UI ACC-143
wireapp/wire-ios pull request #5972
Opened 2022-12-01 00:29 UTC by KaterinaWire

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-12-15 10:07 UTC, agisilaos requested changes
I left some comments regarding colors, SwiftGen, SwiftLint. Let's tackle those first before the next round of review.

2022-12-15 10:07 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
> +        view.backgroundColor = UIColor.from(scheme: .callActionBackground, variant: ColorScheme.default.variant)
Here we're setting the background color using the old way of handling the colors. Is there a reason why?

2022-12-15 10:07 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
> +        backgroundColor = UIColor.from(scheme: .callActionBackground, variant: ColorScheme.default.variant)
This is the old way of setting colors. Is there a reason why we don't use SemanticColors?

2022-12-15 10:07 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
> +    }
Can we use L10n here instead of .localized?

2022-12-15 10:07 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/IncomingCallActionsView.swift
> +        backgroundColor = UIColor.from(scheme: .callActionBackground, variant: ColorScheme.default.variant)
Same question about the color here.

2022-12-15 10:07 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
> +    }
Same question about the colors here.

2022-12-15 10:07 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
> +            gridView.backgroundColor = UIColor.from(scheme: .background, variant: ColorScheme.default.variant)
Same question about colors here.

2022-12-15 10:29 UTC, MarcinR commented on Wire-iOS/Generated/Colors+Generated.swift
> -#if canImport(SwiftUI)
done

2022-12-15 10:30 UTC, MarcinR commented on Wire-iOS/Sources/AppRootRouter.swift
> +
done

2022-12-15 10:30 UTC, MarcinR commented on Wire-iOS/Sources/Helpers/ColorScheme.swift
> +
done

2022-12-15 10:37 UTC, MarcinR commented on Wire-iOS/Sources/Helpers/ColorScheme.swift
> +    static var callIconBackgroundDark: UIColor = UIColor(rgba: (23, 24, 26, 1))
done

2022-12-15 10:37 UTC, MarcinR commented on Wire-iOS/Sources/Helpers/ColorScheme.swift
> +    case callActionBackground
done

2022-12-15 10:40 UTC, MarcinR commented on Wire-iOS/Sources/Helpers/ColorScheme.swift
> +            return ColorPair(light: .white, dark: .black)
done

2022-12-15 10:40 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
> +class BottomSheetContainerViewController : UIViewController {
done

2022-12-15 10:41 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallHeaderBar.swift
> +        backgroundColor = SemanticColors.View.backgroundDefault
done

2022-12-15 10:49 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
> +            participantsHeaderLabel.text = L10n.Localizable.Call.Participants.showAll(participants.count).uppercased()
yes, it uppercased on designes

2022-12-15 10:49 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallHeaderBar.swift
> +        avatarView.backgroundColor = SemanticColors.View.backgroundAvatar
done

2022-12-15 10:51 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsInfoViewController/CallingActionsInfoViewController.swift
> +        view.backgroundColor = UIColor.from(scheme: .callActionBackground, variant: ColorScheme.default.variant)
done

2022-12-15 10:51 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
> +        backgroundColor = UIColor.from(scheme: .callActionBackground, variant: ColorScheme.default.variant)
done

2022-12-15 10:52 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/IncomingCallActionsView.swift
> +        backgroundColor = UIColor.from(scheme: .callActionBackground, variant: ColorScheme.default.variant)
done

2022-12-15 11:00 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
> +    }
done

2022-12-15 11:14 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallGridViewController.swift
> +            gridView.backgroundColor = UIColor.from(scheme: .background, variant: ColorScheme.default.variant)
done

2022-12-15 12:27 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
> +    }
we had to keep buttons-related logic that already exist in current callingUI

2023-01-05 12:41 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
> +        titleLabel?.font = DynamicFontLabel(fontSpec: .smallRegularFont, color: SemanticColors.Label.textSectionHeader).font
Can we set the titleLabel as a DynamicFontLabel from the get go? So we don't have to set the font like that here?

2023-01-05 12:44 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
> +        iconButton.setBackgroundImageColor(SemanticColors.Button.backgroundCallingDisabled, for: .disabled)
Here we can create a typealias like I mentioned already and use that instead ofusing  SemanticColors.Button in multiple places. So it would look like:


```swift
typealias ButtonColors = SemanticColors.Button
```

And the use it like:

```swift
ButtonColors.textCallingNormal
```

2023-01-05 12:44 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
> +        iconButton.setBackgroundImageColor(greenColor, for: .normal)
Why we don't use a Semantic Color here?

2023-01-05 12:44 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
> +        iconButton.setBackgroundImageColor(redColor, for: .normal)
Why we don't use a Semantic Color here?

2023-01-05 12:47 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
> +        super.init(contentViewController: visibleVoiceChannelViewController, bottomSheetViewController: callingActionsInfoViewController, bottomSheetConfiguration: .init(height: bottomSheetMaxHeight,
This looks like quite long. Let's try to make it shorter:
```suggestion
        super.init(contentViewController: visibleVoiceChannelViewController, 
                       bottomSheetViewController: callingActionsInfoViewController, 
                       bottomSheetConfiguration: .init(height: bottomSheetMaxHeight, 
                                                                              initialOffset: 128.0))
```

2023-01-05 12:48 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
> +        case .ringingIncoming(_): return true
SwiftLint warning

2023-01-05 12:50 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/IncomingCallActionsView.swift
> +        endCallButton.subtitleTransformLabel.font = FontSpec(.small, .bold).font!
We would like to use the properties within FontSpec.swift file. When setting the fonts try to use the properties from that file. 
```suggestion
        pickUpButton.subtitleTransformLabel.font = FontSpec.smallBoldFont.font!
        endCallButton.subtitleTransformLabel.font = FontSpec.smallBoldFont.font!
```

2023-01-05 12:51 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
> +
These are for the old Calling UI?

2023-01-05 12:52 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
>          }
Same question for the colors here.

2023-01-05 12:54 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
> +                    ? DynamicFontLabel(fontSpec: .mediumRegularFont, color: .white)
Why we don't use a Semantic Color here?

2023-01-05 12:55 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallInfoViewController/CallStatusView.swift
> +
Let's get rid of that line

2023-01-12 12:42 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionsView.swift
> +        [flipCameraButton, cameraButton, microphoneButton, speakerButton, endCallButton, largeHangUpButton, largePickUpButton].forEach { $0.addTarget(self, action: #selector(performButtonAction), for
suggestion to break up this long line 
```suggestion
        [
            flipCameraButton, 
            cameraButton, 
            microphoneButton,
            speakerButton, 
            endCallButton, 
            largeHangUpButton, 
            largePickUpButton
        ].forEach { 
            $0.addTarget(self, action: #selector(performButtonAction), for: .touchUpInside) 
        }
```

2023-01-12 12:42 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
> +            return UIDevice.current.orientation.isLandscape ? 128.0 : 230.0
Seeing that we rely on the device orientation for custom offsets makes me wonder: How does the calling UI look on iPad? Are these offsets accommodating iPhone devices only? Or is iPad also taken into account?

2023-01-12 12:42 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
> +        }
```suggestion
        guard 
            let conversation = ZMUserSession.shared()?.priorityCallConversation,
            visibleVoiceChannelViewController.conversation != conversation,
            let voiceChannel = conversation.voiceChannel 
        else {
            return
        }
```

2023-01-12 12:42 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/EstablishingCallStatusView.swift
> +        [stackView, profileImageView, spaceView].forEach { $0.translatesAutoresizingMaskIntoConstraints = false }
you can use `prepareForLayout()` here

```swift
// From WireCommonComponents/Sequence+layout.swift

extension Sequence where Element == UIView {

    /// set the items in the Sequence translatesAutoresizingMaskIntoConstraints to false
    public func prepareForLayout() {
        forEach { $0.translatesAutoresizingMaskIntoConstraints = false }
    }
}
```


```suggestion
        [stackView, profileImageView, spaceView].prepareForLayout()
```

2023-01-12 12:42 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/IconLabelButton.swift
> +    }
indentation looks off here

2023-01-12 12:42 UTC, David-Henner commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/RoundedPageIndicator.swift
> +            }
indentation looks off here

2023-01-13 10:14 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
> +
second one- yes. First one is deleted

2023-01-13 10:18 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
>          }
deleted

2023-01-13 10:20 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
> +                    ? DynamicFontLabel(fontSpec: .mediumRegularFont, color: .white)
done

2023-01-13 10:21 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
> +    public func didChangeState() {}
it's for overriding in child class. I'm adding comment

2023-01-13 13:53 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingBottomSheetViewController.swift
> +            return UIDevice.current.orientation.isLandscape ? 128.0 : 230.0
yes, layout on ipad was checked. Both landscape and portrait mode.

2023-01-16 09:18 UTC, MarcinR commented on Wire-iOS.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "Wire iOS Development Debug";
removed

2023-01-16 09:25 UTC, MarcinR commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/BottomSheetContainerViewController.swift
> +            visibleControllerBottomConstraint = contentViewController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -configuration.initialOffset)
it should just change constant in this constraint. I'm changing it

2023-01-17 10:52 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/BottomSheetContainerViewController/CallingActionsView/CallingActionButton.swift
> +        iconButton.setBackgroundImageColor(SemanticColors.Button.backgroundCallingDisabled, for: .disabled)
I would suggest using a typealias here:

```swift
typealias ButtonColors = SemanticColors.Button
```

2023-01-17 11:04 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallActionsView/CallActionAppearance.swift
> +        }
Do we still need those colors for the old implementation or we can get rid of those?

2023-01-17 11:09 UTC, agisilaos commented on Wire-iOS/Sources/UserInterface/Calling/CallGridView/CallParticipantViews/CallParticipantDetailView.swift
> +            nameLabel.textColor = .white
Let's try and use semantic colors here as well.

2023-01-17 11:14 UTC, agisilaos reviewed
Left some comments and some questions.

2023-01-17 13:51 UTC, johnxnguyen approved these changes

2023-01-17 18:52 UTC, agisilaos approved these changes

2023-01-18 09:45 UTC, merged