feat: datadog implementation
wireapp/wire-ios pull request #6001
Opened 2022-12-15 11:58 UTC by netbe

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Debug remote builds within extensions and app

### Solutions

Use datadog to see remote logs

### Dependencies (Optional)

Needs releases with:

- [](https://github.com/wireapp/wire-ios-transport/pull/260)

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

* Run the app and see logs on Datadog

### Notes (Optional)

It needs Datadog.xcconfig inside your configuration to work with the following keys:

```
// Datadog
DATADOG_IMPORT=1
DATADOG_APP_ID=<you app id here>
DATADOG_CLIENT_TOKEN=<you client token here>
```

+ developer flag datadog should be enabled otherwise it does not log (it will still run the automatic tracking Views and events if not enabled)

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-12-15 12:17 UTC, netbe commented on Wire-iOS/Sources/Managers/DatadogWrapper.swift
> +    // TODO: check if implemented in lower frameworks - check WireUtilities
@tmspzz so far I don't see similar code, is it better to move it to WireUtilities, or fine to keep it here for now?

2022-12-15 13:11 UTC, tmspzz requested changes
Overall it looks good, however there is a crucial bit missing:

both the import and the use of DataDog has to be made conditional to a build flag so that there is no trace of it in public releases to the store

2022-12-19 08:27 UTC, netbe commented on Cartfile.resolved
> +github "microsoft/plcrashreporter" "1.11.0"
Should this be included in the build? it does not seem to be required.

2022-12-19 08:28 UTC, netbe commented on Wire Notification Service Extension/NotificationService.swift
> +import Datadog
done `DATADOG_IMPORT = 1` should be defined in DATADOG.xcconfig

2022-12-19 08:36 UTC, tmspzz approved these changes

2022-12-20 14:45 UTC, johnxnguyen approved these changes

2022-12-20 14:45 UTC, johnxnguyen commented on Cartfile.resolved
> +github "microsoft/plcrashreporter" "1.11.0"
So this is being pulled in by data dog?

2022-12-20 14:45 UTC, johnxnguyen commented on Wire Notification Service Extension/LegacyNotificationService.swift
> +      DatadogWrapper.shared()?.log(level: .debug, message: message)
This will lead to duplicate logs, since it's called by the previous method.

2022-12-20 14:45 UTC, johnxnguyen commented on Wire Notification Service Extension/LegacyNotificationService.swift
> +      DatadogWrapper.shared()?.log(level: .debug, message: message)
But don't worry about it, we can revise the extension logs separately.

2022-12-20 14:56 UTC, netbe commented on Cartfile.resolved
> +github "microsoft/plcrashreporter" "1.11.0"
it comes from the cartfile of datadog yes, but not added to the target

2022-12-20 15:08 UTC, netbe commented on Wire Notification Service Extension/LegacyNotificationService.swift
> +      DatadogWrapper.shared()?.log(level: .debug, message: message)
done

2022-12-22 12:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios?pullRequest=6001) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios?pullRequest=6001) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: netbe<br/>:x: johnxnguyen<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios?pullRequest=6001) it.</sub>

2022-12-22 13:43 UTC, merged